genesis_id = ""
system = "Gizer"
dependencies = ["Ethereum"]
icon = "gizer"

[token]
name = "gizer token"
symbol = "GZR"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "The Global Gaming Network "

[crowdsales]
start_date = "2017-10-20T00:00:00"
end_date = "2017-11-20T00:00:00"
end_date_plan = "2017-11-20T00:00:00"
genesis_address = [""]
funding_terms = "https://tokensale.gizer.io/wp-content/uploads/2017/09/GZR-Terms-of-Use.pdf"
funding_url = "https://www.saftlaunch.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "tokensale.gizer.io"
url = "https://tokensale.gizer.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Gizer Whitepaper"
url = "https://tokensale.gizer.io/wp-content/uploads/2017/09/Gizer_Whitepaper_V2.2.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Gizer GitHub"
url = "https://github.com/GizerInc"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Gizer Blog"
url = "https://medium.com/@Gizer_Gaming/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2200121"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/Gizer_Gaming"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Gizer Telegram"
url = "https://t.me/joinchat/Em71dQ4KZ8G-XxpArXNuHg"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Gizer/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/GizerGaming/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/watch?v=jJ4EXiZk2zA"
icon = "youtube.png"
tags = ["News"]
