
genesis_id = ""
system = "Universa"
dependencies = ["Ethereum"]
icon = "universa"

[token]
name = "utn token"
symbol = "UTN"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Universa Platform is new generation of blockchain technology"

[crowdsales]
start_date = "2017-10-28T00:00:00"
end_date = "2017-11-30T23:59:00"
end_date_plan = "2017-11-30T23:59:00"
genesis_address = [""]
funding_terms = "https://universa.io/"
funding_url = "https://icobacker.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = ["usd = 99000000"]
raised = [""]

[specs]
supply = 0

[[links]]
type = "website"
name = "universa.io"
url = "https://universa.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Universa Whitepaper"
url = "https://www7.universa.io/files/Universa-Whitepaper-v1.0e.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Universa Github"
url = "https://github.com/UniversaBlockchain/universa"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/Universa_News"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = " Telegram"
url = "https://t.me/Uplatform"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Universablockchain/"
icon = "facebook.png"
tags = ["News"]
