app = []

[blockchain]
project_name = "Nebula AI"
headline = "Decentralized AI Blockchain"
short_description = "Nebula AI is committed to building a decentralized artificial intelligence\ncomputing blockchain (NBAI) that reduces the energy costs of traditional Proof\nof Work by converting GPU mining machines into AI computing services.The\nAI transactions recorded on NBAI will be irreversible. The distributed computing\nnetwork also ensures high concurrency and low latency computing power.\nThe conversion of GPU mining machines makes it possible to provide more\ncost-effective artificial intelligence services.\nNebula AI will cooperate with large-scale third-party Internet data centers\nto provide adequate computing power for AI computing. Nebula AI has\nestablished an artificial intelligence training centre in Canada. System-based\nquantitative finance, image identification and other blockchain applications are\nalso in development.\nThe well-developed NBAI ecosystem integrates the top-level applications\nsuch as DAI App, scientific research and application, university education, and\nthe bottom-level of NBAI blockchain, Artificial Intelligence Mining Machine\nand Artificial Intelligence Data Center. The innovative economic model of\nNBAI ecosystem is the realization of a complete set of value-added economic\nsystems."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://www.nebula-ai.com/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://www.nebula-ai.com/whitepaper/NBAI_whitepaper_EN.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/nebulaai"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/nebula_ai"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/NebulaAICommunity"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/NebulaAI/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://tokensale.nebula-ai.network/"
    sales_agreement = "https://www.nebula-ai.com/whitepaper/NBAI_whitepaper_EN.pdf"

    [ico.common_info.token_distribution]
    total_supply = "6700000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "45"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "25"
      description = "Held by the foundation & community"

      [[ico.common_info.token_distribution.shares]]
      percent = "15"
      description = "Held by the core team"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Held by the early-stage investors"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Held by the marketing & Partner supporters"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = ""
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "ETH"
      amount = "12000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-30"
    end_date = "2018-04-30"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "NBAI tokens"
symbol = "NBAI"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = "The initial release is 6.7 billion tokens. Each year a certain amount of tokens\nare produced, the amount decreases from 2% per year to 0.2% in six years. Tokens\nare consumed when users use customized predictive features of artificial intelligence,\nand the amount of tokens consumed depends on the amount of computation. As the\nsystem’s accuracy increases, the demand for tokens will increase."
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""