app = []

[blockchain]
project_name = "Tru Reputation"
headline = "Decentralized Proof of Reputation Network"
short_description = "This document describes the Tru Reputation Protocol, a blockchain protocol that revolutionizes Reputation &\nRatings in digital interactions. Our goal is to create a next-generation solution to the problem of trust and\nreputation that will solve some of the longest standing and most costly problems in digital ecosystems whilst\nalso providing an on-ramp from off-blockchain users to blockchain platforms.\nThe Tru Reputation Protocol provides a unique and revolutionary solution to Reputation by moving away from\nRatings & Reviews towards the selection of easy-to-understand words and phrases when describing an\ninteraction. Moreover, the Tru Reputation Protocol provides the first digital solution to persisting Reputation\nbetween platforms and reward contributors for their feedback creating the first Proof of Reputation network. "
state = "1"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://tru.ltd/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://tru.ltd/Tru_Reputation_Protocol_White_Paper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/TruLtd"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://blog.tru.ltd/"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/tru_ltd"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/truprotocol"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "slack"
  name = "Slack"
  url = "https://tru.ltd/slack"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/truprotocol/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://tru.ltd/tokensale"
    sales_agreement = "https://tru.ltd/tokensale"

    [ico.common_info.token_distribution]
    total_supply = ""

      [[ico.common_info.token_distribution.shares]]
      percent = "50"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "Token Reserve"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Team"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Partnerships"

      [[ico.common_info.token_distribution.shares]]
      percent = "8"
      description = "Bounties"

      [[ico.common_info.token_distribution.shares]]
      percent = "2"
      description = "Advisors"

    [[ico.common_info.use_of_proceeds]]
    percent = "30"
    description = "Development & Engineering"

    [[ico.common_info.use_of_proceeds]]
    percent = "25"
    description = "Business Development & Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "CryptoCurrency Reserve"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Operations"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Legal"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Contingency"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Supporting Projects Donations"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Pre-Sale"
  phase_status = "Finished"

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "5000000"
    sold_tokens = "133750"
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      address = "0x33358AD0D06fAfA08AEebffb3f66ACd05F6D08be"
      currency = "ETH"

    [ico.phases.dates]
    start_date = "2018-01-04"
    end_date = "2018-04-02"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = "52127"

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "25%"
      condition = "Pre-Sale"

    [[ico.phases.contract]]
    address = "0x19662C22eaaB9FB69Add72ef54B296C5a72593B5"

[[token]]
name = "Tru Reputation Token"
symbol = "TRU"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""