app = []

[blockchain]
project_name = "FTEC"
headline = "An ecosystem for trading activities on cryptocurrency markets"
short_description = "There are many services, bots, signals, academies, neural networks and\nother products for successful trading.\nBut where can one find a place that combines all these tools?\nWhat will be equally useful and convenient for both novice and\nexperienced trader?\nWe are glad to introduce FTEC - the first trading cryptocurrency\necosystem.\nOur global mission is to reduce the number of unprofessional traders.\nThe idea behind this project is very clear and simple: to create a holistic\necosystem that will contain all the necessary tools for users with any level\nof experience and knowledge in the field of cryptocurrencies.\nWe already have currently running projects based on algorithms for\nautomatic trading on cryptomarkets, they gave us a great and valuable\nexperience and therefore we moved on to fulfill more ambitious goals.\nThe ecosystem offers a complex of 15 original solutions for:\nBoosting your sales efficiency\n(by using smart trading systems)\nSaving your time\n(by using neuronetworks for information flow filtering)\nFTEC is an ecosystem of intelligent services and neural networks\nfor conducting effective trading activities on cryptocurrency\nmarkets.\n4\nStudying the specifics of crypto trading\n(with the help of automatized cryptoacademy and broad\ndatabase)\nImproving your trading strategies\n(by using a smart system for analyzing your trading history on\ncryptocurrency markets)\nMinimizing the risks of the trading activity\n(by using the tips of the automatic search for most profitable\noffers on the market)\nReceiving the latest trends in the industry\n(by means of smart service for analyzing social networks and\nweb search data)"
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://ftec.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://ftec.io/en/whitepaper"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/FtecFoundation/FtecMainModule"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@ftecfound"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=3161171.new#new"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/ftec_found"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/user/ftecfound"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/ftec.io/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://ftec.io/?utm_source=cyber.fund"
    sales_agreement = "https://ftec.io/en/whitepaper"

    [ico.common_info.token_distribution]
    total_supply = "998400000"

      [[ico.common_info.token_distribution.shares]]
      percent = "85"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "7"
      description = "Team"

      [[ico.common_info.token_distribution.shares]]
      percent = "3"
      description = "Advisors"

      [[ico.common_info.token_distribution.shares]]
      percent = "2"
      description = "Bounty"

      [[ico.common_info.token_distribution.shares]]
      percent = "2"
      description = "Airdrop"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Pre-Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "99840000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "ETH"
      amount = "4000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2019-04-11"
    end_date = "2018-05-08"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "55%"
      condition = "0 - 1 000 ETH"

      [[ico.phases.prices.bonuses]]
      amount = "50%"
      condition = "1 000 - 2 000 ETH"

      [[ico.phases.prices.bonuses]]
      amount = "45%"
      condition = "2 000 - 4 000 ETH"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Mail Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "748800000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-05-29"
    end_date = "2018-06-21"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "30%"
      condition = "4 000 - 8 000"

      [[ico.phases.prices.bonuses]]
      amount = "25%"
      condition = "8 000 - 13 000"

      [[ico.phases.prices.bonuses]]
      amount = "20%"
      condition = "13 000 - 19 000"

      [[ico.phases.prices.bonuses]]
      amount = "15%"
      condition = "19 000 - 28 000"

      [[ico.phases.prices.bonuses]]
      amount = "10%"
      condition = "28 000 - 40 000"

[[token]]
name = "FTEC Token"
symbol = "FTEC"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""