app = []

[blockchain]
project_name = "ZeroState"
headline = "EMOTIONAL INTELLIGENCE POWERED BY BLOCKCHAIN"
short_description = "ZeroState is the world’s first emotional intelligence platform. It\nhelps advertisers around the world increase the loyalty of their\ncustomers by analyzing their emotional involvement.\nEmotional intelligence (EQ) is what we feel. It is the feelings that are born inside\nus long before our brain can assess the situation, apply social filters and decide\nwhether it is «good» or «bad».\nZeroState uses an application to collect such feelings. The users are motivated to\nshare as they learn about a new product and earn money at the same time."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://zerostate.io/zerostate_whitepaper_en.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://zerostate.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/0stateapp"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@zerostate"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=3070843.0"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/ZeroStateDapp"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/zerostate_chat"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/user/zerostate_me"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/zerostate.info/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://zerostate.io/"
    sales_agreement = "https://zerostate.io/zerostate_whitepaper_en.pdf"

    [ico.common_info.token_distribution]
    total_supply = "100000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "65"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "Reserve fund"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Main team"

      [[ico.common_info.token_distribution.shares]]
      percent = "3"
      description = "Bounty programm"

      [[ico.common_info.token_distribution.shares]]
      percent = "2"
      description = "Business advisors"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Team"

    [[ico.common_info.use_of_proceeds]]
    percent = "33"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "16"
    description = "Product and blockchain development"

    [[ico.common_info.use_of_proceeds]]
    percent = "2"
    description = "Legal expenses"

    [[ico.common_info.use_of_proceeds]]
    percent = "14"
    description = "Business expenses"

    [[ico.common_info.use_of_proceeds]]
    percent = "11"
    description = "Scaling"

    [[ico.common_info.use_of_proceeds]]
    percent = "14"
    description = "Operational expenses"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Pre-Sale"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "5000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "2000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-21"
    end_date = "2018-05-31"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "50%"
      condition = "Presale"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Main Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "59000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "20000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-06-21"
    end_date = "2018-08-31"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "ZSCoin"
symbol = "ZSC"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""