app = []

[blockchain]
project_name = "CoinMetro"
headline = "Fintech platform fueling the future of blockchain"
short_description = "Designed for mainstream adoption, the CoinMetro platform will be an all-in-one solution for crypto geared towards maximizing client value. We will deliver a rock-solid, user-focused framework that offers unparalleled mobility between blockchain-based digital assets and traditional markets.\nThe CoinMetro Ecosystem will include (i) a fast, intuitive exchange, (ii) a feature-rich trading platform offering unique digital asset investment opportunities, and (iii) a turnkey ICO Express solution. All services will be accessible via a streamlined web application with a stunning UI, fully integrated with industry-leading blockchain platforms. CoinMetro will price all services using our own digital ERC20 utility token, called COIN.\nIt is our vision that newcomers to the digital economy will be able to get started with buying their first Bitcoin instantly through our simple, supportive platform. Professional traders will enjoy a fast, secure, and highly flexible environment that integrates familiar features into our digital asset ecosystem. CoinMetro will also offer innovative investment models, such as our Tokenized Asset Management (TAM) platform and an Exchange-Traded Crypto Fund (ETCF) intended to give users access to one-click digital asset diversification options.\nCoinMetro’s partners and Token Buyback Program\nIntegral to CoinMetro is the relationship to our strategic partner, FXPIG, an established Forex (“FX”) broker. FXPIG’s proven track record and experience in providing financial services will help CoinMetro to deliver its planned “Token Buyback Program.” The Token Buyback Program is one of the ways CoinMetro will look to initially stabilize the price of COIN and support market growth (See Section 4.0.4 for more information). Sharing of technology and human resources between CoinMetro and FXPIG will allow the CoinMetro Exchange to offer features, opportunities, and token sale bonuses above and beyond the scope of many current platforms."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://coinmetro.com/whitepaper/"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://coinmetro.com/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@coinmetro"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/CoinMetro"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/CoinMetro"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/CoinMetro"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/CoinMetro/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://coinmetro.com/"
    sales_agreement = "https://coinmetro.com/whitepaper/"

    [ico.common_info.token_distribution]
    total_supply = "500000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "50"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "Liquidity"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "CoinMetro Team & Shareholders"

      [[ico.common_info.token_distribution.shares]]
      percent = "7.5"
      description = "Community Rewards"

      [[ico.common_info.token_distribution.shares]]
      percent = "2.5"
      description = "Advisor Compensation"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Public Pre-Sale"

    [[ico.common_info.use_of_proceeds]]
    percent = "40"
    description = "Platform Development, HR"

    [[ico.common_info.use_of_proceeds]]
    percent = "30"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "War chest; possible buyouts, takeovers, acquisitions, etc."

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Legal, Compliance, Regulatory"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "250000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "35500000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-02-21"
    end_date = "2018-03-31"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = "9370869"

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "CoinMetro token"
symbol = "COIN"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""