genesis_id = ""
system = "Leviar Coin"
dependencies = ["Ethereum"]
icon = "leviarcoin"

[token]
name = "leviar coin"
symbol = "XLC"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "DRM Protection over Blockchain"

[aliases]
coinmarketcap = "LeviarCoin"

[crowdsales]
start_date = "2017-04-07T00:00:00"
end_date = "2017-07-09T00:00:00"
end_date_plan = "2017-07-09T00:00:00"
genesis_address = [""]
funding_terms = "https://leviarcoin.org/assets/pdf/LeviarCoin_White_Paper_v1.pdf"
funding_url = "https://ico.leviarcoin.org/signup"
tokens_sold = ""
tokens_issued = ""
btc_raised = "31.21"
cap_limit = ["usd = 5400000"]
raised = ["usd = 63729.88"]

[[links]]
type = "website"
name = "leviarcoin.org"
url = "https://leviarcoin.org/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Leviar Coin Whitepaper"
url = "https://leviarcoin.org/assets/pdf/LeviarCoin_White_Paper_v1.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Leviar Coin GitHub"
url = "https://github.com/leviarcoin/leviarcoin-src"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1838617"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/hashtag/leviarcoin?src=hash"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Leviar Coin Telegram"
url = "https://t.me/leviarcoinofficial"
icon = "telegram.png"
tags = ["News"]
