genesis_id = ""
dependencies = ["Ethereum"]
system = "BoardRoom"

[aliases]
coinmarketcap = "BoardRoom"

[ratings]

[consensus]
consensus_name = ""
hashing = ""
consensus_type = ""

[descriptions]
state = "Project"
system_type = "cryptoservice"
headline = "Next-gen Blockchain Governance Apparatus"
tags = ["DApp"]
hashtag = ""
twwidid = ""
page_state = "draft"

[token]
name = ""
symbol = ""

[[links]]
name = "boardroom.to"
url = "http://boardroom.to/"
icon = "website.png"
tags = ["Main"]
type = "website"

[[links]]
name = "Twitter"
url = "https://twitter.com/goboardroom"
icon = "twitter.png"
tags = ["Main", "News"]
type = "twitter"

[[links]]
name = "Whitepaper"
url = "http://boardroom.to/BoardRoom_WhitePaper.pdf"
tags = ["News"]
type = "paper"

[[links]]
type = "github"
name = "BoardRoom GitHub"
url = "https://github.com/boardroom-project"
icon = "github.png"
tags = ["Main","Code"]
