genesis_id = ""
system = "Acebusters"
dependencies = ["Independent"]
icon = "acebusters"

[token]
name = ""
symbol = ""

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized poker platform on the Ethereum blockchain"

[crowdsales]
start_date = "2017-09-21T13:00:00"
end_date = "2017-12-21T12:59:00"
end_date_plan = "2017-12-21T12:59:00"
genesis_address = [""]
funding_terms = "http://www.acebusters.com/files/acebusters_whitepaper.pdf"
funding_url = "http://www.acebusters.com/crowdsale"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "acebusters.com"
url = "http://www.acebusters.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Acebusters Whitepaper"
url = "http://www.acebusters.com/files/acebusters_whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Acebusters GitHub"
url = "https://github.com/acebusters"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/ace_busters"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/acebusters.poker"
icon = "facebook.png"
tags = ["News"]
