app = []

[blockchain]
project_name = "RED MWAT"
headline = "Major EU energy company launches energy trading ecosystem"
short_description = "Restart Energy is building a global energy supply platform using blockchain protocol to democratize a sector\nburdened by bureaucracy and transaction costs, freeing up capital, saving consumers money, helping local\nsmall producers earn more and allowing real peer to peer direct energy trading using existing infrastructure.\nEnergy demand globally is expected to nearly double by 2030. With finite resources and the commitment to\nthe UN SDGs, nations must innovate to generate power in a socially, economically, and environmentally\nsustainable manner. The European Union Member States and the United States have begun piloting reforms\nthrough energy market deregulation, allowing private companies to operate in the power retail sector.\nCountries across Asia such as Japan, South Korea, Taiwan, Malaysia, Thailand, Philippines and Singapore have\nopted for market deregulation in a bid to create sustainability while China and India are slated to follow from\n2018."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://restartenergy.io/Restart_Energy_Whitepaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://restartenergy.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://blog.restartenergy.io/"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/TransylvaniaHighTech/RestartEnergyICO"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2572702.20"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/restartenergyio"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/restartenergy"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/RestartEnergy"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/Restart-Energy-Democracy-140703160017376/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://restartenergy.io/"
    sales_agreement = "https://restartenergy.io/Restart_Energy_Whitepaper.pdf"

    [ico.common_info.token_distribution]
    total_supply = "500000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "80"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "12"
      description = "Team"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Advisors"

      [[ico.common_info.token_distribution.shares]]
      percent = "3"
      description = "Bounty"

    [[ico.common_info.use_of_proceeds]]
    percent = "60"
    description = "Red Platform global expansion"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Red Platform development"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Upstream integration"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "400000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-01-15"
    end_date = "2018-01-23"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "20%"
      condition = "10000$ - more"

[[token]]
name = "RED MegaWatt Token"
symbol = "MWAT"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""