
genesis_id = ""
system = "Simple Token"
dependencies = ["Ethereum"]
icon = "simpletoken"

[token]
name = "st token"
symbol = "ST"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Token to Power Your Business"

[crowdsales]
start_date = "2017-11-14T00:00:00"
end_date = "2017-11-21T00:00:00"
end_date_plan = "2017-11-21T00:00:00"
genesis_address = [""]
funding_terms = "https://simpletoken.org/"
funding_url = "https://simpletoken.org/"
tokens_sold = ""
tokens_issued = "800000000"
btc_raised = ""
cap_limit = ["usd = 40000000"]
raised = [""]

[specs]
supply = 800000000

[[links]]
type = "website"
name = "simpletoken.org"
url = "https://simpletoken.org/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Simple Token Whitepaper"
url = "https://drive.google.com/file/d/0Bwgf8QuAEOb7Z2xIeUlLd21DSjQ/view"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Simple Token Github"
url = "https://github.com/OpenSTFoundation"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = "Simple Token Blog"
url = "https://medium.com/simple-token"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/TheSimpleToken"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = " Telegram"
url = "https://t.me/simpletoken"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/simpletoken/"
icon = "facebook.png"
tags = ["News"]
