app = []

[blockchain]
project_name = "Tradershub"
headline = "The first all-in-one Crypto Trading Platform"
short_description = "Tradershub is developed by a strong, cross-functional team in order to eliminate all friction points,\nmaximize profit and mitigate risk by consolidating best trading practices and offer best trading tools\nfor active traders. In collaboration with our existing community of hundreds of active traders and\ninvestors (and growing) around the globe and these goals in mind, we will deliver a smart trading\nplatform that seamlessly connects to multiple exchanges and gateways, along with next generation\ntrading tools and provides active traders and investors of all experience levels a collaborative and\ntrustworthy trading environment.\n1\n Abeer ElBahrawy, Laura Alessandretti, Anne Kandler, Romualdo Pastor-Satorras, Andrea Baronchelli. Evolutionary dynamics of the cryptocurrency market. Royal Society Open Science Journal 4, 2017;\n2 https://www.cnbc.com/2017/11/27/bitcoin-exchange-coinbase-has-more-users-than-stock-brokerage-schwab.html\n5TRADERSHUB WHITEPAPER\nWe will build the best crypto trading platform and one stop tool in the crypto universe for\nprofessional traders. In order to achieve stimulated environment for traders we will create THT tokens\nwhich will be the currency of the platform. THT is a utility token that will be used on the platform to\npay fees and access various features and services. THTs will also be distributed to traders to incentivize\ncommunity building and value creation through a rating-based dynamic reward system.\nThe platform will allow us to aggregate people and trading services together in dynamic ways in order\nto deliver a next-generation trading platform that will become the go-to solution for diversified portfolio\nmanagement and all trading-related activities."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://tradershub.io/en/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://tradershub.io/build/static/downloadables/Whitepaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@tradershub"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/tradershub_io"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/tradershub_comunity"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/Tradershub"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2850010.0"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/Tradershub.io/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://tradershub.io"
    sales_agreement = "https://tradershub.io/build/static/downloadables/Whitepaper.pdf"

    [ico.common_info.token_distribution]
    total_supply = "83385000"

      [[ico.common_info.token_distribution.shares]]
      percent = "60"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "Core team"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Reserve fund"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Bounty pool"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Advisors"

    [[ico.common_info.use_of_proceeds]]
    percent = "40"
    description = "Engineering & Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Marketing & User Acquisition"

    [[ico.common_info.use_of_proceeds]]
    percent = "17"
    description = "Operational & Administrative "

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Partner Engagement "

    [[ico.common_info.use_of_proceeds]]
    percent = "8"
    description = "Legal & Advisory"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Security & Compliance"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token sale"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "50031000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "ETH"
      amount = "12000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-02-22"
    end_date = "2018-03-26"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "40%"
      condition = "Presale Stage 1"

      [[ico.phases.prices.bonuses]]
      amount = "20%"
      condition = "Presale Stage 2"

      [[ico.phases.prices.bonuses]]
      amount = "10%"
      condition = "Crowdsale Stage 3"

      [[ico.phases.prices.bonuses]]
      amount = "5%"
      condition = "Crowdsale Stage 4"

[[token]]
name = "Tradershub Token"
symbol = "THT"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""