app = []

[blockchain]
project_name = "TruePlay"
headline = "Platform for integration of blockchain into gambling projects"
short_description = "TruePlay is a B2B platform with a complex of software solutions for online gaming business. TruePlay is not a\ngambling-provider. TruePlay only allows licensed gambling companies access to their software\n(Software-as-a-service). TruePlay technologies are aimed at developing online gaming and making it as legal and\ntransparent as possible from any point of view.\nPlaying games with the honesty control, based on blockchain technologies, players can be sure that it is\nimpossible to falsify the game outcome. Game statistics gives an understanding that games do meet world\nstandards and are not tuned for losing.\nWebmasters, who cooperate with gambling operators around the world, will be assured that the traffic is not cut.\nOperators and game developers receive a decentralized structure of access to their game content around\nthe world and protection from copying the brand and games"
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://trueplay.io/docs/en/TruePlayWhitePaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://trueplay.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2771636.20"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@TruePlayInfo"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/TruePlayinfo"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/trueplay"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/TruePlayinfo"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://trueplay.io/en/"
    sales_agreement = "https://trueplay.io/docs/en/TruePlayWhitePaper.pdf"

    [ico.common_info.token_distribution]
    total_supply = "70000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "60"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "reserve for the team, consultants and partners"

      [[ico.common_info.token_distribution.shares]]
      percent = "19"
      description = "TruePlay reserve"

      [[ico.common_info.token_distribution.shares]]
      percent = "1"
      description = "Bounty"

    [[ico.common_info.use_of_proceeds]]
    percent = "30"
    description = "Operational activities"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "30"
    description = "TruePlay reserve"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Marketing"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "42000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "ETH"
      amount = "43000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-05-15"
    end_date = "2018-06-30"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "1300 TPLAY / 1.2 ETH"
      condition = "TruePlay Early Sale"

      [[ico.phases.prices.bonuses]]
      amount = "1200 TPLAY / 1.2 ETH "
      condition = "1st stage TruePlay Token Sale"

      [[ico.phases.prices.bonuses]]
      amount = "1100 TPLAY / 1.2 ETH "
      condition = "2nd stage TruePlay Token Sale"

      [[ico.phases.prices.bonuses]]
      amount = "1000 TPLAY / 1.2 ETH "
      condition = "3rd stage TruePlay Token Sale"

[[token]]
name = "TPLAY Token"
symbol = "TPLAY"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""