genesis_id = ""
system = "MingoCoin"
dependencies = ["Ethereum"]
icon = "mingocoin"

[token]
name = "mingo token"
symbol = "MGT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "CryptoCurrency Tutor With Multi-Platform Messenger"

[crowdsales]
start_date = "2017-09-25T14:00:00"
end_date = "2017-10-23T14:00:00"
end_date_plan = "2017-10-09T14:00:00"
genesis_address = [""]
funding_terms = "https://goo.gl/4RytLd"
funding_url = "https://goo.gl/3wnYd6"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "mingocoin.com"
url = "https://mingocoin.com/?utm_source=cyper%20fund&utm_medium=ico%20listing%20page"
tags = ["Main"]

[[links]]
type = "paper"
name = "MingoCoin Whitepaper"
url = "https://firebasestorage.googleapis.com/v0/b/mingo-2bdfc.appspot.com/o/Whitepaper.pdf?alt=media&token=e709359a-b76f-4230-b9a8-2c374ccc464d&utm_source=cyper%20fund&utm_medium=ico%20listing%20page"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "MingoCoin GitHub"
url = "https://github.com/mingocoin/contracts"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "MingoCoin Blog"
url = "https://medium.com/mingocoin"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/mingocoin"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "MingoCoin Telegram"
url = "https://t.me/joinchat/EoTxKELtcbkH3UZJzoaZ0w"
icon = "telegram.png"
tags = ["News"]
