genesis_id = ""
system = "Divi Project"
dependencies = ["Ethereum"]
icon = "diviproject"

[token]
name = "divi token"
symbol = "DIVX"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Bridging the gap between crypto and the masses"

[crowdsales]
start_date = "2017-10-12T10:00:00"
end_date = "2017-11-02T10:00:00"
end_date_plan = "2017-11-02T10:00:00"
genesis_address = [""]
funding_terms = "https://diviproject.org/"
funding_url = "https://diviproject.org/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "diviproject.org"
url = "https://diviproject.org/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Divi Project Whitepaper"
url = "https://diviproject.org/files/Divi-WP.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Divi Project GitHub"
url = "https://github.com/Divicoin"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Divi Project Blog"
url = "https://medium.com/diviproject"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/diviproject"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Divi Project Telegram"
url = "https://t.me/joinchat/EAdiTQ3yZk_GkqU0IdG-Gg"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Divi Project Slack"
url = "https://diviproject.slack.com/join/shared_invite/MjMzNzQwMDg0NTMzLTE1MDQwNTgxODUtM2IzMjJjYTk2OQ"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/DiviProject/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/diviproject"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCihooU0crqQkBOvV0_lsRnw"
icon = "youtube.png"
tags = ["News"]
