app = []

[blockchain]
project_name = "Noku"
headline = "The Blockchain Money Company"
short_description = "Our first product will be a token that we sell for 1 EUR (plus transaction cost)\nand which we then buy-back for 1 EUR (minus transaction cost) should the\ncustomer wish to sell back to the Noku Company.\nA serie of tokens will follow. For example it will be possible for Noku to\nrelease: 1 GBPN for 1 GBP, or 1 CHFN for 1 CHF.\n noku.io 7\nIf a customer wants to buy a “Buy-Back Token”, he has to register for a\nNoku account and do the KYC procedure. The token (not the customer) has\nBuy-Back right with the Noku Company. However, if a customer wants to sell\na Buy-Back Token, he must have a registered Noku account, or register a\nNoku account with KYC procedure. If a customer does not comply with the\nKYC/AML Noku procedure, they cannot buy or sell Buy-Back Token from/to\nthe Noku Company. Only Noku Company can sell or buy Noku Buy-Back\nToken."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://www.noku.io/Noku-White_Paper_Draft_0-9-5.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://www.noku.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/nokugroup"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/noku-wallet/wallet"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2518812.0"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/NokuTeam"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/nokuofficial"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/Noku-317917408638309/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://www.noku.io/"
    sales_agreement = "https://www.noku.io/Noku-White_Paper_BETA_0-9-5.pdf"

    [ico.common_info.token_distribution]
    total_supply = "19250000"

      [[ico.common_info.token_distribution.shares]]
      percent = "85"
      description = "Hold & Locked by Noku"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Early Investors"

    [[ico.common_info.use_of_proceeds]]
    percent = "30"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Legal & Compliance"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Research & Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "IT Infrastructure"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Management & Administration"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "ICO"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "15000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2017-12-20"
    end_date = "2018-01-19"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "NOKU token"
symbol = "NOKU"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""