genesis_id = ""
system = "Matryx"
dependencies = ["Ethereum"]
icon = "matryx"

[token]
name = "matryx token"
symbol = "MTX"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized Collaboration Platform"

[crowdsales]
start_date = "2017-08-13T15:00:00"
end_date = "2017-09-13T15:00:00"
end_date_plan = "2017-09-13T15:00:00"
genesis_address = [""]
funding_terms = "https://www.matryx.ai/"
funding_url = "https://www.matryx.ai/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "matryx.ai"
url = "https://www.matryx.ai/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Matryx Whitepaper"
url = "https://www.matryx.ai/matryx-whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Matryx GitHub"
url = "https://github.com/matryx"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Matryx Blog"
url = "https://blog.matryx.ai/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2141614.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/intent/follow?original_referer=http%3A%2F%2Flocalhost%3A8080%2F&ref_src=twsrc%5Etfw&region=follow_link&screen_name=matryx_ai&tw_p=followbutton"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Matryx Telegram"
url = "https://t.me/matryxai"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/matryxai/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCmyCwkgekVmLzONJZ1jQk-A"
icon = "youtube.png"
tags = ["News"]
