
genesis_id = ""
system = "BitClave"
dependencies = ["Ethereum"]
icon = "bitclave"

[token]
name = "consumer activity token"
symbol = "CAT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Search engine that works without third entity and pays users."

[crowdsales]
start_date = "2017-11-08T00:00:00"
end_date = "2017-12-08T00:00:00"
end_date_plan = "2017-12-08T00:00:00"
genesis_address = [""]
funding_terms = "https://www.bitclave.com/"
funding_url = "https://www.bitclave.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 2000000000

[[links]]
type = "website"
name = "bitclave.com"
url = "https://www.bitclave.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "BitClave Whitepaper"
url = "https://docsend.com/view/2t4zrfx"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "BitClave Github"
url = "https://github.com/bitclave/"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = "BitClave Blog"
url = "https://medium.com/@BitClave"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/bitclave"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "BitClave Slack"
url = "https://slack.bitclave.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "BitClave Telegram"
url = "https://t.me/BitClaveCommunity"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/bitclave"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCtibs4mNHqbPn-NGnFtK6yg"
icon = "youtube.png"
tags = ["News"]
