app = []

[blockchain]
project_name = "Photochain"
headline = "Photochain uses blockchain technology to reinvent photostocks."
short_description = "Nowadays we live in the innovative era of web 3.0 which enables a global network of people, with the aid of high data availability and high data throughput. The use of blockchain technology enables peer-to-peer (p2p) systems to operate safely and securely, without the need for a central authority. This technology opens up new horizons for software architectures and applications. It provides a safe and verifiable transaction list available to all users at any given time. With so-called Smart Contracts[1], Ethereum blockchain technology opens up the possibility of checking correct compliance with digital agreements by using a machine. Therefore, the conditions for the conclusion of a smart contract are met only if both parties have fulfilled their part of the digital contract. In doing so, the machine leaves no room for any malicious tampering. The flexibility of the Ethereum language ‘Solidity’ facilitates the implementation of many use cases, uses which until not too long ago would have been regarded as utopian.\n\nWith the p2p platform Photochain, we are releasing a new concept as the next generation of a stock photography platform. We use this technology to enable fair p2p trading of digital works between artists and buyers.\n\nBy doing so, the specialized terms of use for this platform, ensure a secure, uncomplicated and fair trading process for both parties. Moreover, the artist receives up to 95% of the final selling price.\n"
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://photochain.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://docs.google.com/document/d/1C4UPA9-9o2cOLJOEYMIVwN_Fi3Ebtn2YcRua58hQ7_0/edit"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/photochain"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/photochain"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/photochain_io"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/Photochain-141364963181927"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://photochain.io/"
    sales_agreement = "https://photochain.io/"

    [ico.common_info.token_distribution]
    total_supply = "230000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "79"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "11"
      description = "Team & Management"

      [[ico.common_info.token_distribution.shares]]
      percent = "7"
      description = "Bounties and Partners"

      [[ico.common_info.token_distribution.shares]]
      percent = "3"
      description = "Legal & Advisory"

    [[ico.common_info.use_of_proceeds]]
    percent = "30"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "30"
    description = "IT Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "8"
    description = "Infrastructure"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Copyright and Licensing"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "R&D and Platform Evolution"

    [[ico.common_info.use_of_proceeds]]
    percent = "4"
    description = "Legal, Accounting and Audit"

    [[ico.common_info.use_of_proceeds]]
    percent = "4"
    description = "Cooperations with Photo Agencies"

    [[ico.common_info.use_of_proceeds]]
    percent = "4"
    description = "Allocation to contributors"

    [[ico.common_info.use_of_proceeds]]
    percent = "3"
    description = "Business Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "2"
    description = "Business Development"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "230000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-04-06"
    end_date = "2018-05-06"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "PHOTON Token"
symbol = "PHT"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""