app = []

[blockchain]
project_name = "Elementh"
headline = "Elementh is a blockchain platform for e-commerce"
short_description = "One of Elementh’s main objectives is to implement the blockchain technology into e-commerce. In setting this kind of objective, Elementh aims to fully utilize the advantages of the technology and make e-commerce as efficient as possible. Step-by-step introduction of the blockchain technology into trade will promote global expansion of Elementh. This combination does not require a drastic change of business processes of the market participants.\n\nWe have been actively participating in the e-commerce market since 2007, creating the project Miiix [1] in 2012. Its main goal is to standardize nomenclature in the e-commerce market. For six years, we have been helping online retailers to compare millions of goods from thousands of suppliers. Owing to our algorithms based on the use of machine learning, we can automate hundreds of processes to update real-time supplier stock data. Indeed, we have changed immensely since 2012 as a result of both cooperation and feedback from several thousands of retailers, marketplaces, distributors and manufacturers from different countries.\n\nElementh is the next level in Miiix development. Elementh allows everyone to access real-time stock inventory and price data of the vendors inside the blockchain.\n\nTrust and decentralized nature of the Elementh blockchain gives consumers the opportunity to find the best deal and sellers to conduct business more quickly."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://github.com/ElementhFoundation/Documentation/blob/master/ElementhWhitepaperEN.md#elementh-foundation-economy"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://elementh.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/ElementhFoundation"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@sergeyryabov_676"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2590603.new#new"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/Ahooleeman"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/elementh_community"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/Elementh/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/Elementh-1371154296341075/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://elementh.io/"
    sales_agreement = "https://github.com/ElementhFoundation/Documentation/blob/master/ElementhWhitepaperEN.md"

    [ico.common_info.token_distribution]
    total_supply = "303000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "71.78"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "14.85"
      description = "Team"

      [[ico.common_info.token_distribution.shares]]
      percent = "13.37"
      description = "partners and advisors"

    [[ico.common_info.use_of_proceeds]]
    percent = "50"
    description = "Technology development"

    [[ico.common_info.use_of_proceeds]]
    percent = "35"
    description = "Business development & marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Reinvestment"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Daily operation"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Pre-Sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = ""
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-01-15"
    end_date = "2018-02-14"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = "910"

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Main Sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = ""
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "ETH"
      amount = "30000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-04-01"
    end_date = "2018-04-30"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "30%"
      condition = "1st day"

      [[ico.phases.prices.bonuses]]
      amount = "15%"
      condition = "2nd day"

[[token]]
name = "Elementh Token"
symbol = "EEE"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""