[blockchain]
project_name = " Ceyron"
headline = "Globally accepted cryptocurrency"
short_description = "Каждый держатель Ceyron сможет использовать свои монеты на биржах для торговли, а также передавать их другим пользователям или произвести какую-либо международную оплату. \nТакже предусмотрена CEY карта, которая будет физической, виртуальной и дебетовой картой  MasterCard с мобильным приложением. Карты выпускаются с чипом, большинство из них также будут и бесконтактными. Наряду с предложениями по сделкам с ценными бумагами, CFL-карта предлагает возможность удерживать средства в основных крипто-валютах с одинаковой ликвидностью и транзакционными издержками."
logo = ""
state = "0"
dependency = "Ethereum"
consensus_name = "Proof-of-Work"

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://ceyron.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://ceyron.io/wp-content/uploads/2018/02/White-Paper-ICO-CEY-Token-UPDATED31012018.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/Ceyron/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/CeyronICO"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/joinchat/HlFUXhLIUYQL88_NtoM4sA"
  tags = [
    "News"
  ]

  [[blockchain.milestone]]
  number = 1.0
  name = "ICO starts"
  start_date = "2018 Q1 "
  current_status = "In work"
  value = false

  [[blockchain.milestone]]
  number = 2.0
  name = "Listing on crypto exchanges"
  start_date = "2018 Q4"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 3.0
  name = "  Build a secured credit portfolio with the Fund; "
  start_date = "2019 Q1"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 4.0
  name = "Expand CEY Debit Card plan and capabilities, integrate strategic partner Debit Cards with CEY Debit Card and extend the local fiat debit card capabilities including crypto wallets; "
  start_date = "2019 Q1"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 5.0
  name = "Hire engineers for integrating to build out cryptocurrency exchange and Debit Card features."
  start_date = "2019 Q1"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 6.0
  name = " Launch of the CEY Debit Card Program, in which CEY intends to open approximately fifteen thousand (15,000) to twenty thousand (20,000) cards worldwide."
  start_date = "2019 Q1"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 7.0
  name = "Complete the cryptocurrency exchange and include cross exchange trading capabilities, increase the tokens listed on such exchange to other ERC20 tokens, and complete seamless integration of these exchange platforms to debit cards."
  start_date = "2019 Q2"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 8.0
  name = "Build decentralized applications to solve for complex banking needs, like smart contracts to facilitate the payment of sales tax at point of sale terminals."
  start_date = "2020 Q1"
  current_status = "Planned"
  value = false

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 1.0
  current_phase_status = ""

    [ico.common_info.token_distribution]
    total_supply = "250000000"

      [[ico.common_info.token_distribution.shares]]
      description = ""
      percent = 0.0

    [[ico.common_info.use_of_proceeds]]
    percent = "82"
    description = "Portfolio Investment"

    [[ico.common_info.use_of_proceeds]]
    percent = "12"
    description = "Technology & Product Dev"

    [[ico.common_info.use_of_proceeds]]
    percent = "3"
    description = "Working Capital"

    [[ico.common_info.use_of_proceeds]]
    percent = "3"
    description = "Fees & Expenses"

  [[ico.phases]]
  phase_name = "Pre-Sale"
  phase_status = "Active"
  phase_num = 0.0

    [ico.phases.registration]
    start_date = "2018-02-16T00:00:00.000Z"
    end_date = "2018-03-15T00:00:00.000Z"
    website = "https://ceyron.io/tokensale/"
    terms = "https://ceyron.io/terms-of-service/"

    [ico.phases.terms]
    sales_agreement = "https://ceyron.io/terms-of-service/"
    sales_url = "https://ceyron.io/tokensale/"
    issued_tokens = "250000000"
    sold_tokens = "2700000"
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = 0.0

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      currency = ""
      address = ""

    [ico.phases.dates]
    start_date = "2018-02-16T00:00:00.000Z"
    end_date = "2018-03-15T00:00:00.000Z"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = 0.0

    [[ico.phases.contract]]
    address = ""
    type = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "USD"
      price = "1"

      [[ico.phases.prices.bonuses]]
      amount = "10% Extra Coins"
      condition = "USD $ 500-1000 "
      index = 0.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "15% Extra Coins"
      condition = "USD $ 1001-5000"
      index = 1.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "20% Extra Coins"
      condition = "USD $ 5001-15000"
      index = 2.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "25% Extra Coins"
      condition = " USD $ 15001-25000 "
      index = 3.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = " 30% Extra Coins"
      condition = "USD $ 25001-50000"
      index = 4.0
      value = false

  [[ico.phases]]
  phase_name = "Token Sale"
  phase_status = "Planned"
  phase_num = 1.0

    [ico.phases.registration]
    start_date = "2018-03-16T00:00:00.000Z"
    end_date = "2018-07-15T00:00:00.000Z"
    website = "https://ceyron.io/tokensale/"
    terms = "https://ceyron.io"

    [ico.phases.terms]
    sales_agreement = "https://ceyron.io/terms-of-service/"
    sales_url = "https://ceyron.io/tokensale/"
    issued_tokens = "70000000"
    sold_tokens = 0.0
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "45000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      currency = ""
      address = ""

    [ico.phases.dates]
    start_date = "2018-03-16T00:00:00.000Z"
    end_date = "2018-07-15T00:00:00.000Z"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = 0.0

    [[ico.phases.contract]]
    address = ""
    type = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = 0.0

      [[ico.phases.prices.bonuses]]
      description = ""
      percent = ""

[app]
info = []

[[token]]
inflation_rate = ""
circulation_terms = ""
governance_rights_org = ""
governance_rights_project = "CEY Tokens hold no rights in the Company."
name = "CEY Tokens"
symbol = "CEY"
token_purpose = "Utility"
token_type = "Core token"

[[exchange]]
exchange = ""
date = ""
price = ""
volume = ""

[[label]]
blockchain = ""
address = ""
balance = ""