app = []

[blockchain]
project_name = "Hive Power"
headline = "Shared energy for a brighter future"
short_description = "A Hive provides a distributed energy market platform where every prosumer can exchange its\nenergy consumption and production. The basic component of a Hive is the Worker. A Worker\nis a blockchain enabled electrical meter and it is generally linked to a prosumer, e.g. a single\nappliance, a single family household, a storage system, a solar power plant, an industrial facility.\nA Worker belongs to a single Hive. A Worker measures and certifies its own energy production\nand consumption, and joins the Hive energy market.\nMore precisely, the interface with the electrical grid is monitored by an Ethereum Meter equipped\nwith a hardware oracle, a cryptographically attestable anti-tampering sensor. The certified energy\ndata from the hardware oracle is gathered by a blockchain computer and tokenized by a smart\ncontract. The Worker also includes a forecasting service that predicts the energy consumption/production\nand an energy bidding system interacting with the Hive through the worker smart contract.\nEach Hive is created by a Beekeeper and contains a Queen, which acts as an aggregator for the\nHive. The main goal of the Queen is to help the Workers coordination, by collecting the production\nand consumption forecasts of the single Workers, aggregating them and communicating them back\nto the Hive in an anonymous form. The Queen also collects data about energy production/consumption\nrelated to the Workers and distributes the corresponding fiat to the Workers retaining a\npart for the Hive owner.\nA Hive consists of a Queen, a population of Workers and an owner. Each Worker is logically linked\nto the Queen with a connector. Hives can exchange energy profiting of a hierarchical (motherdaughter)\nrelationship between them. Each Hive possesses only one Queen, which in the upper\nhierarchical level will act as a Worker, representing the entire Hive as a single entity"
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"

  [[blockchain.milestone]]
  number = 1.0
  name = " Hive Power Beta "
  start_date = "Q4 2017 - Q2 2018"
  current_status = "In work"

  [[blockchain.milestone]]
  number = 2.0
  name = "Hive Power 1.0 "
  start_date = "Q2 2018 - Q1 2019"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 3.0
  name = "Hive Power 2.0 "
  start_date = "Q1 2019 - Q1 2020"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 4.0
  name = "Hive Power 3.0 "
  start_date = "Q1 2020 and beyond"
  current_status = "Planned"

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://www.hivepower.tech/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://v.fastcdn.co/u/a25ac79a/28232572-0-Hive-Power-Whitepape.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/hive-power/"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://blog.hivepower.tech/"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/hive_power"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/hivepower"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/HivePower/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://icoengine.net"
    sales_agreement = "https://blog.hivepower.tech/introducing-the-hvt-crowdsale-f9f50db5a67a"

    [ico.common_info.token_distribution]
    total_supply = "100000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "54"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "33"
      description = "Company"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Founders"

      [[ico.common_info.token_distribution.shares]]
      percent = "3"
      description = "Referral and Airdrop"

    [[ico.common_info.use_of_proceeds]]
    percent = "65"
    description = "R&D"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "Expansion"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Pilot Projects"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "54000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "11000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-04-23"
    end_date = "2018-05-14"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "30%"
      condition = "5'000'000 HVT"

      [[ico.phases.prices.bonuses]]
      amount = "10%"
      condition = "20'000'000 HVT"

[[token]]
name = "Hive Token"
symbol = "HVT"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = "The Hive Owners, who are staking HVTs in the Beekeeper contract, will also have access to Hive\nPower technical governance. More specifically, all the upgrade proposals of Beekeeper contract\nwill be subjected to the vote of Hive Owners. In order to exclude potential speculative actors,\nonly Hive Owners will participate in the governance. Moreover the voting power will be weighted\naccordingly to staking age. Long term and active Hive Owners will have more voting power on the\ntechnical governance."
governance_rights_org = ""