
genesis_id = ""
system = "Mobius"
dependencies = ["independent"]
icon = "mobius"

[token]
name = "mobius token"
symbol = "MOBI"

[consensus]
consensus_type = "POS"
consensus_name = "Proof-of-Stake"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Connecting every device and data stream to blockchain ecosystem"

[crowdsales]
start_date = "2017-11-08T00:00:00"
end_date = "2017-12-08T00:00:00"
end_date_plan = "2017-12-08T00:00:00"
genesis_address = [""]
funding_terms = "https://mobius.network/"
funding_url = "https://mobius.network/token_sale"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 888000000

[[links]]
type = "website"
name = "mobius.network"
url = "https://mobius.network/token_sale"
tags = ["Main"]

[[links]]
type = "paper"
name = "Mobius Whitepaper"
url = "https://mobius.network/mobius_white_paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Mobius Github"
url = "https://github.com/mobius-network"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = "Mobius Blog"
url = "https://medium.com/mobius-network"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/mobius_network"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Mobius-1727395010897177"
icon = "facebook.png"
tags = ["News"]
