app = []

[blockchain]
project_name = "CEEK"
headline = "VR platform for streamed live events and productions"
short_description = "CEEK VR is an award-winning developer and\ndistributor of hardware and software for Omnichannel\ndistribution of Virtual Reality (VR)\nexperiences for multiple world-class partners.\nCEEK provides several channels of VR content\n(both originally created and professionally\nlicensed) using the CEEK Virtual Reality\nPlatform and the patented headsets. CEEK VR\nis in partnerships with globally-renowned\nindustry leaders such as Universal Music,\nApple, T-Mobile, and Baptist Health.\nCEEK’s patent-awarded VR bundles are\ncurrently being sold nationwide through major\nretailers including Best Buy and Target and\nare widely recognized as one of the best\n“mobile ready” VR hardware devices on the\nmarket today.\nCEEK VR recognizes that there are many\nfinancial and technological benefits by moving\nfrom an SQL based technology to a streamlined,\ntransparent, and secure blockchain based\nsystem that offers added financial benefits\nto CEEK, our partners and end users. As\nwe prepare to scale our existing patented\nVirtual Reality Content Delivery Platform, VR\nheadset and solutions toward mainstream\nadoption we have partnered with CEEK\nGLOBAL INNOVATIONS(CGI) World Ltd and\nCGI Global Ltd to offer solutions, collectively\nCEEK aims to solve some of the biggest\nproblems facing the entertainment and\neducational worlds.\nCEEK is the higher echelon virtual reality “killer\napp” for the blockchain and currently boasts\npartnerships with major celebrities and some\nof the world’s largest tech companies offering\nthe entertainment industry and “CEEKERS”\nworldwide one of the most exciting\nopportunities on the market today, as we all\nCEEK A NEW REALITY!"
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://www.dropbox.com/s/1fibdgyjgbfiu6h/CEEK_Virtual%20Reality%20TGE%20White%20Paper.pdf?dl=0%20"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://www.ceek.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/ceek"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/ceekvrtokensale"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/ceekapp/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://www.ceek.io"
    sales_agreement = "https://www.dropbox.com/s/1fibdgyjgbfiu6h/CEEK_Virtual%20Reality%20TGE%20White%20Paper.pdf?dl=0%20"

    [ico.common_info.token_distribution]
    total_supply = "1000000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "50"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "will be reserved to incentive the development community"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "will go to the company, early contributors and advisors"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "will be locked for 3 years as reserves and for future reserves"

    [[ico.common_info.use_of_proceeds]]
    percent = "25"
    description = "CEEK Foundation R&D"

    [[ico.common_info.use_of_proceeds]]
    percent = "25"
    description = "Content & Licenses"

    [[ico.common_info.use_of_proceeds]]
    percent = "25"
    description = "Marketing & Business Development "

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Operations"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Legal"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Contingency"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "500000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "50000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-27"
    end_date = "2018-05-03"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "20%"
      condition = "Pre Sale Week 2"

      [[ico.phases.prices.bonuses]]
      amount = "10%"
      condition = "Pre Sale Week 3"

[[token]]
name = "CEEK token"
symbol = "CEEK"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""