
genesis_id = ""
system = "Props Project"
dependencies = ["Ethereum"]
icon = "propsproject"

[token]
name = "lev token"
symbol = "LEV"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized Ecosystem of Video Applications"

[crowdsales]
start_date = "2017-11-01T00:00:00"
end_date = "2017-12-01T00:00:00"
end_date_plan = "2017-12-01T00:00:00"
genesis_address = [""]
funding_terms = "https://propsproject.com/"
funding_url = "https://propsproject.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 1000000000

[[links]]
type = "website"
name = "propsproject.com"
url = "https://propsproject.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Props Project Whitepaper"
url = "https://propsproject.com/static/PROPS%20Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "Props Project Blog"
url = "https://blog.propsproject.com/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://www.twitter.com/PROPSproject"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Props Project"
url = "https://t.me/propsproject"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/PROPSProject/"
icon = "reddit.png"
tags = ["News"]
