genesis_id = ""
system = "DMarket"
dependencies = ["Ethereum"]
icon = "dmarket"

[token]
name = "dmarket token"
symbol = "DMarket"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized marketplace to turn every virtual item into a real commodity"

[crowdsales]
start_date = "2017-11-03T16:00:00"
end_date = "2017-11-17T16:00:00"
end_date_plan = "2017-11-17T16:00:00"
genesis_address = ["0x4b60B53a6eDCD75f0730ecC22579Df2079F210B0"]
funding_terms = "https://dmarket.io"
funding_url = "https://dmarket.io"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "dmarket.io"
url = "https://dmarket.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "DMarket Whitepaper"
url = "https://dmarket.io/assets/documents/DMarket_white_paper_EN.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "DMarket GitHub"
url = "https://github.com/suntechsoft/dmarket-smartcontract"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "DMarket Blog"
url = "https://medium.com/@dmarket"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2041720.new#new"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/dmarket_io"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "DMarket Telegram"
url = "https://t.me/joinchat/CV8tCULRq_vJ2Xzu9Iopqg"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "DMarket Slack"
url = "https://dmarket.io/slack"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/D_Market/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/dmarketcommunity/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCCF8BhVCdsSr1oy9kA1g5vg"
icon = "youtube.png"
tags = ["News"]
