
genesis_id = ""
system = "Sharpe Capital"
dependencies = ["Ethereum"]
icon = "sharpecapital"

[token]
name = "sharpe token"
symbol = "SHP"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "The Financial Markets Protocol"

[crowdsales]
start_date = "2017-11-13T14:00:00"
end_date = "2017-12-12T14:00:00"
end_date_plan = "2017-12-12T14:00:00"
genesis_address = [""]
funding_terms = "https://sharpe.capital/tokens"
funding_url = "https://sharpe.capital/tokens"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "sharpe.capital"
url = "https://sharpe.capital/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Sharpe Capital Whitepaper"
url = "https://s3-eu-west-1.amazonaws.com/sharpe-website/whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Sharpe Capital GitHub"
url = "https://github.com/sharpe-capital"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Sharpe Capital Blog"
url = "https://medium.com/sharpecapital"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/sharpecapital"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Sharpe Capital Telegram"
url = "https://t.me/sharpecapital"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/sharpecapital"
icon = "facebook.png"
tags = ["News"]