
genesis_id = ""
system = "REGA"
dependencies = ["Ethereum"]
icon = "rega"

[token]
name = "rst token"
symbol = "RST"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "First crowdsurance platform based on blockchain"

[crowdsales]
start_date = "2017-10-15T09:00:00"
end_date = "2017-11-15T18:00:00"
end_date_plan = "2017-11-15T18:00:00"
genesis_address = [""]
funding_terms = "https://rega.life/regatokensale.pdf"
funding_url = "https://regabbp.rega.life/"
tokens_sold = "45655"
tokens_issued = "1500001"
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 3000000

[[links]]
type = "website"
name = "rega.life"
url = "https://rega.life/"
tags = ["Main"]

[[links]]
type = "paper"
name = "REGA Whitepaper"
url = "https://rega.life/regawhitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "REGA Github"
url = "https://github.com/REGA-RS/"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = "Rega Blog"
url = "https://medium.com/@REGA"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2151094"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/REGA20847530"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = " Telegram"
url = "https://t.me/RRSOfficialChat"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = ""
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/regarisksharing"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCf2elu4F1U5hLI60XjL5-1w"
icon = "youtube.png"
tags = ["News"]
