
genesis_id = ""
system = "Nocta"
dependencies = ["Ethereum"]
icon = "nocta"

[token]
name = "nocta token"
symbol = "NOCTA"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "FIRST PREMIUM PLATFORM FOR SEX LEISURE"

[crowdsales]
start_date = "2017-09-18T16:00:00"
end_date = "2017-10-30T16:00:00"
end_date_plan = "2017-10-30T16:00:00"
genesis_address = [""]
funding_terms = "https://nocta.co/get.html"
funding_url = "https://nocta.co/get.html"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 300000000

[[links]]
type = "website"
name = "nocta.co"
url = "https://nocta.co/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Nocta Whitepaper"
url = "https://nocta.co/assets/whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "Nocta Blog"
url = "https://medium.com/@Nocta"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2156189"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/noctaworldwide"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Nocta Telegram"
url = "https://t.me/noctaworld"
icon = "telegram.png"
tags = ["News"]
