genesis_id = ""
system = "Hero Coin"
dependencies = ["Ethereum"]
icon = "herocoin"

[token]
name = "hero coin"
symbol = "HERO"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Reward-based peer to peer betting on the Ethereum Blockchain"

[crowdsales]
start_date = "2017-09-14T14:00:00"
end_date = "2017-10-14T14:00:00"
end_date_plan = "2017-10-14T14:00:00"
genesis_address = [""]
funding_terms = "https://s3-cdn.herocoin.io/HERO_CoinOfferDocument.pdf"
funding_url = "https://www.herocoin.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 2000000000

[[links]]
type = "website"
name = "herocoin.io"
url = "https://www.herocoin.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Hero Coin Whitepaper"
url = "https://s3-cdn.herocoin.io/HERO_Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Hero Coin GitHub"
url = "https://github.com/ByteHeroes/herocoin"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2116864.msg21169697#msg21169697"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/HEROcoinio"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Hero Coin Telegram"
url = "https://t.me/joinchat/FsEwOwtrCZMWwHokEj70Gw"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Hero Coin Slack"
url = "https://herocoin.slack.com/join/shared_invite/enQtMjQyNTQ1NDU3ODYxLTVmMzlmNTg5ZTUyODM4NzFjZGVjNGFlZjYzOTM0MzI1YWIwZWMxN2UzMWMxYWQ2MDE4NDQ3OTE4Y2I1NmMyYjU"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/HEROcoin/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/HEROcoinio/"
icon = "facebook.png"
tags = ["News"]
