app = []

[blockchain]
project_name = "DiscountCoin"
headline = "Discount coin is a local stores oriented crypto."
short_description = "Our mission : Our goal is simple, give the world an opportunity to use crypto-currency everyday\nto buy items at discounted prices in every stores accepting it. The network will reward shop\nowners making an effort to propose those prices by giving them more coins as they accept more\ntransactions.\nOur plans : Using the emerging technology of Proof-of-stake Masternodes, we plan to reward\nstaking people with coins each time a block is mined.\nAs a customer, you will be able to buy your items, pay for the restaurant, or go to the cinema with\na discounted price.\nAs a shop owner, you will sell with a discount but you will earn more coins by staking them is\nyour wallet, thus making a profit as if you sold for more than initial price.\nOur vision : Our vision is long term based.\nWe are planning a wide customer usage during first year to build the Discount network and\nstrengthen POS system with an Intial Coin Offering (ICO).\nMasternode will be rewarding early adopters by great amount during first year. Then we will\npromote our technology to local shop owners, still encouraging them to propose discounted\nprices and earn rewards themselves.\nDiscount Coin network is designed to give great rewards during at least 20 years !"
state = "0"
asset_type = ""
dependency = "independent"
consensus_name = "Proof-of-Stake"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://discountco.in/upload/whitepaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://discountco.in/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/DiscountCoin/dsc"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=3097845.0"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/DiscountCoinDev"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://discountco.in/buy"
    sales_agreement = "https://discountco.in/buy"

    [ico.common_info.token_distribution]
    total_supply = "2000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "75"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "25"
      description = "will be used for bouties, airdrops, signature campaigns and promotion across social media for youtubers or twitter promoters"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "1500000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "98000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-14"
    end_date = "2018-04-30"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "Discount Coin"
symbol = "DISCOUNT"
token_purpose = "Raising funds"
token_type = "Core token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""