
genesis_id = ""
system = "Anti-Bureaucracy"
dependencies = [""]
icon = "antibureaucracy"

[token]
name = "abc token"
symbol = "ABC"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "1st regtech using blockchain for real worldwide cases"

[crowdsales]
start_date = "2017-10-30T18:00:00"
end_date = "2017-11-30T18:00:00"
end_date_plan = "2017-11-30T18:00:00"
genesis_address = [""]
funding_terms = "https://github.com/OriginalMy/originalmy-abc-whitepaper"
funding_url = "https://originalmy.com/ico"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 200000000

[[links]]
type = "website"
name = "originalmy.com"
url = "https://originalmy.com"
tags = ["Main"]

[[links]]
type = "paper"
name = "Anti-Bureaucracy Whitepaper"
url = "https://github.com/OriginalMy/originalmy-abc-whitepaper"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Anti-Bureaucracy Github"
url = "https://github.com/OriginalMy"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/originalmycom"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Anti-Bureaucracy Slack"
url = "https://originalmy.slack.com/messages/webchat/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = " Telegram"
url = "https://telegram.me/originalmy"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://fb.com/originalmycom"
icon = "facebook.png"
tags = ["News"]
