genesis_id = ""
system = "Udiar"
dependencies = ["Ethereum"]
icon = "udiar"

[token]
name = "udiar token"
symbol = "IAR"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Blockchain-based marketplace of intellectual property turnover"

[crowdsales]
start_date = "2017-09-20T00:00:00"
end_date = "2017-11-30T23:59:00"
end_date_plan = "2017-11-30T23:59:00"
genesis_address = [""]
funding_terms = "https://udiar.io/UDIAR-terms-and-conditions.pdf"
funding_url = "https://ico.udiar.io/"
tokens_sold = ""
tokens_issued =""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "udiar.io"
url = "https://udiar.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Udiar Whitepaper"
url = "https://udiar.io/UDIAR-WP-en.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Udiar GitHub"
url = "https://github.com/udiar"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2192590.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/UDIAR_copyright"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Udiar Telegram"
url = "https://t.me/UDIAR"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Udiar Slack"
url = "https://udiar.slack.com/join/shared_invite/enQtMjM3NjQ3NDUzMDI1LWE3YzM5NWE3MDBlM2ZmMzRkZmNkYmRhNmM2YTk3YmY4ZWNjNmFiNzQ1NTFiYjc4ZDIyZDM1NDAxZjNhYzI5ZGY"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/UDIAR.NET/"
icon = "facebook.png"
tags = ["News"]
