genesis_id = ""
system = "Real"
dependencies = ["Ethereum"]
icon = "real"

[token]
name = "real token"
symbol = "REAL"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Real Estate Crypto-Crowdfunding"

[aliases]
coinmarketcap = "REAL"

[crowdsales]
start_date = "2017-08-30T00:00:00"
end_date = "2017-09-30T00:00:00"
end_date_plan = "2017-09-30T00:00:00"
genesis_address = [""]
funding_terms = "http://www.real.markets"
funding_url = "http://www.real.markets"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = ["usd = 10824148"]

[[links]]
type = "website"
name = "real.markets"
url = "https://www.real.markets/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Real Whitepaper"
url = "http://www.real.markets/REAL_Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Real GitHub"
url = "https://github.com/REALToken/real_contract"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Real Blog"
url = "https://medium.com/@real_token/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/real_token"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Real Telegram"
url = "https://t.me/realplatform"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/realestateassetledger"
icon = "facebook.png"
tags = ["News"]
