genesis_id = ""
system = "Gimli"
dependencies = ["Ethereum"]
icon = "gimli"

[token]
name = "gimli token"
symbol = "GIM"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized live stream bets and interactions"

[crowdsales]
start_date = "2017-09-18T10:00:00"
end_date = "2017-10-20T14:00:00"
end_date_plan = "2017-10-20T14:00:00"
genesis_address = [""]
funding_terms = "https://gimli.io/"
funding_url = "https://gimli.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "gimli.io"
url = "https://gimli.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Gimli Whitepaper"
url = "https://gimli.io/wp-content/uploads/2017/07/Gimli-white-paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Gimli GitHub"
url = "https://github.com/thegimliproject"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Gimli Blog"
url = "https://medium.com/gimli-project"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/thegimliproject"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Gimli Telegram"
url = "https://t.me/thegimliproject"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Gimli Slack"
url = "https://auto-invite-contact.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/The-Gimli-Project"
icon = "facebook.png"
tags = ["News"]
