[blockchain]
project_name = "BotGaming"
headline = "Blockchain powered gambling platform for messenger bots"
short_description = "BotGaming is a project combining a marketplace (gaming bots ecosystem) within already\nworking products on connection using a Blockchain technology for inside-coin spenditure. A\nmarketplace is a scalable business model, which is flexible for changes and variability of new\nconcepts and feature adding.\nThe concept of a marketplace should be able to provide the following terms on business\ndevelopment for a BotGaming project:\n1. Assessment - users should be able to acknowledge their activity and BotGaming team\nshould be able to track unit economics of users\n2. User experience - using tracking analysis, BotGaming team would be able to identify\nproblematic points of platform usage and use it for future development\n3. Blockchain and tokenization model usage - gaming bots are connected into one\nsystem with one environment, using a unique account for players\n4. Transparency and easiness to use - Blockchain technology obviously provides this\ncompetitive advantage\n5. Scalability - unlimited borders on how to expand the project worldwide, how to add\ncontent and bots, only legal terms and licensing are considered\nThese described terms should provide a flexible environment not only for project\ndevelopment, but more to token liquidity and design a stable path for growth.\nBotGaming team started game development in 2016, and initially focused on a social\ngambling business model with monetization solely through in-app purchases. Today the\ntotal number of our bots installations on all platforms exceeds 400,000, with more than\n35,000 monthly active users.\nIn 2017, we made a decision to create a solid and designed gambling platform for messenger\napps by obtaining a Gambling License, which entitles our company to operate in Europe\nmarket and then on other markets where online gambling is legal."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://botgaming.me/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://botgaming.me/whitepaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/Botgaming"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@botgaming"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2727253"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/botgaming_me"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/botgamingchat"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/botgaming.me"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://botgaming.me/"
    sales_agreement = "https://botgaming.me/whitepaper.pdf"

    [ico.common_info.token_distribution]
    total_supply = "3625000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "60"
      description = "On Sale"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "Team and owners "

      [[ico.common_info.token_distribution.shares]]
      percent = "15"
      description = "Reserve"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Advisers, Escrow "

    [[ico.common_info.use_of_proceeds]]
    percent = "35"
    description = "Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "40"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Legal"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "Listing on exchange & operations"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Planned"

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "2175000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "20000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-05-07"
    end_date = "2018-06-04"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

    [[ico.phases.contract]]
    address = "0x4de00f12A31263690dcceAafdCaf85197cAf2f8F"

[[token]]
name = "BOT token"
symbol = "BOT"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""

[[app]]
name = "BotGaming"
same_blockchain = "true"
sources_availability = "false"
app_status = "1"
app_type = "Gaming bots ecosystem"
app_url = ""