app = []

[blockchain]
project_name = "Invacio"
headline = "UN FEATURED AI & BLOCKCHAIN STARTUP INVACIO | INV ICO"
short_description = "After five years in development,\nInvacio reaches ICO having\nevolved eleven distinct\ncompany divisions, each an\nexpression of the capabilities\nof our core multi-agent system\nArtificial Intelligence.\nNo mere white paper or prototype, Invacio’s\nachievement has already shown outstanding\nperformance in live tests that have run the\nwhole range of our products and services,\nfrom our ‘Zero-Knowledge’ end-to-end\nencrypted communications, groundbreaking\ndata repository and financial offerings, to\nTAMIUS, the revolutionary decentralized\nblockchain banking system that underlies our\ncryptocurrency. Several of these tests have\nbeen conducted live. Here for example, you\ncan follow the progress of Invacio’s current\nopen experiment designed to test and refine\nthe interaction of certain of our financial-AI’s\nmost basic features.\nIn the main body of this white paper you will\nfind these and other of our solutions and\nresearch areas described in some detail, both\nto introduce the array of services your Invacio\nCoin will open for you and to demonstrate how\n— by covering key interrelated areas including\nbig data, research and development, online\nsecurity, social networking, Zero-Knowledge\ncommunications, blockchain technology,\nintelligence, and with our banking, fintech and\nhedge fund divisions, finance, all grounded\nin our cutting edge artificial intelligence\ntechnologies — Invacio’s business model is\nboth rich and incredibly resilient.\nExecutive\nSummary\nAs will be seen, this\nresilience is in no small part\ndue to Jean. Our core AI,\nJean is not only a locally\nadaptive technology.\nShould any combination of Invacio’s\nelements not be performing as\nwe’d like, Jean has of course\nbeen designed to evaluate and\nrefashion them so that they do; yet\nbecause the successes and failures\nof those elements occur always\nwithin a machine-learning context,\nthose successes and failures\nimmediately contribute also to the\nenhancement of Invacio as a whole.\nIn consequence of this, Invacio is\ncharacterised by an astounding\nplasticity. Even now as we reach\nfrom data and fintech into banking\nand cryptocurrency, a greater\npart of our evolution is a matter\nof Jean’s ever more perfect and\nsubtle adaptation to what secures\nInvacio’s advancement.\nBy taking part in this coin sale\nyou are involving yourself with\na company composed of forex\ntraders, coders, data security\nspecialists, “white hat” hackers,\nengineers, statisticians, thinkers,\nand entrepreneurs. Our team is\ninnovative and curious and because\nfully encouraging of new ideas and\napproaches, we continue to make\nvery sudden and often unpredicted\nadvances in many fields. We\ntherefore invite you to spend your\ntime coming to know us and the\nwork we’re doing by reading this\npaper, exploring our pages, and\nlistening to the informational audio\nand video we have made available. "
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://invest.invacio.com/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://invest.invacio.com/layouts/landing-content-media/2018/01/Final-White-paper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/Invacio"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/Invacio"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/InvacioNetwork/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://invest.invacio.com/account/signup"
    sales_agreement = "https://s3-ap-southeast-1.amazonaws.com/invacio/invacio_home_newsite/invest/ICO+Aggrement+Final.pdf"

    [ico.common_info.token_distribution]
    total_supply = "450000000"
    shares = []

    [[ico.common_info.use_of_proceeds]]
    percent = "40"
    description = "Product Research and Developmen"

    [[ico.common_info.use_of_proceeds]]
    percent = "23"
    description = "Operations"

    [[ico.common_info.use_of_proceeds]]
    percent = "23"
    description = "Infrastructure and Setup Costs"

    [[ico.common_info.use_of_proceeds]]
    percent = "14"
    description = "Marketing"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "42600000"
    sold_tokens = "26347922"
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "30000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-12"
    end_date = "2018-05-14"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "Invacio token"
symbol = "INV"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""