genesis_id = ""
system = "Wanchain"
dependencies = ["Ethereum"]
icon = "wanchain"

[token]
name = "wan coin"
symbol = "WANCOIN"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Distributed Cross-Blockchain Financial Platform "

[crowdsales]
start_date = "2017-10-03T16:00:00"
end_date = "2017-10-25T15:59:00"
end_date_plan = "2017-10-25T15:59:00"
genesis_address = [""]
funding_terms = "https://wanchain.org/tokensale"
funding_url = "https://wanchain.org/tokensale"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "wanchain.org"
url = "https://wanchain.org/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Wanchain Whitepaper"
url = "https://wanchain.org/files/Wanchain-Whitepaper-EN-version.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Wanchain GitHub"
url = "https://github.com/wanchain"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/wanchain_org"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Wanchain Telegram"
url = "https://t.me/WanchainANN"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Wanchain Slack"
url = "https://wanchain.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/wanchain/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/wanchainfoundation/"
icon = "facebook.png"
tags = ["News"]
