app = []

[blockchain]
project_name = "TBIS"
headline = "TBIS is developed on the blockchain platform"
short_description = "Titanium Blockchain Infrastructure Services (TBIS) finally answers the question:\n“What if an entire IT enterprise could be decentralized, including data centers,\nfirewalls, load-balancers, routers, switches, network appliances and servers?”\n• TBIS intends to disrupt the current market leaders in the provisioning and\nvirtualization space.\n• Our core product, Infrastructure as a Service (IaaS) will potentially be released as\na Minimum Viable Product during Q1 2018, before March 1 st\n.\n• TBIS is developed on the blockchain platform, so all changes in the environment\nand assets could potentially be recorded on an immutable ledger, to correlate\nwith standard IT change management and ITIL methodologies.\n• Follow-the-Sun enterprise management and monitoring services, autonomous\nhealing, and optimized disaster recovery and redundancy mechanisms could\npotentially allow TBIS to potentially provide a significantly higher percentage of\nuptime of devices, applications and services, making them a market leader.\n• Since TBIS would operate on the blockchain, the days of Distributed Denial of\nService (DDoS) attacks and other black hat hacker exploits would effectively be\nover.\n• Most, if not all, of the issues associated with similar cloud server products would\nbe solved.\n• The TBIS Administrative User Interface (UI) is intuitive and the simplest to use in the\nindustry, and could potentially be available as a thick client, web-based thin\nclient, and mobility applications on both Apple’s iOS and Android platforms.\n• UI wizards could potentially allow administrators to create any component of\ntheir infrastructure in mere minutes, designed in alignment with their growth\nfactors, technical requirements and business drivers.\n• Mean Time to Repair (MTTR) is projected to be significantly hastened, minimizing\nthe cost of outages.\n• Cost of ownership (COO) could potentially be reduced to minimal levels.\n• Return on Investment (ROI) for clients that migrate to the Titanium IaaS platform,\ncould potentially be achieved far faster than with traditional cloud-based\nsolutions. "
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://tbis.io/assets/TBIS-White-Paper-v2.7.1-46148c6d9985d1c3c9bf8440f7828c15ac50451d9c0c91bcd29c872908aac25b.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://tbis.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/TbisOfficial"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://tbis.io/twitter"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://tbis.io/#sale"
    sales_agreement = "https://tbis.io/#sale"

    [ico.common_info.token_distribution]
    total_supply = ""
    shares = []

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = ""
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "35000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-01-01"
    end_date = "2018-01-18"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = "35000000"

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "TBIS token"
symbol = "BAR"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""