app = []

[blockchain]
project_name = "PEER MOUNTAIN"
headline = "Decentralized ID protection, trust, and compliance ecosystem"
short_description = "The recent string of high-profile data breaches\nhighlights the dire shortcomings of current data\nprotection and storage methods. In summer 2017,\ncybercriminals breached Equifax’s secure servers and\nstole the sensitive personal information of 146 million\nAmericans1. That information - Social Security Numbers,\ncredit card details, dates of birth - could potentially be\nsold the dark web, putting the identities and financial\nsecurity of millions of hard-working people at risk. In\nresponse to this crisis, governments and regulators\nare passing legislation that requires businesses to\nEvery time a person transacts with\na bank, credit agency, government,\nor online retailer, that organization\ngenerates and stores a copy of that\nperson’s information following a\nnumber of rules and regulations\naccording to the specifics of the\ninteraction. The result is a world of\nenormous digital fortresses, each\nholding a duplicate of the identity\nof anyone who has ever been a\ncustomer. These fortresses - the\ncentralized servers that hold all\nour information - are rich, obvious\ntargets for cybercriminals. No\nmatter how many digital moats,\narchers, and catapults the\ndefenders build and deploy, the\nattackers will keep coming. And a\nsingle breach of any one of these\nfortresses can result in the loss of\nmillions of identities.\nDevelopers can harness blockchain\ntechnology to give individuals\nfurther ownership of their\npersonal information, and enable\nthem to store that information in\na distributed ledger, thus helping\neffectively mitigate the risk of\nidentity theft. To achieve this goal,\nmany organizations have launched\nblockchain-based platforms over\nthe past year; several of them have\nalso had successful coin offerings.\nPeer Mountain goes beyond\nproviding users with further\nownership and control over\ntheir cryptographically secure\nidentities, offering an end-to-end\napplication ecosystem designed\nto facilitate the commerce and\nexchange of digital and physical\nservices. It facilitates trust and\nthe secure sharing of information\nwith multiple independent\nparties across broad networks\nwhile preserving traceability and\ncompliance at every end of the\ntransference of data.\nPeer Mountain is the first\ndecentralized peer-to-peer trust\nmarketplace that connects selfsovereign\nidentity owners with\nregulatory-compliant service\nproviders, and opens a new\nparadigm for how and where\nindividuals and organizations\nconduct business."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://www.peermountain.com/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://www.peermountain.com/peermountain-whitepaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/PeerMountain"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/peermountain"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/PeerMountain/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/Peer-Mountain-489107644789749/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://steemit.com/@peermountain"
  tags = [
    "Main",
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "http://www.peermountain.com/token-sale/"
    sales_agreement = "https://www.peermountain.com/peermountain-whitepaper.pdf"

    [ico.common_info.token_distribution]
    total_supply = ""
    shares = []

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Pre-sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = "2018-02-12"
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = ""
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-02-13"
    end_date = "2018-03-02"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "PMT token"
symbol = "PMT"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""