app = []

[blockchain]
project_name = "IAGON"
headline = "Global Supercomputer powered by AI and Blockchain Technology"
short_description = "IAGON is a platform for harnessing the storage capacities and processing power of multiple computers\nover adecentralizedBlockchaingrid.IAGONutilizesenables tostorebigdata files andrepositories, as\nwell as smaller scales of files, and to carry out complex computational processes, such as those needed\nfor artificial intelligence and machine learning operations, within a fully secure and encrypted platform\nthat integrates blockchain, cryptographic and AI technologies in a user-friendly way.\nThe size of the cloud services market providing both storage capacities and computational processing\ncapabilities to companies and to corporates is estimated by 45 billion USD per annum and it steadily grows.\nThe market is dominated by four major players: AWS, Google Cloud, Microsoft and IBM, all utilize central and\nless trusted storage and computation facilities. Due to their oligopolistic dominance, the four providers of\ncloud services set high pricing levels. These providers are also capable of hampering any competition and\npreventing new market entrants from competing with them, due to the broad scale of their operations and\ntheir substantial investments in data centers, servers and storage facilities.\nInterestingly , however, the demand for computational processing capabilities and storage is expected to\ndramatically increase in the near future due to two major trends in the business and computing worlds: Big\nData and Artificial Intelligence (AI). Big Data is the collection , management and storage of vast amounts\nof information obtained from any internal of external sources (such as the company ’s IT systems , social\nnetworks, sensors and so on). The data management of companies promotes collection and storage of any\ndata related to its operations, clients and competitors, should a need to analyze any of these data ever present\nitself. The other major trend is the emergence of Artificial Intelligence methods that “learn” from data on\npast operations, find patterns and business rules and predict future behavior. AI-based processes consume\nrequire vast amounts of computations and consume significant processing power of CPU and GPU processes.\nThe demand for storage and for processing power is expected to exponentially increase with broadening\nthe introduction of AI applications in new areas and with the widespread adoption of data collection from\nmultiple channels (such as sensors, social networks, data providers, etc.) and later processing them.\nIAGON’s major aim is to revolutionize the cloud and web services market by offering a decentralized grid of\nstorage and processing. By joining the unused storage capacity in servers and personal computers and their\nprocessing power, we can create a super-computer and super data center that can compete with any of the\ncurrent cloud computing moguls.\nWe aim at providing companies and individuals storage and processing services at a fraction of the market\nprices and at a better security level by connecting data centers, business computers and personal users and\nutilizing their free storage capacities and their CPU and GPU processors during idle times. Doing so, IAGON\novercomes the entry barriers imposed by the high level of investments required to compete in this market.\nOur token-based economy is based on computer, server and data center owners who join the storage and\nprocessing power grids. In return for sharing the capabilities of their machine, they will be granted IAGON\ntokens that can be traded back to fiat money , while any party who wishes to utilize their capabilities will\npurchase IAGON tokens to distribute them to the parties that provide their services to the grid. The storage\nmechanism will be based on Blockchain encryption and delivery of encrypted file fragments to many\nstorage facilities. Contributors to the grid can publish their skills and free capacity and offer their service on\nthe basis of their experience , available resources and storage space and bidding on price . Advanced\nmachine learning and AI algorithms will assist in recommending prices to parties involved in this venture\nand classify- ing them according to their price levels and assuring continuity of services and access to all\nfiles.\n3\nAs more and more companies will recognize the benefits of IAGON’s platforms for storing files and processing\nthem, the demand will increase and so will be the demand for the token – the way customers pay grid\nparticipants.\nIAGON ’s token and platform are proven services with our Ethereum -based Blockchain beta version ,\nproving the concept of blockchain-based distributed computing and storage grid. IAGON plans to support\nalso the new and innovative Tangle technology that provides an alternative, rapid and lower cost solution\nfor oper- ating the Blockchain technology. Thus, IAGON will establish two blockchains – on Ethereum and\non Tangle – providing the complete flexibility and freedom of choice to our users and miners."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://www.iagon.com/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://www.iagon.com/pdf/Iagon%20Whitepaper%20v3.0.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "http://www.github.com/iagonorg"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/iagon-official"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2945888.0"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/IagonOfficial"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/Iagon_official"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/iagon/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/Iagon-228521574349591"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://www.iagon.com/"
    sales_agreement = "https://www.iagon.com/pdf/Iagon%20Whitepaper%20v3.0.pdf"

    [ico.common_info.token_distribution]
    total_supply = "1000000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "70"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Team"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Bounty & Advisors"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "development"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Pre-Sale"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "200000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-04-02"
    end_date = "2018-05-10"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Main Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "500000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-05-10"
    end_date = "2018-07-10"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "Iagon Token"
symbol = "IAG"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""