genesis_id = ""
system = "Etch"
dependencies = ["Ethereum"]
icon = "etch"

[token]
name = "etch token"
symbol = ""

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Evolution in payroll since the industrial revolution"

[crowdsales]
start_date = "2017-09-18T18:00:00"
end_date = "2017-10-18T18:00:00"
end_date_plan = "2017-10-18T18:00:00"
genesis_address = [""]
funding_terms = "https://app.etch.work/static/files/Etch_White_Paper.pdf"
funding_url = "https://app.etch.work/register_interest"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "etch.work"
url = "https://etch.work/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Etch Whitepaper"
url = "https://app.etch.work/static/files/Etch_White_Paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Etch GitHub"
url = "https://github.com/etch-work/reward-token"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Etch Blog"
url = "https://app.etch.work/blog/"
icon = "blog.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/etch_work"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Etch Telegram"
url = "https://t.me/etchwork"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/etchwork1/"
icon = "facebook.png"
tags = ["News"]
