
genesis_id = ""
system = "Blockstack"
dependencies = ["independent"]
icon = "blockstack"

[token]
name = "blockstack token"
symbol = ""

[consensus]
consensus_type = "POB"
consensus_name = "Proof-of-Burn"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "New Internet for Decentralized Apps"

[crowdsales]
start_date = "2017-11-13T00:00:00"
end_date = "2017-11-20T00:00:00"
end_date_plan = "2017-11-20T00:00:00"
genesis_address = [""]
funding_terms = "https://blockstack.com/"
funding_url = "https://blockstack.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "blockstack.org"
url = "https://blockstack.org/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Blockstack Whitepaper"
url = "https://blockstack.com/tokenpaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Blockstack Github"
url = "https://github.com/blockstack"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = "Blockstack Blog"
url = "https://blockstack.org/blog"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://www.twitter.com/blockstack"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Blockstack Slack"
url = "http://chat.blockstack.org/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UC3J2iHnyt2JtOvtGVf_jpHQ"
icon = "youtube.png"
tags = ["News"]
