app = []

[blockchain]
project_name = "JoyToken"
headline = "Smarter Games for Smarter Players"
short_description = "Joy Gaming’s technology offers a novel solution to connect small developers, software houses, large casinos and players. It creates a gaming ecosystem that both empowers players and helps developers and casinos reduce risk.\n\nThe lack of trust and transparency is a concern with the online gambling industry. Players tend to use reputable casinos instead of smaller sites, even if they offer more “interesting games”, because players naturally gravitate to casino brands that they trust. Joy Gaming’s technology is a transparent blockchain-based system, which will help improve trust in the gaming industry. Joy Gaming’s technology enables users to play in a transparent and code- governed environment. This allows players and developers to have confidence in the fairness of the games. Through an innovative RNG generator, players will have peace of mind that the games they play are fair and safe. Developers, casinos and businesses bene t from an ecosystem that provides liquidity sharing and fair compensation. By connecting developers and casinos, we aim for an optimal solution where all participants in Joy Gaming benefit"
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://joytoken.io/white-paper.html"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://joytoken.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/JoyPlatform/ico-contracts"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?action=profile;u=1343129"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://blog.joytoken.io/"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/JoyToken"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/joytoken"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/user/JoyToken/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/JoyToken.io/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://joytoken.io/"
    sales_agreement = "https://joytoken.io/#token-structure"

    [ico.common_info.token_distribution]
    total_supply = "700000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "50"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Rewards pool (VIP etc)"

      [[ico.common_info.token_distribution.shares]]
      percent = "23"
      description = "Sold on the platform"

      [[ico.common_info.token_distribution.shares]]
      percent = "12"
      description = "Founding team, vested for 24 months"

      [[ico.common_info.token_distribution.shares]]
      percent = "3"
      description = "Ambassadors, Fund Raising Fees"

      [[ico.common_info.token_distribution.shares]]
      percent = "2"
      description = "ICO bounties"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "350000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "46 340 000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-20"
    end_date = "2018-04-20"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "JoyToken"
symbol = "JoyToken"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""