app = []

[blockchain]
project_name = "Qlink"
headline = "World’s First Decentralized Mobile Network "
short_description = "Qlink\taims\tto\tbuild\tthe\tworld’s\tfirst\tdecentralized\tmobile\tnetwork,\twhich\twill\textend\t\nnetwork\tcoverage,\treduce\tthe\tcost\tof\ttelecom\tinfrastructures,\tand\treward\tusers\tfor\tsharing\t\nunused\tnetwork\tassets.\nThis\twhite\tpaper\texplains\tthe\ttechnical\tarchitecture\tof\tthe\tdecentralized\tmobile\tnetwork.\t\nBy\tutilizing\tblockchain\ttechnology,\tQlink\tapplies\tdigital\tidentities\tto\ttelecom\tassets,\t\nrepackages\tthose\tassets,\tand\trecords\tthe\tusage\tfootprint\tof\teach\tasset\tto\ta\tdistributed\t\nledger.\tAdditionally,\tQlink\taims\tto\tlaunch\tapplications\tdesigned\tto\tallow\tpeer-to-peer\t\nsharing\tof\tassets,\tincluding\tWi-Fi,\tmobile\tdata\taccess,\tand\tenterprise-to-peer\tSMS.\t\nWhile\timproving\tthe\tefficiency\tof\texisting\tnetworks,\tQlink\tplans\tto\tlaunch\tits\tcustom\tbase\t\nstations,\tincluding\ta\tmodel\tsuitable\tfor\tvehicle\tinstallation.\tBy\tutilizing\tthe\tidle\tresources\tof\t\nnetwork\tequipment,\tthese\tbase\tstations\twill\tallow\tusers\tto\tbecome\ta\tpart\tof\tthe\tcryptoeconomy,\nand\tat\tthe\tsame\ttime\tcreate\ta\tdecentralized\tsolution\tto\tcover\tnetwork\tblack\t\nspots.\t\nQlink\thas\tassembled\ta\tteam\tof\tseasoned\ttelecom\tand\tblockchain\tdevelopers,\talong\twith\t\nexperienced\tbusiness\tand\tmarketing\tprofessionals.\tAllen\tLi,\tfounder\tof\tQlink,\tpreviously\t\nfounded\tYouyou\tMobile\t(invested\tby\tAlibaba Capital),\twhich\tis\ta\tleading\tmobile\tdata\t\ndistributor\tin\tChina\tand\tSoutheast\tAsia,\tand\thas\tpartnered\twith\t40\ttelecom\toperators\t\naround\tthe\tworld\tto\tprovide\tmobile\tdata\tservices\tto\t6\tmillion\tcustomers.\tQlink’s\tR&D\tteam\t\nhas\tspent\tlast\tfour\tyears\tworking\tfor\tYouyou\tMobile,\tand\tdeveloped\tthe\tcompany's\tfirst\t\nvirtual\tSIM\tcard\tbank.\nThe\tQlink\tecosystem\tis\tsupported\tby\tthe\tQlink\ttoken\t(QLC).\tQLC\tis\tthe\tutility\ttoken\tused\tto\t\nsettle\tevery\ttransaction\ton\tthe\tQlink\tnetwork,\tfunctioning\tas\ta\tcryptocurrency\tto\tmeasure\t\nthe value\tof\tassets\tand\tcontent.\nQlink\twill\tbegin\tissuing\tQIink\ttokens\t(QLC)\tin\tNovember\t2017.\tThrough\tthe\tQLC\ttoken\tsale,\t\nQlink\taims\tto\traise\tthe\tequivalent\tof\tUSD$15,000,000\tin\tETH\tand\tNEO.\tThe\ttotal\tsupply\tof\t\nQLC\tis\tsix\thundred\tmillion\ttokens\t(600,000,000)."
state = "2"
asset_type = ""
dependency = "independent"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://qlink.mobi/qlink2/res/WhitePaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://qlink.mobi/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/QlinkMobi"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/joinchat/F2sRmw4x_mzgSHKhyH5AFQ"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/Qlink/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2393643.0"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/Qlink-Mobi-1997869573788683"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://qlink.mobi"
    sales_agreement = "https://qlink.mobi/qlink2/res/TokenSales.pdf"

    [ico.common_info.token_distribution]
    total_supply = "600000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "40"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "- Qlink\tdevelopment\tteam\tand\tadvisors\t(Tokens\tto\tteam\tand\tadvisors\tare\t released\tover\ta\t3-year\tvesting\tperiod)"

      [[ico.common_info.token_distribution.shares]]
      percent = "40"
      description = "Held\tas\ta\tprovision\tfor\tpartnerships,\tmarketing,\tstrategic\tinitiatives,\tand\tfuture\t QLC\texpenses"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Launching\tthe\tdecentralized\ttelecom\tservice\tindustry\tprotocol\tand\tconnecting\twith\t industry\texperts\t"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Recruiting\ttalent,\texpanding\tthe\tcurrent\tdevelopment\tteam\tand\tlaunching\t applications"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "Project\tmarketing\tto\tattract\tboth\tdata\tsharing\tparties\tand\tdata\tusing\tparties"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Paying\tteam\tmembers\tsalary\tand\tother\tbusiness\toperating\texpenses"

    [[ico.common_info.use_of_proceeds]]
    percent = "35"
    description = "Continuous\tdevelopment\tand\tproduction\tof\tQlink\thardware"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Rewarding\ttalented\tengineers\tand\tconsultants\tfor\toutstanding\tcontributions\tto\tQlink\t platform\tto\tdrive\tgrowth\tand\tsustainability"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Pre-purchasing\tdata\tto\trun\tthe\tproject\tduring\tthe\ttrial\tstage"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Crowdsale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "224000000"
    sold_tokens = "224000000"
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "19300000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2017-11-28"
    end_date = "2017-12-22"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = "19270800"

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "Qlink Token"
symbol = "QLC"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""