genesis_id = ""
system = "Equibit"
dependencies = ["Waves"]
icon = "equibit"

[token]
name = "equibit token"
symbol = "EQB"

[consensus]
consensus_type = "PoS"
consensus_name = "Proof-of-State"

[descriptions]
state = "Pre-public"
system_type = "cryptoasset"
headline = "Peer-to-Peer Electronic Equity System"

[crowdsales]
start_date = "2017-08-15T12:00:00"
end_date = "2017-09-15T12:00:00"
end_date_plan = "2017-09-15T12:00:00"
genesis_address = [""]
funding_terms = "https://equiplatform.io/Equi_Whitepaper.pdf"
funding_url = "https://equiplatform.io"
tokens_sold = 229301
tokens_issued = ""
btc_raised = ""
cap_limit = ["usd = 1000000"]
raised = [""]

[[links]]
type = "website"
name = "equibitgroup.com"
url = "https://equibitgroup.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Equibit Whitepaper"
url = "https://equiplatform.io/Equi_Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Equibit GitHub"
url = "https://github.com/Equibit"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/equibit"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Equibit Slack"
url = "https://equibit.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Equibit"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCBWEY89pt-DpPYyPedqGWEg"
icon = "youtube.png"
tags = ["News"]
