app = []

[blockchain]
project_name = "MedCredits"
headline = "First Ethereum blockchain powered telemedicine platform"
short_description = "To date, we do not know of a medical application that uses a decentralized platform for health services. We believe that dermatology is the most readily accessible medical specialty to establish MedCredits in blockchain-based telemedicine. Our teledermatology application ‘Hippocrates’ is used to showcase the capabilities of the MedCredits healthcare ecosystem. Beyond dermatology, we envision the addition of many other medical specialties such as psychiatry, internal medicine and radiology to the MedCredits platform. The MedCredits telemedicine platform is powered by a decentralized token curated registry (TCR) of physicians — the first of its kind. This allows any 3rd party blockchain healthcare application to access a registry of physicians in any specialty. Finally, all data generated in the MedCredits ecosystem is under the control of the patients. Over time, this data can be aggregated into an electronic medical record system built from the ground up based on clinical applications. In its entirety, the MedCredits ecosystem has the potential to be a decentralized physician registry, global electronic health records system and marketplace giving patients instantaneous access to medical care anywhere in the world — that is, a truly free global healthcare market."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://medcredits.io/docs/MedCreditsWhitePaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://medcredits.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2101348.0"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/medcredits"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/medcredits"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/MedCredits"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://medcredits.io/whitelist"
    sales_agreement = "https://medcredits.io/tokensale"

    [ico.common_info.token_distribution]
    total_supply = "100000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "70"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "Team"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Marketing"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Pre-Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "35000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-04-08"
    end_date = "2018-05-08"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "MEDX token"
symbol = "MEDX"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""