genesis_id = ""
system = "Prizm"
dependencies = ["independent"]
icon = "prizm"

[token]
name = "prizm token"
symbol = "PZM"

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptocurrency"
headline = "Decentralized and self-regulating digital currency"

[aliases]
coinmarketcap = "PRIZM"

[[links]]
type = "website"
name = "prizm.club"
url = "http://prizm.club/en/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Prizm Whitepaper"
url = "https://docviewer.yandex.ru/view/122721294/?*=4ELPgTqF6aWcOwZzli5dz9%2B%2FJnV7InVybCI6InlhLWRpc2stcHVibGljOi8vMEFSQlY1cFBjZkh3RE9lYUlRQkdjUFQvOHlvSWsya3hueDRkYmVQdW05Yz0iLCJ0aXRsZSI6IlBSSVpNV2hpdGVwYXBlcl9FbmdsaXNoLnBkZiIsInVpZCI6IjEyMjcyMTI5NCIsInl1IjoiODA4MDc3NTUwMTUwNDcyOTE4MiIsIm5vaWZyYW1lIjpmYWxzZSwidHMiOjE1MDgwODIzNDg2NjR9"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Prizm GitHub"
url = "https://github.com/prizmspace/PrizmCore"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/PRIZM_RU"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Prizm Telegram"
url = "https://t.me/PRIZMclub"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/prizmcoin%20"
icon = "facebook.png"
tags = ["News"]
