
genesis_id = ""
system = "KredX"
dependencies = ["Ethereum"]
icon = "kredx"

[token]
name = "kredits token"
symbol = "KRT"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "A Multi-Blockchain Cryptocurrency Platform"

[crowdsales]
start_date = "2017-10-04T00:00:00"
end_date = "2018-03-01T23:59:00"
end_date_plan = "2018-03-01T23:59:00"
genesis_address = [""]
funding_terms = "https://bitcointalk.org/index.php?topic=2235814.msg22545568#msg22545568"
funding_url = "https://kredx.io/#buytokens"
tokens_sold = "10001000"
tokens_issued = "440000000"
btc_raised = ""
cap_limit = ["usd = 43000000"]
raised = [""]

[specs]
supply = 440000000

[[links]]
type = "website"
name = "kredx.io"
url = "http://kredx.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "KredX Whitepaper"
url = "http://kredx.io/kredx.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "KredX GitHub"
url = "https://github.com/kredX/kredx-platform"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/KredXApp"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/KredX/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/kredxapp/"
icon = "facebook.png"
tags = ["News"]