genesis_id = ""
system = "Forty Seven Bank"
dependencies = ["Ethereum"]
icon = "fortysevenbank"

[token]
name = "Forty Seven Token"
symbol = "FSBL"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Bank uniting fiat and crypto communities"

[crowdsales]
start_date = "2017-11-13T03:00:00"
end_date = "2017-12-11T23:59:00"
end_date_plan = "2017-12-11T23:59:00"
genesis_address = [""]
funding_terms = "https://drive.google.com/file/d/0BzvESRkgX-uDOG01a253SUdYdkU/view"
funding_url = "https://www.fortyseven.io/"
tokens_sold = 0
tokens_issued = 0
btc_raised = 0
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "fortyseven.io"
url = "https://www.fortyseven.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Forty Seven Bank Whitepaper"
url = "https://drive.google.com/open?id=0BzvESRkgX-uDeHc1QjRzbHRBelU"
tags = ["Main", "Science"]

[[links]]
type = "custom"
name = "Forty Seven Bank Bitbucket"
url = "https://bitbucket.org/fortysevenbank/fsbt-smart-contract/src"
icon = "bitbucket.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Forty Seven Bank Blog"
url = "https://medium.com/@FortySeven47"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2225492"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/47foundation"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Forty Seven Bank Telegram"
url = "https://t.me/thefortyseven"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/FortySevenBank/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/FortySevenBank/"
icon = "facebook.png"
tags = ["News"]
