app = []

[blockchain]
project_name = "Emmares"
headline = "Solution for email marketing problems"
short_description = "EMMARES is connecting high-quality email content with interested\nrecipients. Encouraging better quality content, lower frequency, and fair\ncontent evaluation, EMMARES brings new value, an expanded audience\nfor email marketers and less spam with only desired content for\nrecipients.\nEMMARES - Email Marketing Rewarding System is an evaluation system\nthat highly benefits email marketers (senders) as well as email recipients\n(all email users)."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://emmares.io/whitepaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://emmares.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/emmares_io"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/emmares.io/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = ""

    [ico.common_info.token_distribution]
    total_supply = ""

      [[ico.common_info.token_distribution.shares]]
      percent = "51"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "23"
      description = "new account opening incentives"

      [[ico.common_info.token_distribution.shares]]
      percent = "17"
      description = "Founders and team"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "future strategic team members"

      [[ico.common_info.token_distribution.shares]]
      percent = "1"
      description = "Bounty"

      [[ico.common_info.token_distribution.shares]]
      percent = "3"
      description = "Pre-tokensale contributors"

    [[ico.common_info.use_of_proceeds]]
    percent = "30"
    description = "Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "25"
    description = "Technical deployment"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Market promotion"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "Operations"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Legal"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "250000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "22500000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-05-01"
    end_date = "2018-05-31"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "EMA token"
symbol = "EMA"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""