genesis_id = ""
system = "Solar Bankers"
dependencies = ["Skycoin"]
icon = "solarbankers"

[token]
name = "sun coin"
symbol = "SUN"

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized Electricity Network based on Solar Energy"

[specs]
supply = 300000000

[[links]]
type = "website"
name = "solarbankers.com"
url = "https://solarbankers.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Solar Bankers Whitepaper"
url = "http://solarbankers.com/wp-content/uploads/2017/08/Solarbankers_whitepaper_Vers2BUpd.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Solar Bankers GitHub"
url = "https://github.com/SolarBankers/SunCoin"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Solar Bankers Blog"
url = "https://solarbankers.com/blog/"
icon = "blog.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2064964.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/SolarBankers_"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Solar Bankers Telegram"
url = "https://t.me/solarbankersICO"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Solar Bankers Slack"
url = "https://solarbankers.slack.com/join/signup"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/solarbankerssingapore/"
icon = "facebook.png"
tags = ["News"]
