app = []

[blockchain]
project_name = "WorldWiFi"
headline = "DECENTRALIZED FREE WI-FI NETWORK POWERED BY BLOCKCHAIN"
short_description = "The World Wi-Fi is a free decentralized Wi-Fi network based on\nprivate routers, most of which are residential. Every router\nowner may share excess broadband capacity and allow internet\nguest users to connect to free internet, and so earn\ncryptocurrency. As a result, internet users view short\nadvertisement while connecting and then use internet for free,\nadvertisers pay directly to the router owners for each ad\nimpression on their networks. Win-Win for everyone. The World\nWi-Fi is a global project being built by the community. "
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://en.worldwifi.io/?utm_source=cyberfund&utm_medium=cyberfund&utm_campaign=cyberfund"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://s3.eu-west-2.amazonaws.com/world-wifi/whitepaper/whitepaper_en.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/World-WiFi"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@WorldWifi_ICO"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2518622"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/WorldWifi_ICO"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/world_wifi"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/worldwifi/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "slack"
  name = "Slack"
  url = "https://world-wifi.slack.com/join/shared_invite/enQtMjkzNDQ0MzMxMTI2LTVkMzQ5ZTdiNDE3YTc4ZjUxNGY0Mzg2NjczYTE2M2JmOTAxMzY4NmM3YTZkMjczZGQ3YjNjOTI3MTBjOGQ3OGM"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/worldwifi.io"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "http://en.worldwifi.io?utm_source=cyberfund&utm_medium=cyberfund&utm_campaign=cyberfund"
    sales_agreement = "http://en.worldwifi.io?utm_source=cyberfund&utm_medium=cyberfund&utm_campaign=cyberfund"

    [ico.common_info.token_distribution]
    total_supply = "600000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "43"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Team"

      [[ico.common_info.token_distribution.shares]]
      percent = "3"
      description = "Advisers"

      [[ico.common_info.token_distribution.shares]]
      percent = "2"
      description = "Bounty"

      [[ico.common_info.token_distribution.shares]]
      percent = "7"
      description = "Founders (frozen for 1 year)"

      [[ico.common_info.token_distribution.shares]]
      percent = "40"
      description = "Future development  (frozen for 1-5 years)"

    [[ico.common_info.use_of_proceeds]]
    percent = "24.4"
    description = "R&D"

    [[ico.common_info.use_of_proceeds]]
    percent = "39.5"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "25.5"
    description = "EXPENSES FOR AGENT NETWORK "

    [[ico.common_info.use_of_proceeds]]
    percent = "6.4"
    description = "EXPENSES FOR BUILDING B2B NETWORK"

    [[ico.common_info.use_of_proceeds]]
    percent = "2.4"
    description = "EXPENSESES ON SOFTWARE AND HARDWARE"

    [[ico.common_info.use_of_proceeds]]
    percent = "1.3"
    description = "Payroll"

    [[ico.common_info.use_of_proceeds]]
    percent = "0.5"
    description = "ADMINISTRATIVE EXPENSES"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "258000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "25000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-11-28"
    end_date = "2018-04-18"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = "5686000"

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "15"
      condition = "PRE-SALE"

[[token]]
name = "WETOKEN"
symbol = "WT"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""