app = []

[blockchain]
project_name = "METRUMCOIN"
headline = "METRUMCOIN a new way to do Real Estate"
short_description = "The project \"METRUMCOIN™\" has been prepared for two years by an\ninternational group of real estate and IT experts. Its goal is to transform\nthe obsolete real estate market into an effective digital market based on\nBlockchain and other IT technologies. The idea of the project belongs to\nMr. Telman Abbasov, a specialist with more than 25 years of real estate\nexperience, the President of the World Council of Developers and\nInvestors FIABCI 2015-2017.\nThe project was presented to a wide range of professionals from the real\nestate industry at the annual international conference \"MIPIM-2017\" in\nCannes. The second report took place within the framework of\n\"BlokTex-2017\" conference in Kuala Lumpur, dedicated to advanced\ndevelopments in the field of Blockchain technologies. For the first time an\nexpert in the real estate market, having nothing in common with IT\nindustry, has presented the project at the international level for\nprofessionals in IT sphere and Blockchain technology. The project aroused\ngreat interest in the RE and IT communities, confirming its importance for\nthe future development of the international real estate market.\nIn March 2017 in the United Kingdom and the United States, we have\npatented the author's method for attracting investments in real estate\nobjects with the help of cryptoinstruments and Blockchain technology.\nToday, the international real estate market requires a deep transformation\nand the introduction of innovative information technologies.\nMETRUMCOIN © - is a project that can change the fundamentals of the\nglobal real estate market. Our mission is to make the global real estate\nmarket accessible to everyone in just a few clicks.\nWe create a single digital space that ensures the elimination of all\ngeographical, bureaucratic and transactional barriers for all market\nparticipants.\nUsing its own cryptocurrency inside the METRUMCOIN ecosystem will\nallow to finally overcome all international barriers. "
state = "0"
asset_type = ""
dependency = "independent"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://www.metrumcoin.com/pdf/white_paper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://www.metrumcoin.com/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/Metrumcoin"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/user/Metrumcoin/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/metrumcoin_chat"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/metrumcoin/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/metrumcoin"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@Metrumcoin"
  tags = [
    "Main",
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://my.metrumcoin.com/login"
    sales_agreement = "https://www.metrumcoin.com/pdf/white_paper.pdf"

    [ico.common_info.token_distribution]
    total_supply = "3800000"

      [[ico.common_info.token_distribution.shares]]
      percent = "80"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Pre-sale"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Development team"

    [[ico.common_info.use_of_proceeds]]
    percent = "50"
    description = "infrastructure development"

    [[ico.common_info.use_of_proceeds]]
    percent = "25"
    description = "platform development"

    [[ico.common_info.use_of_proceeds]]
    percent = "16"
    description = " development of complementary services for the circulation of the created cryptocurrency "

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "formation of the company's reserve fund"

    [[ico.common_info.use_of_proceeds]]
    percent = "4"
    description = "marketing, payment for experts and consultants services "

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = ""
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2017-11-07"
    end_date = "2017-12-10"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "20%"
      condition = "pre sale"

      [[ico.phases.prices.bonuses]]
      amount = "15%"
      condition = "1 stage of crowdsale – 300 000 tokens"

      [[ico.phases.prices.bonuses]]
      amount = "10%"
      condition = "2 stage of crowdsale - 200,000 tokens"

[[token]]
name = "METRUMS tokens"
symbol = "METRUMS"
token_purpose = "Both"
token_type = "Core token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""