app = []

[blockchain]
project_name = "BoatPilot"
headline = "BoatPilot is marine Google Maps and TripAdvisor in one software"
short_description = "BoatPilot is the first, free integrated marine navigation service with augmented\nreality capabilities for private and commercial yachting markets.\nPRECISE NAVIGATION INFORMATION\nBoatPilot allows yachtsmen to easily track marine routes and access the most\nrelevant information on coastal objects; including charts, navigation signs, reference\ndata, maritime laws and regulations in a specific region. The cloud-based\ninfrastructure allows BoatPilot users to add and update the existing database and\ngenerate relevant content, which is checked and supported by other members in the\nyachting community. This structure leads to creating the most complete and precise\nnavigation information database in the world. In addition to general information\nabout coastal objects and services, BoatPilot also includes professional comments,\nphotos, and sketches.\nAUGMENTED REALITY FUNCTION\nBoatPilot supports an augmented reality (AR) function, which allows the skipper to\nuse AR glasses to see all necessary data incorporated into actual surroundings, and\navoid distractions by the traditional dash. This feature is especially useful during poor\nvisibility conditions, or at night.\nFREE TO USERS\nBoatPilot is completely free to all end users. Unlike most existing marine navigation\nsystems on the market, our product is uniquely developed for private yachtsmen and\nsmall yachting businesses. It is not an updated, or reworked, version of military or\nlarge commercial navigation systems.\nBoatPilot is more than just a marine navigation tool, although navigation is definitely\nits main feature. BoatPilot is a marketplace that provides businesses of any size –\nfrom large brands to small seaside restaurants – effective and convenient access to\nthe international yachting market, which is estimated to reach $74.7 billion\nby 20221\n. Best of all, BoatPilot advertising works even when the user has no internet\naccess.\nWE PLAN TO:\n•become the world’s leading marine navigation solution for mobile devices\n(phones and tablets), and built-in navigation systems produced by equipment\nmanufacturers;\n•provide the yachting industry a convenient and fully functional platform to\nadvertise products and services in a market estimated to be worth over $200 billion\nannually.\nBoatPilot is not an abstract concept. It is an existing and functioning product. By\nlate 2017, the service was released on Android.\nBoatPilot is essentially Google Maps and TripAdvisor in one\nprogram, with no other product like it in the world.\n(phones and tablets), and built-in navigation systems produced by equipment\nmanufacturers;\nadvertise products and services in a market estimated to be worth over $70 billion\nannually."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://www.boatpilot.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://www.boatpilot.io/docs/BoatPilot_White_Paper_EN.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/BoatPilotNAVI/TGE"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@boatpilot/"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/boatpilot_io"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/boatpilot"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/BoatPilot/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/boatpilot.io/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://www.boatpilot.io/"
    sales_agreement = "https://www.boatpilot.io/docs/BoatPilot_Token_Policy_EN.pdf"

    [ico.common_info.token_distribution]
    total_supply = "229737610"

      [[ico.common_info.token_distribution.shares]]
      percent = "61.25"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "Team"

      [[ico.common_info.token_distribution.shares]]
      percent = "12.25"
      description = "Bonuses"

      [[ico.common_info.token_distribution.shares]]
      percent = "3.5"
      description = "Advisers"

      [[ico.common_info.token_distribution.shares]]
      percent = "1.5"
      description = "Project`s ecosystem"

      [[ico.common_info.token_distribution.shares]]
      percent = "1.5"
      description = "Bounty, PR and Referral"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "140714286"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "9850000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-01-09"
    end_date = "2018-04-30"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = "1433100"

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "NAVI Token"
symbol = "NAVI"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""