app = []

[blockchain]
project_name = "LetitPlay"
headline = "Audio layer of the internet. "
short_description = "LetItPlay prepares the Internet for its audio future by creating a decentralized ecosystem with attention economy\nwhich allows any news portal, blogger of community to easily create, distribute and monetize audio versions of\ntheir content.\nIn audio future, every website, news portal or blog that is interesting to the audience will acquire its own audio\nversion and will be able to deliver its content to the audience via various audio interfaces. With the help of audio,\nwe want to give modern people an opportunity to consume information without being glued to a screen. Almost all\nof us have several hours during the day when our visual channel is occupied, but the mind is open for consuming\ninformation, say in your car, in public transport, in the gym or while doing household chores, before going to bed or\nafter waking up. This time represents the best opportunity to consume content in audio format.\nIt would be nice to listen to news from your favorite sites or blogs or your friends’ comments about the world\nevents while driving. Indeed, a bulk of internet content can be delivered as audio without losing anything, for\nexample, news, articles, analytics, blogs, etc.\n Yet, even content as popular as news is far more likely to be found in text or video form, and audio content on the\nInternet remains a second-class citizen. The main reason is that production of audio content brings no direct profits\nto the Content Providers, and requires additional investment into its production.\nLetItPlay provides a solution to this problem. LetitPlay is backed by EOS blockchain technology. Decentralized nature\nof this solution allows us to implement a genuinely transparent and fair attention economy designed to reward\ncontent creators for consumer attention to content, including listens, likes, comments and reposts. Similarly to what\nSteem has done for text content, LetItPlay will do for audio.\nThe attention economy will make audio production profitable for Content Providers. And the ecosystem will grant\nContent Providers access to new ways of content distribution and chance to reach a new audience.\nThe LetItPlay ecosystem will connect not only Content Providers and general Consumers, but also Service Providers\ni.e., those who put in their effort to produce audio content, including voiceover artists, audio recording studios,\ntranslators, editors, and so on.\nThis means that any news portal or individual blogger can afford to create audio content and do it at minimal cost.\nIt is as easy as choosing a studio and voiceover artist.\nThe LetItPlay ecosystem is designed to be as open as possible. We will actively bring in new Distributors and\nsupport every effort to create new applications including but not limited to podcasts, audiobooks, audio guides,\netc. In future, the LetItPlay attention economy may be implemented in many other areas such as music, videos,\ngames, and even software.\nFinally, the Advertiser in the ecosystem will play by the rules of attention economy where Consumer attention is\nevaluated and should compensated directly by Advertiser.\nInternal digital currency Play will serve as a utility token that will be used to reward Content Providers for the\nattention of the Consumers, as well as to facilitate transactions between all ecosystem participants."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://letitplay.io/wp/WP_en.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://letitplay.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/LetItPlay"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/letitplay"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=3140643.0"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/letitplay_io"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/letitplay_io"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/user/letitplay_io/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/letitplayio/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://letitplay.io/tokensale"
    sales_agreement = "https://letitplay.io/wp/WP_en.pdf"

    [ico.common_info.token_distribution]
    total_supply = "1000000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "60"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "15"
      description = "Ecosystem fund"

      [[ico.common_info.token_distribution.shares]]
      percent = "15"
      description = "Founders"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Team"

      [[ico.common_info.token_distribution.shares]]
      percent = "3"
      description = "Advisors"

      [[ico.common_info.token_distribution.shares]]
      percent = "2"
      description = "Bounty"

    [[ico.common_info.use_of_proceeds]]
    percent = "36"
    description = "Product development"

    [[ico.common_info.use_of_proceeds]]
    percent = "35"
    description = "Community development"

    [[ico.common_info.use_of_proceeds]]
    percent = "12"
    description = "Reserve fund"

    [[ico.common_info.use_of_proceeds]]
    percent = "7"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "7"
    description = "Administrative"

    [[ico.common_info.use_of_proceeds]]
    percent = "3"
    description = "Legal"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "593000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-04-02"
    end_date = "2018-06-01"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "20%"
      condition = "up to 15 APR 2018"

      [[ico.phases.prices.bonuses]]
      amount = "10%"
      condition = "up to 29 APR 2018"

      [[ico.phases.prices.bonuses]]
      amount = "5%"
      condition = "up to 13 MAY 2018"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Pre-Sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "6500000 "
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2017-12-25"
    end_date = "2018-02-28"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = "263"

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "30%"
      condition = "Pre-ICO"

[[token]]
name = "PLAY Token"
symbol = "PLAY"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""