app = []

[blockchain]
project_name = "MYDFS"
headline = "Blockchain-powered daily fantasy sports platform"
short_description = "MyDFS is a blockchain-based daily\nfantasy sports solution that connects\nsports fans around the world with a\ntransparent, easy-to-use, investorfriendly\nplatform.\nMyDFS doesn’t try to compete with industry leaders, but redefines the\nindustry itself.\n­ MyDFS adds maximum transparency by using the blockchain and smart contracts for every\npart of the platform, from player trades to receiving your winnings.\n­ MyDFS overcomes legal issues by using ERC-20 Ethereum-based cryptocurrency tokens.\nThese replace real money in the game, meaning people from all over the world can play without\nworrying about the game’s legality.\n­ MyDFS makes the gaming process as simple and straightforward as possible, attracting\nmore sports fans to fantasy."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"

  [[blockchain.milestone]]
  number = 1.0
  name = "uTrener DFS launched in Russia"
  start_date = "JANUARY 16, 2016"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 2.0
  name = "Kontinental Hockey League app launched"
  start_date = "FEBRUARY 20, 2016"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 3.0
  name = "uTrener app got a UK Gambling license"
  start_date = "NOVEMBER 7, 2017"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 4.0
  name = "MyDFS development started"
  start_date = "NOVEMBER 20, 2017"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 5.0
  name = "MyDFS investor functionality is ready"
  start_date = "DECEMBER 29, 2017"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 6.0
  name = "MyDFS investor wallet is publicly accessible"
  start_date = "FEBRUARY 8 2018 "
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 7.0
  name = "Pre-ICO sale starts"
  start_date = "MARCH 19 - APRIL 2, 2018 "
  current_status = "In work"

  [[blockchain.milestone]]
  number = 8.0
  name = "MyDFS basic gaming functionality is ready"
  start_date = "MARCH 25, 2018 "
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 9.0
  name = "ICO starts"
  start_date = "APRIL 9, 2018"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 10.0
  name = "ICO finishes"
  start_date = "MAY 7, 2018 "
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 11.0
  name = "Intensive public marketing & PR campaign starts"
  start_date = "MAY 15, 2018"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 12.0
  name = "MyDFS app is fully ready"
  start_date = "MAY 15, 2018 "
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 13.0
  name = "The app is fully ready for largest soccer event"
  start_date = "JUNE 1, 2018"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 14.0
  name = "MyDFS supports all teams playing at the biggest soccer event of 2018"
  start_date = "JUNE 14, 2018"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 15.0
  name = "NFL is included to MyDFS "
  start_date = "AUGUST 10, 2018"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 16.0
  name = "NBA is added to MyDFS"
  start_date = "SEPTEMBER 20, 2018"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 17.0
  name = "MyDFS card is issued"
  start_date = "NOVEMBER 19, 2018"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 18.0
  name = "MyDFS app is launched on Apple TV"
  start_date = "DECEMBER 3, 2018"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 19.0
  name = "eSports is added to MyDFS platform"
  start_date = "JANUARY 21, 2019"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 20.0
  name = "MyDFS Event in Las Vegas, USA"
  start_date = "MARCH 16, 2019"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 21.0
  name = "Formula 1 is added to the platform"
  start_date = "APRIL 10, 2019"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 22.0
  name = "MyDFS supports MLB"
  start_date = "JUNE 9, 2019"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 23.0
  name = "MyDFS Fantasy Basketball Championship"
  start_date = "AUGUST 17, 2019"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 24.0
  name = "World Fantasy Football Championship Weekend"
  start_date = "NOVEMBER 8, 2019"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 25.0
  name = "MyDFS starts to prepare for Fantasy Olympic Games"
  start_date = "DECEMBER 16, 2019"
  current_status = "Planned"

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://mydfs.net/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://mydfs.net/whitepaper"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/mydfs/blockchain"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/mydfs"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/mydfs"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/@mydfs_net"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/mydfs.page"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://mydfs.net/?utm_source=cyber.fund"
    sales_agreement = "https://mydfs.net/site/terms-of-use"

    [ico.common_info.token_distribution]
    total_supply = "125000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "40"
      description = "PURCHASED TOKENS"

      [[ico.common_info.token_distribution.shares]]
      percent = "37"
      description = "GROWTH TOKENS"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "TEAM TOKENS"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "ADVISORS AND EARLY CONTRIBUTORS TOKENS"

      [[ico.common_info.token_distribution.shares]]
      percent = "3"
      description = "BOUNTY TOKENS"

    [[ico.common_info.use_of_proceeds]]
    percent = "55"
    description = "Marketing & PR"

    [[ico.common_info.use_of_proceeds]]
    percent = "18"
    description = "Business Operations"

    [[ico.common_info.use_of_proceeds]]
    percent = "13"
    description = "Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "8"
    description = "Legal and licences"

    [[ico.common_info.use_of_proceeds]]
    percent = "6"
    description = "Other costs “Rainy day” fund to be used in case of unanticipated expenses"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "ICO"
  phase_status = "Active"

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "50000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "40000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-19"
    end_date = "2018-05-07"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "10%"
      condition = "for $ 50k+"

      [[ico.phases.prices.bonuses]]
      amount = "15%"
      condition = "for $ 100k+"

      [[ico.phases.prices.bonuses]]
      amount = "25%"
      condition = "for $ 500k+"

    [[ico.phases.contract]]
    address = "0xCdF35C3FE4cCFaCb3B1bBEDFe71CA3A5ff6f2dB1"

[[token]]
name = "MyDFS token"
symbol = "MyDFS"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""