genesis_id = ""
system = "Qointum"
dependencies = ["independent"]
icon = "qointum"

[token]
name = "qointum token"
symbol = ""

[consensus]
consensus_type = ""
consensus_name = ""

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Secure Trustless Smart Money powering Web 3.0"

[crowdsales]
start_date = "2017-07-02T00:00:00"
end_date = "2017-08-14T00:00:00"
end_date_plan = "2017-08-14T00:00:00"
genesis_address = [""]
funding_terms = "https://wiki.qointum.com/legal/crowdfunding/"
funding_url = "https://qointum.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "qointum.com"
url = "https://qointum.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Qointum Whitepaper"
url = "https://wiki.qointum.com/design/dev/"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Qointum GitHub"
url = "https://github.com/Qointum"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Qointum Blog"
url = "https://blog.qointum.com/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/Qointum"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Qointum/"
icon = "reddit.png"
tags = ["News"]
