app = []

[blockchain]
project_name = "XYO Network"
headline = "The decentralized, trustless Smart Contract location oracle."
short_description = "With the growing presence of connected, location-reliant technologies, our privacy\nand safety rely heavily on the accuracy and validity of location information. Various\nattempts have been made to eliminate the need for centralized entities controlling the\nflow of location data, but every attempt has relied on the integrity of the devices collecting\nthis data in the physical world. We propose a trustless, cryptographic location\nnetwork using a novel formulation reliant on a chain of zero-knowledge proofs to establish\na high degree of data certainty on location information. The XYO Network\n(XY Oracle Network) is an abstraction that enables layered, location verification\nacross many device classes and protocols. At its core sits a set of novel cryptographic\nmechanisms known as Proof of Origin & Bound Witness that tie together the\npower of blockchain technology and real world data collection into a system with direct\napplications today."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://xyo.network/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://docs.xyo.network/XYO-White-Paper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/XYOracleNetwork"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@XYOracleNetwork"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/XYOracleNetwork"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/xyonetwork"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/xyonetwork"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://xyo.network/"
    sales_agreement = "https://docs.xyo.network/XYO-White-Paper.pdf"

    [ico.common_info.token_distribution]
    total_supply = ""

      [[ico.common_info.token_distribution.shares]]
      percent = "40"
      description = "Marketing"

      [[ico.common_info.token_distribution.shares]]
      percent = "35"
      description = "R&D"

      [[ico.common_info.token_distribution.shares]]
      percent = "15"
      description = "Operations"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Overhead"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Supporting important blockchain projects"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Active"

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "409617234"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "48000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-20"
    end_date = "2018-05-20"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

    [[ico.phases.contract]]
    address = "0x55296f69f40ea6d20e478533c15a6b08b654e758"

[[token]]
name = "XYO Token"
symbol = "XYO"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""