app = []

[blockchain]
project_name = "Bubbletone"
headline = "Bubbletone Blockchain in Telecom"
short_description = "“Blockchain in Telecom” ecosystem provides direct interaction between end-users, mobile\noperators and service-providers via smart contracts.\nIt eliminates hundreds of intermediators, dramatically reduces costs of mobile services (up to 10\ntimes while going abroad), and saves years and millions of $$ on implementation of the oldfashioned\nand ineffective roaming technology.\nHow it works: any mobile carrier could publish its own prepaid tariff plans (“Offers”) as smart\ncontracts. These Offers are visible to all other operators and their subscribers. By selecting an Offer, a\nnew “Request” smart contract is created, with the Digital Identity of a subscriber and Payment\ntransaction.\nAs a result, the Offer issuer identifies the user and receives money, and starts servicing the\nsubscriber directly, with local price and high quality.\nThe same business process is available for any non-telecom service provider (like music, TV or cloud\nservices) who is interested in distributing its own Offers among multimillion customer bases of\nmobile operators.\nThe Blockchain ecosystem consists of a limited number of high performance servers (“Nodes”),\nwhich belong to the crypto community. It means that any crypto holder could buy a license to\nmanage the Node, and start earning by processing the smart contracts.\n8\nThe more operators and service providers are connected to the “Blockchain in Telecom” ecosystem,\nthe more “smart contracts” are to be processed, the more revenue and value of each Node. Our\napproximated projection is 10x annual growth of Smart Contracts in the ecosystem.\nHigh ROI is combined with Low Risks, because we’re a proven team with 20 years’ experience in\ntelecom industry. During this period, multiple telecom and software development businesses have\nbeen created:\na. Mobile Virtual Network Operator under brand “Allo Incognito” (240K Premium Subscribers)\nb. “Bubbletone” messenger with 100+ useful features. It’s customized for the needs of mobile\noperators to provide additional revenue streams on voice calls and SMS from the app and other\ntelecom services. Beta version is already available at App Store and Google Play.\nc. Global Mobile Data Exchange developed for mobile operators who are interested in global\ncoverage services for their subscribers. Currently local prices on mobile services are already\navailable in 80+ countries.\nWe are running an ICO to gather funds mainly for development\nmarketing, expanding and sustainability of the ecosystem."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://bubbletone.io/BubbleTone_Whitepaper_29Dec2017.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://bubbletone.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/Clementvale-LTD"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@bubbletone"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=3075196"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/bubbletone_eng"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/bubbletone"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/BubbleTone-Eng-836837033150145/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "http://bubbletone.io/"
    sales_agreement = "http://bubbletone.io/UMT_Terms_and_Conditions.pdf"

    [ico.common_info.token_distribution]
    total_supply = "1000000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "50"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "Founders"

      [[ico.common_info.token_distribution.shares]]
      percent = "22"
      description = "Network Development Fund"

      [[ico.common_info.token_distribution.shares]]
      percent = "7.8"
      description = "Team & Community Development Fund"

      [[ico.common_info.token_distribution.shares]]
      percent = "0.2"
      description = "Bounty"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "500000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "ETH"
      amount = "35000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-20"
    end_date = "2018-05-20"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "31.5%"
      condition = "01.02-10.02"

      [[ico.phases.prices.bonuses]]
      amount = "20%"
      condition = "11.02-20.02"

[[token]]
name = "UMT token"
symbol = "UMT"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""