[blockchain]
project_name = "Loyakk"
headline = "Loyakk Vega - The Platform for Decentralized Business Networks"
short_description = "Loyakk Vega is a blockchain-enabled Decentralized Business Networks Platform that enables enterprises to securely and efficiently exchange critical data and value within their business networks and in a contextual and relationship-aware manner. The Loyakk Vega Platform embeds proprietary patent-pending blockchain technology implementation with advanced enterprise relationship management capabilities to address modern business-to-business engagement challenges across industries. Loyakk Vega powers a full stack solution that includes the critical application and platform components and services that’s designed to readily enable early and evolving blockchain use cases across industries while supporting a firm’s vision and roadmap for enterprise-wide blockchain implementation and digital transformation."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://www.loyakk.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/Loyakkio/loyakk"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/LoyakkVega"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/loyakk/?fref=ts"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://www.loyakk.io/"
    sales_agreement = "https://www.loyakk.io/assets/Loyakk-Token-Terms-&-Conditions-O21.pdf"

    [ico.common_info.token_distribution]
    total_supply = "1000000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "61"
      description = "Token Purchasers"

      [[ico.common_info.token_distribution.shares]]
      percent = "17"
      description = "Team & Advisors"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Blockchain Research Fund"

      [[ico.common_info.token_distribution.shares]]
      percent = "7"
      description = "Incentives"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Partners"

    [[ico.common_info.use_of_proceeds]]
    percent = "45"
    description = "Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Operations"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Sales and Customer Adoption"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Legal and Administrative"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token sale"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "183000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-02-23"
    end_date = "2018-04-23"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "20-25%"
      condition = "Days 1-5"

      [[ico.phases.prices.bonuses]]
      amount = "15-20%"
      condition = "Days 6-10"

      [[ico.phases.prices.bonuses]]
      amount = "7-10%"
      condition = "Days 11-15"

[[token]]
name = "LYK token"
symbol = "LYK"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = "Ownership of Loyakk Token carries no rights express or implied"
governance_rights_org = ""

[[app]]
name = "Loyakk Vega Business Relationship Platform"
same_blockchain = "true"
sources_availability = "true"
app_status = "1"
app_type = "Web app"
app_url = ""