
genesis_id = ""
system = "Confideal"
dependencies = ["Ethereum"]
icon = "confideal"

[token]
name = "confideal token"
symbol = "CDL"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Unique smart contract management service"

[crowdsales]
start_date = "2017-11-02T11:00:00"
end_date = "2017-11-22T12:01:00"
end_date_plan = "2017-11-22T12:01:00"
genesis_address = [""]
funding_terms = "https://confideal.io/pdf/terms_and_conditions.pdf"
funding_url = "https://confideal.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 100000000

[[links]]
type = "website"
name = "confideal.io"
url = "https://confideal.io"
tags = ["Main"]

[[links]]
type = "paper"
name = "Confideal Whitepaper"
url = "https://confideal.io/pdf/confideal_whitepaper_en.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Confideal Github"
url = "https://github.com/confideal"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = "Confideal Blog"
url = "https://medium.com/@confideal"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2201499"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/confideal_io"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Confideal Telegram"
url = "https://t.me/confidealioeng"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Confideal/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/confideal.io/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Steem"
url = "https://steemit.com/@confideal"
icon = "steem.png"
tags = ["News"]
