[blockchain]
project_name = "SHOP"
headline = "The first token built for shopping."
short_description = "Протокол SHOP децентрализованная платформа для торговли и обмена данными, построенная на основе Smart Contracts. Этот протокол позволяет торговым маркам и продавцам выполнять всю свою коммерческую деятельность, вознаграждая участников за внесение данных, которые явно ценны для других пользователей системы. Благодаря взаимодействию с протоколом создается множество информации, начиная от вариантов доставки и заканчивая отзывами покупателей. Затем эта информация может быть доступна любой компании и покупателю на рынке в обмен на токены SHOP."
logo = ""
state = "0"
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/joinchat/HUKPSA5F_VGyJHWv-vl0QQ"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "http://www.twitter.com/_shoppersshop"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2969137.msg30507564#msg30507564"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/Shop_/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@shoppers_shop"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "http://www.facebook.com/shoppersio"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://github.com/ShoppersShop/whitepaper/blob/master/technical-white-paper.org"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://shoppers.shop/"
  tags = [
    "Main"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 2.0
  current_phase_status = ""

    [ico.common_info.token_distribution]
    total_supply = "1000000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Public Sale"

      [[ico.common_info.token_distribution.shares]]
      percent = "45"
      description = "Embedded Rewards"

      [[ico.common_info.token_distribution.shares]]
      percent = "30"
      description = "Ecosystem Development"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Acquisitions"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Team"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Operations, Legal, and Patents"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Protocol Development & Scale"

    [[ico.common_info.use_of_proceeds]]
    percent = "35"
    description = "Shopper Member Acquisitions"

    [[ico.common_info.use_of_proceeds]]
    percent = "30"
    description = "Ecosystem Growth"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Founders' Compensation"

  [[ico.phases]]
  phase_name = ""
  phase_status = ""
  phase_num = 0.0

    [ico.phases.registration]
    start_date = "2018-02-20T00:00:00.000Z"
    end_date = "2018-04-29T00:00:00.000Z"
    website = "https://comrse.us7.list-manage.com/subscribe/post?u=b282e0972477825a568aaea3e&id=9652151157"
    terms = "https://shoppers.shop/"

    [ico.phases.terms]
    sales_agreement = "https://shoppers.shop/token-sale-terms-of-service/"
    sales_url = "https://comrse.us7.list-manage.com/subscribe/post?u=b282e0972477825a568aaea3e&id=9652151157"
    issued_tokens = 0.0
    sold_tokens = 0.0
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = 0.0

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      currency = ""
      address = ""

    [ico.phases.dates]
    start_date = "2018-02-20T00:00:00.000Z"
    end_date = "2018-03-29T00:00:00.000Z"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = 0.0

    [[ico.phases.contract]]
    address = ""
    type = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = 0.0

      [[ico.phases.prices.bonuses]]
      description = ""
      percent = ""

  [[ico.phases]]
  phase_name = "pre-sale"
  phase_status = "Active"
  phase_num = 1.0

    [ico.phases.registration]
    start_date = "2018-02-20T00:00:00.000Z"
    end_date = "2018-04-29T00:00:00.000Z"
    website = "https://comrse.us7.list-manage.com/subscribe/post?u=b282e0972477825a568aaea3e&id=9652151157"
    terms = "https://shoppers.shop/token-sale-terms-of-service/"

    [ico.phases.terms]
    sales_agreement = "https://shoppers.shop/token-sale-terms-of-service/"
    sales_url = "https://comrse.us7.list-manage.com/subscribe/post?u=b282e0972477825a568aaea3e&id=9652151157"
    issued_tokens = 0.0
    sold_tokens = 0.0
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = 0.0

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      currency = ""
      address = ""

    [ico.phases.dates]
    start_date = "2018-02-20T00:00:00.000Z"
    end_date = "2018-04-29T00:00:00.000Z"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = 0.0

    [[ico.phases.contract]]
    address = ""
    type = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = 0.0

      [[ico.phases.prices.bonuses]]
      description = ""
      percent = ""

  [[ico.phases]]
  phase_name = "ICO"
  phase_status = "Planned"
  phase_num = 2.0

    [ico.phases.registration]
    start_date = "2018-05-14T00:00:00.000Z"
    end_date = "2018-06-13T00:00:00.000Z"
    website = ""
    terms = "https://shoppers.shop/token-sale-terms-of-service/"

    [ico.phases.terms]
    sales_agreement = "https://shoppers.shop/token-sale-terms-of-service/"
    sales_url = "https://comrse.us7.list-manage.com/subscribe/post?u=b282e0972477825a568aaea3e&id=9652151157"
    issued_tokens = "105000000"
    sold_tokens = 0.0
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = 0.0

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      currency = ""
      address = ""

    [ico.phases.dates]
    start_date = "2018-05-14T00:00:00.000Z"
    end_date = "2018-06-13T00:00:00.000Z"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = 0.0

    [[ico.phases.contract]]
    address = ""
    type = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = 0.0

      [[ico.phases.prices.bonuses]]
      description = ""
      percent = ""

[app]
info = []

[[token]]
inflation_rate = ""
circulation_terms = ""
governance_rights_org = "Shoppers will use tokens similar to loyalty points with the additional value of being able to vote on desired products, offers, and features as it relates to the customer journey."
governance_rights_project = "Supply chain participants will use them as access tokens and will have a right and obligation to participate in the growth, optimization, and success of the protocol.\nSupply chain participants will vote on how best to respond to consumer preferences. This activity will also define the going value of different value sets within the protocol.\n"
name = "SHOP Token"
symbol = "SHOP"
token_purpose = "Utility"
token_type = "Core token"

[[exchange]]
exchange = ""
date = ""
price = ""
volume = ""

[[label]]
blockchain = ""
address = ""
balance = ""