app = []

[blockchain]
project_name = "Sooloox"
headline = "Sooloox enables users to make money with their data "
short_description = "SOOLOOX provides a blockchain-adaptive tool that allows the handling of peer-to-peer transactions. This tool\nis called IDTX. IDTX stands for Interest Dimension & Transaction Box.\nWith IDTX, users can generate revenue with data related to their interests.\nUsers in the role of a vendor can buy these leads and convert them to purchase agreements (transaction\nleads) - i.e. faster and less expensive sales and rental of suitable products, etc.\nPage 8\nVersion 01.2018\nClassic Marketing Approach\nCompanies use marketing to attract the interest of customers.\nUsers, in the role of interests’ providers, benefit from the platform's technological approach directly and\nindirectly because they can transact and monetize their data as leads.\nDisruptive SOOLOOX Marketing Approach\nCustomers use the IDTX to get their interests discovered by suppliers.\n2.3 Data monetization: USERs can earn from their data.\nSOOLOOX provides, through appropriate application, the possibility for people's interests to be inspired,\norganized, and communicated. Interest- and profile-related data regularly form the start of product-related\ntransactions.\nIncome opportunities through leads:\n- View offers\n- Qualify for offers\n- Express needs \"appropriately\" to get \"appropriate\" offers\n- Visit specified geographic locations\n- Confirm purchasing decisions\n- Receive bonus with complaint-free purchase process\n- Create reviews of purchasing experience\n- Verify reviews of purchasing experience\n- Define interest profile\n- Define needs profile\n- Define inventory profile\nPage 9\nVersion 01.2018\n- License inventory profile for demand-related advertising\n- License interest profiles for demand-related advertising\n- License wish profile for demand-related advertising\n- License interests profile for information-seeking organizations (e.g. institutes)\n- License opinion profile for information-seeking organizations (e.g. institutes)\n- License competence profile (e.g. Headhunter)\n- License opportunity profiles (e.g. apartment vacancy)\n- Evaluate products & contents\n- Make recommendations\n- Identify profiles"
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://www.sooloox.com/white-paper/"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://www.sooloox.com/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/soolooxinc"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://facebook.com/sooloox"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://www.sooloox.com/"
    sales_agreement = "https://www.sooloox.com/white-paper/"

    [ico.common_info.token_distribution]
    total_supply = "30000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "70"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "30"
      description = "Reserve"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "21000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "30000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-04-16"
    end_date = "2018-06-30"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "CASH ACCOUNT-KEY"
symbol = "CAK"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""