app = []

[blockchain]
project_name = "trade.io"
headline = "JOIN THE TRADING REVOLUTION"
short_description = "By using our innovative and trusted trade.io blockchain trading platform, we will democratize the\nmarkets and save money for investors and companies, reducing and in some cases, eliminating\nthe tremendous fees and inefficiencies traditionally associated with asset trading.\ntrade.io is a next generation financial institution based on blockchain technology, providing the\nultimate in security and transparency. By leveraging decades of experience in the investment\nbanking, trading & fintech sectors, and combining them with the power and transparency of the\ndistributed ledger, we’ve created a truly unique product that will revolutionize asset trading and\ninvestment banking.\nAs well as asset trading, the trade.io exchange supports a more efficient and secure method\nof listing assets in the crypto economy, using the trusted record keeping capabilities that only\nblockchain provides. This is coupled with trade.io’s investment banking and advisory expertise\nand the reassurance that comes with operating in a regulated environment.\nUltimately, trade.io will be a trading and financing platform for more than just crypto assets. It\nwill also offer Forex and CFDs over precious metals, oil, commodities, indices, global equities, to\nname just a few. Offering more than 120 products at launch, trade.io will have the capacity to\ntrade any number of assets.\ntrade.io recognizes the potential for Blockchain to transform the global trading system and as a\nresult, has created an offering and product that not only fills a huge void in the FinTech space but\nwhich, most importantly, puts its investors’ and clients’ interests first."
state = "1"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://trade.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://trade.io/whitepaper/"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@trade.io"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2367245"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/TradeToken"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/TradeToken"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/trade.io"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://trade.io"
    sales_agreement = "https://trade.io/whitepaper"

    [ico.common_info.token_distribution]
    total_supply = "500000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "55"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Tokens For Liquidity Pool"

      [[ico.common_info.token_distribution.shares]]
      percent = "11"
      description = "Reserved Tokens"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "Founders and Developers"

      [[ico.common_info.token_distribution.shares]]
      percent = "11"
      description = "Advisors and Vendors"

    [[ico.common_info.use_of_proceeds]]
    percent = "23"
    description = "ACQUISITION & IP’S"

    [[ico.common_info.use_of_proceeds]]
    percent = "18"
    description = "LIQUIDITY POOL"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "OPERATIONS"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "LICENSES"

    [[ico.common_info.use_of_proceeds]]
    percent = "9"
    description = "SEED AND VENTURE FUND"

    [[ico.common_info.use_of_proceeds]]
    percent = "7"
    description = "DEVELOPMENT"

    [[ico.common_info.use_of_proceeds]]
    percent = "3"
    description = "LEGAL, AUDITS & ADVISORY"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "275000000"
    sold_tokens = "65782147"
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2017-11-07"
    end_date = "2017-12-15"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = "31169749"

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "Trade Token"
symbol = "TIO"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""