app = []

[blockchain]
project_name = "BitRewards"
headline = "BitRewards is a blockchain rewards and loyalty system for e-comm"
short_description = "Loyalty is trust. Trust is called a new currency, much like the bitcoin, because the difference in trust between a company and its competitor directly translates into how much money each is going to make. Every year millions of retailers spend in excess of $20 billion on software that improves the loyalty of their customers. They need to do that in order to stay competitive in the today’s crowded marketplace. Loyalty programs are not only costly, but also time consuming and cumbersome to set up. Often times, customers get only more frustrated from participation in them, complaining about difficulty to earn points or bonuses and to redeem them. This results in the fact that most loyalty programs just don’t pay themselves off, and shut down in less than 12 months’ time. We are a team who has worked together for 5 years in GIFTD, an innovative profitable loyalty SaaS company that helps hundreds of small and medium-sized e-commerce businesses to increase their revenue by an average of more than 17%. We are building BitRewards as a spinoff from this successful business, because blockchain technology allows for introducing a novel approach towards loyalty and rewards market, which will create new value for customers, merchants and the community-at-large. BitRewards is a blockchain loyalty platform and ecosystem that enables retailers to reward their customers' purchases, friends' invited and other configurable actions with crypto-currency. It has an absolute value for the customers, as they get for their purchases the liquid Ethereum-based tokens, which can be redeemed for purchases or transferred to another crypto-wallet. The price of the tokens is also set for growth due to our unique business model, so these rewards may go up in value in the course of time, rather than expire. BitRewards also brings a lot of benefits to the retailers, because they get customers that are more satisfied with the rewards in crypto and become even more loyal. A comprehensive loyalty program increases the retailers’ revenue by dozens of percents. The stores are also tapping into the cryptoenthusiasts audience, which is quite active and appreciates the attention from the regular businesses. The unique value proposition for the retailers is that BitRewards will offer this valuable and expensive loyalty technology free of charge. The retailers will only have to buy BIT in the open market to reward their users. The value of such software starts from $200/month, therefore thousands of retailers will be keen to connect to the platform. We can make such a claim, because we operate in the market of rewards and loyalty software for more than 5 years, have more than five hundred clients - online stores and deeply know their needs. BitRewards also uses AI-based predictive analytics, which allows to configure the rewards and actions for each particular business to address its unique target audience and achieve the highest return on investment from every dollar spent on the rewards. 6 BitRewards is compatible with most existing e-commerce systems (Magento, Shopify, WordPress, Ecwid, etc.). It is easy to integrate and has a simple API."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://bitrewards.network/wp.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://bitrewards.network/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@bitrewards"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2409919"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/bitrewards"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/bitrewards"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/BitRewards_Official/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/BitRewards"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/bitrewards.network"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://bitrewards.network/"
    sales_agreement = "https://bitrewards.network/brw-terms-of-use-for-website.pdf"

    [ico.common_info.token_distribution]
    total_supply = "2000000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "12"
      description = "Reserve for liquidity"

      [[ico.common_info.token_distribution.shares]]
      percent = "64"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "14"
      description = "Management"

      [[ico.common_info.token_distribution.shares]]
      percent = "3.5"
      description = "Advisers"

      [[ico.common_info.token_distribution.shares]]
      percent = "2"
      description = "Bounty"

      [[ico.common_info.token_distribution.shares]]
      percent = "2.5"
      description = "Marketing"

      [[ico.common_info.token_distribution.shares]]
      percent = "2"
      description = "Contingency"

    [[ico.common_info.use_of_proceeds]]
    percent = "27"
    description = "Product Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "12"
    description = "Operations"

    [[ico.common_info.use_of_proceeds]]
    percent = "39"
    description = "Marketing, sales, merchant acquisition & partnerships"

    [[ico.common_info.use_of_proceeds]]
    percent = "6"
    description = "Legal"

    [[ico.common_info.use_of_proceeds]]
    percent = "16"
    description = "Management"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "1280000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "15000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-04-01"
    end_date = "2018-04-30"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "BIT token"
symbol = "Bit"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = "All unsold tokens will be burnt"
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""