app = []

[blockchain]
project_name = "RepuX"
headline = "Decentralized Data & Applications Platform"
short_description = "RepuX is a protocol level framework (the “RepuX Protocol”) on which various types of immutable data can be commoditized and exchanged among different corporate and individual collectors, developers and users. The RepuX Protocol combines multiple decentralized technologies such as InterPlanetary File System (or IPFS)2, Sia3, Ethereum4, EOS5, and offers the potential to upgrade to a custom high-throughput blockchain. By facilitating the transfer of data and value between peers, the RepuX Protocol creates data sharing possibilities among data collectors, application developers and data users which do not exist in the current marketplace. The RepuX Protocol provides the opportunity to data producers to create value in their data through facilitating the provision of this data to users in multiple industries, while eliminating the need for intermediaries in this process.\n\nWith the development of the RepuX Protocol, RepuX is well poised to take advantage of the reliance of machine learning, big data and artificial intelligence on large-scale aggregate data and to drive innovation in these respective fields. By evaluating the reliability of each entity and each transaction with respect to the data, and with verification by an Oracle system, we can ensure integrity within the RepuX Protocol and provide data users with greater confidence in the content and quality of the data they are purchasing."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://repux.io/white-paper.html"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://blog.repux.io/"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://repux.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/repux/token"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2613666.new#new"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/repu_x"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/repuxicoEN"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/RepuX/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/Repux-415260768888793/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://presale.repux.io/presale-register"
    sales_agreement = "https://repux.io/white-paper.html"

    [ico.common_info.token_distribution]
    total_supply = "500000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "50"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Rewards Pool"

      [[ico.common_info.token_distribution.shares]]
      percent = "23"
      description = "Sold on the Platform"

      [[ico.common_info.token_distribution.shares]]
      percent = "12"
      description = "Founding team, 3 years vesting period"

      [[ico.common_info.token_distribution.shares]]
      percent = "3"
      description = "Ambassadors"

      [[ico.common_info.token_distribution.shares]]
      percent = "2"
      description = "Token Sale bounties"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "250000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = "2018-04-05"
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "33100000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-06"
    end_date = "2018-04-05"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = "4700000"

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "50%"
      condition = "Pre-Sale"

      [[ico.phases.prices.bonuses]]
      amount = "30%"
      condition = "Days 1-7"

      [[ico.phases.prices.bonuses]]
      amount = "25%"
      condition = "Days 8-13"

      [[ico.phases.prices.bonuses]]
      amount = "20%"
      condition = "Days 14-19"

      [[ico.phases.prices.bonuses]]
      amount = "15%"
      condition = "Days 20-25"

      [[ico.phases.prices.bonuses]]
      amount = "10%"
      condition = "26-31"

[[token]]
name = "RepuX Token"
symbol = "RepuX"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""