app = []

[blockchain]
project_name = "Sp8de"
headline = "Cardano-based platform supplying unbiased public randomness."
short_description = "Welcome to Sp8de, a blockchain-based platform capable of supplying unbiased public randomness for\ndeveloping and running distributed casino applications. Sp8de is designed to suit the purposes of all the\nactors comprising the online casino landscape and as such represents the new breed of digital institutions, a\ndistributed intermediary.\nThe spark that lit this project and continues to inspire us now, is that early blockchain and Bitcoin casinos\nsimply didn’t get it right. The Blockchain community was younger and wilder, ideals of distributed freedom\nwere burning brighter… still, early adopters who applied blockchain technology to gambling promoted the\nwrong ideals; those undermining the image of decentralized casinos. Instead of promoting transparency and\ncost efficiency that characterize blockchain technology, they promoted anonymity and cyber anarchy. Instead\nof making the casino for everyone, they kept it to themselves.\nBy no means are we here to judge. Instead, we are here to change. We do not say that old ways are bad, but can\nprove that new ones are better. We hold faith in the decentralized future and appreciate the charm of gambling.\nWe soon realized that there is only a fragile wall of glass between the old centralized gambling and the future\nglobal distributed casino. This is it, a simple yet captivating idea. The future is here: we can run a zero-house\nedge decentralized casino with close-to-zero transaction fees and provably fair random numbers feeding\nentropy into a myriad of Smart-Contract-based open source casino applications that can be developed by\nanyone who has a worthy idea by means of state-of-the art application-specific as well general-purpose\nprogramming languages. “We can” was the silent voice of the idea. Now it is the marching echo of “we do”.\nAs it frequently happens, technological progress made a massive leap forward that went unnoticed by the\nmajority of human kind: people still prefer the traditional narrow-minded and boring online casinos that set\ndraconian house edges and cannot be proven fair. Once again, no one has the right to judge: it is just an\nexistential business need, produced by a dilapidated business model and an inch of greed.\nWorse than this, however, is that even the enlightened ones, those chosen to witness the dawn of the distributed\nworld have noticed a perfect fit between distributed consensus protocols and gambling applications, have\nsynthesized them and… nothing. Some of these projects got infamous due to money laundering accusations,\nsome have spoiled the beauty of the idea by running centralized online casinos and simply allowing for\ncryptocurrency deposits, others got their moments of fame during TGAs, today, however, few can recall even\nthe names of these projects. Of course, there are some notable exceptions to this rule, but while succeeding\nlocally all these projects have failed to create awareness. None of them has broadcasted the essential message:\n“There is no glass wall; the future of gambling is now; we are better in every single quantifiable aspect; if\nquantifiable is not enough, we also have the powerful idea of the distributed future, while those who are stuck\nin the past have only a couple of servers and an unaudited poker protocol”.\nWe will do what no one has done before. Sp8de is a blockchain-based platform for developing distributed\ngambling applications. As a platform for gambling applications with self-respect, we are equipped with the\nprotocol for generating fresh unbiased public randomness. As a team with some aspirations we have it provably\nfair and completely decentralized. We feel that it is important to be true to the spirit of the venture we embark\nupon: if blockchain is the universal and undisputed source of truth then it should also be the broadcast channel\nfor randomness. We think that single points of failure should be perceived by anyone as just a relic of the past.\n4\n Contents SP8DE\nThis feature, while setting us aside most starkly, is only a part of what we have to offer in terms of technological\nstack. In what follows we will dive deeper into the revolution we all are a part of and will explain in detail the best\niGaming protocol the world has ever seen. "
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://sp8de.com/sp8de_white_paper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://sp8de.com/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/SP8DE"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://steemit.com/@sp8de"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2659341"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/SP8DE_Official"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/sp8de/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/sp8deofficial/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://ico.sp8de.com/"
    sales_agreement = "https://sp8de.com/sp8de_white_paper.pdf"

    [ico.common_info.token_distribution]
    total_supply = "8888888888"

      [[ico.common_info.token_distribution.shares]]
      percent = "41.125"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "38.875"
      description = "Jackpot prize"

    [[ico.common_info.use_of_proceeds]]
    percent = "45"
    description = "Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Operations"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Legal"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Advisory"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Finished"

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "3655555558"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "1000000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-01-08"
    end_date = "2018-03-11"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = "9222"

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

    [[ico.phases.contract]]
    address = "0x30DdA19C0b94a88eD8784868Ec1e9375d9F0E27c"

[[token]]
name = "SPX token"
symbol = "SPX"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""