app = []

[blockchain]
project_name = "coinadvisor"
headline = "Trading platform: arbitrage, bot, multi accounts management tool"
short_description = "Blockchain, Smart Contract and Crypto technology are game changers with respect to the traditional\neconomy. Many activities will be completely revolutionized. Entire sectors will completely disappear\nover a couple of decades and many intermediaries will become useless. People are getting together\nto found something they truly want, something they truly believe in. Trust is the new fuel that will lead\nsleeping energy to explode in a disruptive wave that will economically and socially reshuffle the cards.\nCOIN ADVISOR is riding this disruptive wave, building a one stop shop for the Crypto community and a\npowerful TRADING PLATFORM that will make hedge fund technology and skills available to everybody.\nMachine Learning and Artificial Intelligence will no longer be an exclusive of big financial institutions.\nPrivate developers will now be able to increase their revenue by renting out their strategies to other\nprivate individuals. Furthermore, the possibility to unite several crypto and traditional brokers’ accounts\ninto one single interface will make it much easier to trade, engage in arbitrage or fully implement a hedge\nmarket neutral portfolio.\nOwners of CADV tokens will also be able to pass their trading signal to other users boosting their return.\nThe best free trading strategy provider will be awarded by COIN ADVISOR.\nOur major goal for carrying out an ICO is to create and develop a platform and a community that allows\neasy crypto-assets trading, both discretionary and automatically from different exchanges via a single\ninterface or cloud bot. Among the multitude of ways to launch a project, we chose the Initial Coin Offering\nbecause it broadens the pool of potential participants. An ICO allows us to reach people from all over the\nworld with the prospect of exponential endorsement of COIN ADVISOR in their respective areas."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://www.coinadvisor.pro/wp-content/uploads/2018/02/CoinAdvisor_White-paper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://www.coinadvisor.pro/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/coinadvisor"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/coin_advisor"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/thecoinadvisor"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://www.coinadvisor.pro/"
    sales_agreement = "https://www.coinadvisor.pro/#icodetails"

    [ico.common_info.token_distribution]
    total_supply = "24999999.8"

      [[ico.common_info.token_distribution.shares]]
      percent = "76"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "0.5"
      description = "Free Air Drop"

      [[ico.common_info.token_distribution.shares]]
      percent = "23.5"
      description = "Team and Advisory"

    [[ico.common_info.use_of_proceeds]]
    percent = "35"
    description = "Product Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "25"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Operations& Maintenance"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Bonus"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Legal/Regulations"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Reserve"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Pre Sale"
  phase_status = "Planned"

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "400000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "ETH"
      amount = "200"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-04-06"
    end_date = "2018-05-27"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "100%"
      condition = "6-23 Apr"

      [[ico.phases.prices.bonuses]]
      amount = "75%"
      condition = "23 Apr-21 May"

      [[ico.phases.prices.bonuses]]
      amount = "50%"
      condition = "21 May -24 June"

      [[ico.phases.prices.bonuses]]
      amount = "33%"
      condition = "24 June - 21 Sept"

      [[ico.phases.prices.bonuses]]
      amount = "25%"
      condition = "21 Sept-22 Oct"

      [[ico.phases.prices.bonuses]]
      amount = "20%"
      condition = "22 Oct"

    [[ico.phases.contract]]
    address = "0xAae1b51b120F384d5749b3f36260c543E49db665"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "ICO"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "19000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "15000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-06-24"
    end_date = "2018-11-25"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "CoinAdvisor Token"
symbol = "CADV"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""