app = []

[blockchain]
project_name = "Leonardian"
headline = "The Marketplace for Digital Assets and Services "
short_description = "Leonardian is a single marketplace providing direct connection between Clients who\nneed assets and services in the digital domain and the Providers who offer such. This\nencompasses everything from any end-user standard code product or custom developed\nto diverse copyright protected items such as graphical, audio, video, 3D and other\nelements to completely custom-tailored freelancer or company services upon request.\nNo intermediaries, low fees, full transparency: all based on the blockchain technology with\nfixed rules of operation.\nLeonardian is revolutionizing the market for digital assets by creating a\nsingle decentralized marketplace with low fees, high quality and speed,\nprotection of clients and fair treatment of providers.\nLeonardian\nOur goal is to democratize the digital asset market by providing a self-governing\ndecentralized ecosystem based on the following pillars:\nFlat fee to guarantee low transaction costs\nFlat fee to guarantee low transaction costs\nQuality assurance mechanism protecting all parties\nFair treatment of providers\nFlexible and instant payment methods\nFull transparency and further development of the platform based on the\ndecision of the community"
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://leonardian.com/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://leonardian.com/whitepaper/Leonardian_Whitepaper_EN.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/Leonardiancom"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/joinchat/HsVZbA0vExIfazCzBdP83Q"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/leonardiancom/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "slack"
  name = "Slack"
  url = "https://slack.leonardian.com/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://leonardian.com/"
    sales_agreement = "https://leonardian.com/"

    [ico.common_info.token_distribution]
    total_supply = "263000000 "

      [[ico.common_info.token_distribution.shares]]
      percent = "50"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "40"
      description = "Liquidity of the system"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Team"

    [[ico.common_info.use_of_proceeds]]
    percent = "40"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "30"
    description = "Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "Operational Costs"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Legal, Accountant, Compliance, Regulatory"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Unforeseen Costs"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Pre Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = ""
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "ETH"
      amount = "3000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-04-16"
    end_date = "2018-05-12"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Main Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = ""
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "ETH"
      amount = "65000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-06-11"
    end_date = "2018-08-06"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "LEON Token"
symbol = "LEON"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""