app = []

[blockchain]
project_name = "HDAC"
headline = "Hdac, IoT Contract & Payment Platform based on Blockchain."
short_description = "The IoT industry is on the verge of exponential growth. The Hdac platform provides the missing building blocks needed to enable IoT environments to thrive:\n\nAuthentication - devices can be correctly identified by one other\nMapping - once identified, they can connect seamlessly\nMachine to Machine transaction - devices can then bill each other\nHdac will solve these three issues by combining blockchain and IoT, allowing automated, machine-to-machine, ultra-low cost transactions between IoT devices that are authenticated, mapped and verified through the blockchain.\n\nIn its architecture the Hdac system uses a combination of public and private blockchains, which allows for previously unattainable transaction speeds. The technology will use quantum random number generation to secure these transactions.\n\nThe Hdac system will ultimately ensure the efficiency and security of exponential growth of the IoT industry."
state = "2"
asset_type = ""
dependency = "independent"
consensus_name = "Proof-of-Work"

  [[blockchain.milestone]]
  number = 1.0
  name = "Hdac consensus algorithm – launched Hdac operating environment field test – completed Hardware Wallet – to launch Advanced Security Module – to launch Hdac apps API – to launch"
  start_date = "2017"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 2.0
  name = "Hdac operating environment – to launch Hdac IoT Contract PoC IoT authentication and device control Private Blockchain PoC Smart IoT diffusion PoC"
  start_date = "2018"
  current_status = "In work"

  [[blockchain.milestone]]
  number = 3.0
  name = "Practical application of Hdac IoT Contract & Smart Home – to launch Practical application of Hdac IoT Contract & Smart Factory – to launch Hdac Hybrid Blockchain – development"
  start_date = "2019"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 4.0
  name = "IoT High Speed ​​Transaction Distributed Processing Blockchain – development Private Blockchain Security Enhancements , Advanced Security Module Ver 2.0 – to launch Hdac Hybrid Blockchain Network Live Operation"
  start_date = "2020"
  current_status = "Planned"

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://hdac.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/Hdac_TGE"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/hdactech"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/HDAC%E2%80%8B"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/hdactech"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://github.com/Hdactech/Hdac/wiki/Hdac-Technical-Whitepaper"
  tags = [
    "Main",
    "Science"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://www.hdac.io/"
    sales_agreement = "https://www.hdac.io/"

    [ico.common_info.token_distribution]
    total_supply = "12000000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "7"
      description = "will be kept for capital reserve."

      [[ico.common_info.token_distribution.shares]]
      percent = "7"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "86"
      description = "can be earned through equitable 'ePoW' mining. "

    [[ico.common_info.use_of_proceeds]]
    percent = "35"
    description = "Capital Reserves"

    [[ico.common_info.use_of_proceeds]]
    percent = "1"
    description = "Hdac foundation"

    [[ico.common_info.use_of_proceeds]]
    percent = "14"
    description = "Hdac technology AG"

    [[ico.common_info.use_of_proceeds]]
    percent = "12"
    description = "Hdac Core R&D"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Hdac IoT Hardware R&D"

    [[ico.common_info.use_of_proceeds]]
    percent = "7"
    description = "Operation"

    [[ico.common_info.use_of_proceeds]]
    percent = "11"
    description = "Global Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "11"
    description = "Strategic Partners"

    [[ico.common_info.use_of_proceeds]]
    percent = "4"
    description = "Business Development"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Tokensale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "840000000 "
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "87700000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2017-11-27"
    end_date = "2017-12-22"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = "20000000"

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = "0.00006"

[[token]]
name = "DAC token"
symbol = "DAC"
token_purpose = "Both"
token_type = "Core token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""