
genesis_id = ""
system = "Lamden"
dependencies = ["Ethereum"]
icon = "lamden"

[token]
name = "tau token"
symbol = "TAU"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Framework for rapid deployment of blockchain technologies."

[crowdsales]
start_date = "2017-10-17T19:00:00"
end_date = "2017-11-01T15:59:00"
end_date_plan = "2017-11-01T15:59:00"
genesis_address = [""]
funding_terms = "https://daks2k3a4ib2z.cloudfront.net/599f63af83acb10001bd4583/59df939bb9bf250001a80455_Updated_Lamden_TOS_Oct_11_2017.pdf"
funding_url = "https://lamden.io/presale-registration"
tokens_sold = ""
tokens_issued = "53280090"
btc_raised = ""
cap_limit = ["usd = 5000000"]
raised = [""]

[specs]
supply = 500000000

[[links]]
type = "website"
name = "lamden.io"
url = "https://lamden.io"
tags = ["Main"]

[[links]]
type = "paper"
name = "Lamden Whitepaper"
url = "https://daks2k3a4ib2z.cloudfront.net/599f63af83acb10001bd4583/59d69f806fbb6f000123dbce_lamden-white-paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Lamden Github"
url = "https://github.com/Lamden/"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = "Lamden Blog"
url = "http://blog.lamden.io/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://www.twitter.com/LamdenTau/"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Lamden Slack"
url = "https://join.slack.com/t/lamden/shared_invite/MjQwMTI2OTIxNzgxLTE1MDUyMzgyMjAtNDg5MmYyNzRmZg"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = " Telegram"
url = "http://t.me/lamdentau"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "http://www.reddit.com/r/lamden"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/LamdenTau/"
icon = "facebook.png"
tags = ["News"]
