[blockchain]
project_name = " Altumea"
headline = "Decentralized GPU Computing"
short_description = "Altumea позволяет владельцам графических процессоров продавать дополнительные вычислительные мощности тем, кто нуждается в крупномасштабных расчетах: художники, инженеры, исследователи.\nПользователи будут иметь возможность покупать вычислительную мощность GPU непосредственно у владельцев  графических процессоров. Altumea предоставляет пользователям доступ к почти безграничной вычислительной мощности, которой владеют миллионы владельцев графических процессоров.\n"
logo = ""
state = "0"
dependency = "Ethereum"
consensus_name = "Proof-of-Work"

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://ico.altumea.io/media/whitepaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://altumea.io"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/altumea"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/altumea_io"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/altumeaproject/"
  tags = [
    "News"
  ]

  [[blockchain.milestone]]
  number = 1.0
  name = "Screening. Recruiting."
  start_date = "2017 Q3"
  current_status = "Completed"
  value = false

  [[blockchain.milestone]]
  number = 2.0
  name = "Funding completed. Work started."
  start_date = "2017 Q4"
  current_status = "Completed"
  value = false

  [[blockchain.milestone]]
  number = 3.0
  name = "Token Sale Campaign. Finalization of Pre-ITO. ITO"
  start_date = "2018 Q1"
  current_status = "In work"
  value = false

  [[blockchain.milestone]]
  number = 4.0
  name = "Distributed CUDA calculation prototype. Distributed data transfer processing."
  start_date = "2018  Q3"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 5.0
  name = "Market protocol. Blockchain integration. Prototype testing"
  start_date = "2018 Q4"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 6.0
  name = "Computer Consensus Validation System. Distributed OpenCL calculation type. Blockchain based reputation ledger."
  start_date = "2019 Q1"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 7.0
  name = "Alpha Launch"
  start_date = "2019 Q3"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 8.0
  name = "Distributed OpenCL Prototype. Deep learning tools"
  start_date = "2019 Q4"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 9.0
  name = "Reputation ledger. Market protocol actualization. Beta Launch."
  start_date = "2020 Q1"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 10.0
  name = "DApps integration use cases. Advance node protocol actualization."
  start_date = "2020 Q3"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 11.0
  name = "Release Launch"
  start_date = "2020 Q4"
  current_status = "Planned"
  value = false

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 1.0
  current_phase_status = ""

    [ico.common_info.token_distribution]
    total_supply = "50000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "60"
      description = "Token Sale"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = " Team"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Partners"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = " Liquidity Reserve"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Researchers"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "PR & marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "Partners, Advisors and Early Backers"

    [[ico.common_info.use_of_proceeds]]
    percent = "55"
    description = "Platform Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "7.5"
    description = "Legal and Compliance"

    [[ico.common_info.use_of_proceeds]]
    percent = "2.5"
    description = "Big Bounty"

  [[ico.phases]]
  phase_name = "Token Sale"
  phase_status = "Planned"
  phase_num = 0.0

    [ico.phases.registration]
    start_date = "2018-04-18T00:00:00.000Z"
    end_date = "2018-04-28T00:00:00.000Z"
    website = "https://altumea.io/token"
    terms = "https://altumea.io/faq"

    [ico.phases.terms]
    sales_agreement = "https://altumea.io/faq"
    sales_url = "https://altumea.io/token"
    issued_tokens = "30000000"
    sold_tokens = 0.0
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "ETH"
      amount = "30000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      currency = ""
      address = ""

    [ico.phases.dates]
    start_date = "2018-04-18T00:00:00.000Z"
    end_date = "2018-04-28T00:00:00.000Z"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = 0.0

    [[ico.phases.contract]]
    address = ""
    type = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = 0.0

      [[ico.phases.prices.bonuses]]
      amount = "+10% MEA"
      condition = "first 5 days"
      index = 0.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+1% MEA"
      condition = " 30 Ether"
      index = 1.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+2.5% MEA"
      condition = " 50 Ether "
      index = 2.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+5% MEA"
      condition = "100 Ether"
      index = 3.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+8% MEA"
      condition = "300 Ether"
      index = 4.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+10% MEA"
      condition = " 500 Ether"
      index = 5.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = " +15% MEA"
      condition = " 1K Ether"
      index = 6.0
      value = false

  [[ico.phases]]
  phase_name = "Token Sale"
  phase_status = "Planned"
  phase_num = 1.0

    [ico.phases.registration]
    start_date = "2018-04-18T00:00:00.000Z"
    end_date = "2018-04-28T00:00:00.000Z"
    website = "https://altumea.io/token"
    terms = "https://altumea.io/faq"

    [ico.phases.terms]
    sales_agreement = "https://altumea.io/faq"
    sales_url = "https://altumea.io/token"
    issued_tokens = "30000000"
    sold_tokens = 0.0
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "ETH"
      amount = "30000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      currency = ""
      address = ""

    [ico.phases.dates]
    start_date = "2018-04-18T00:00:00.000Z"
    end_date = "2018-04-28T00:00:00.000Z"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = 0.0

    [[ico.phases.contract]]
    address = ""
    type = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "ETH"
      price = "0.001"

      [[ico.phases.prices.bonuses]]
      amount = "+10% MEA"
      condition = "first 5 days"
      index = 0.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+1% MEA"
      condition = " 30 Ether"
      index = 1.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+2.5% MEA"
      condition = " 50 Ether "
      index = 2.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+5% MEA"
      condition = "100 Ether"
      index = 3.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+8% MEA"
      condition = "300 Ether"
      index = 4.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "+10% MEA"
      condition = " 500 Ether"
      index = 5.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = " +15% MEA"
      condition = " 1K Ether"
      index = 6.0
      value = false

[app]
info = []

[[token]]
inflation_rate = ""
circulation_terms = ""
governance_rights_org = ""
governance_rights_project = ""
symbol = "MEA"
name = "MEA Token"
token_purpose = "Utility"
token_type = "Core token"

[[exchange]]
exchange = ""
date = ""
price = ""
volume = ""

[[label]]
blockchain = ""
address = ""
balance = ""