app = []

[blockchain]
project_name = "Neurogress"
headline = "THINK. SHAPE YOUR WORLD."
short_description = "Neurogress (Geneva, Switzerland)\ndevelops software for neurocontrolling\nelectronics and machinery.\nWhat is neurocontrol? This is a\ntechnologically facilitated process\nwhich allows a person to directly\nmanipulate a device using brain waves.\nUntil recently, the ability to control\nobjects using the power of thought was\nlimited to the shape of our body. This\nis no longer true. A neurocontrol device\ngives humans the ability to control the\nworld directly using thought. Our\nthoughts are ready to be translated to\naction.\nThe potential uses for neurocontrolled\ndevices are vast. Building on this\nsoftware platform, Neurogress already\nintegrates its software and mechatronic\ncontrol into thought controlled\nprostheses and robots.\n\nHowever, Neurogress ultimately aims to\ndevelop an entire ecosystem of\nneurocontrolled devices based on its\nsoftware platform.\nThese emerging devices will be informed\nby aspirations and design requirements\ndrawn from diverse fields of human\nendeavor. Software and hardware\ndevelopers are the starting point, but\nthe perspectives of designers, artists,\ntechnology enthusiasts and\nphilanthropists will all play a part in\nenriching Neurogress’ vision.\nThe end goal for Neurogress is not just\nto encourage developers to bring\ninnovative new neurocontrolled devices\nto the market, but also to revolutionize\nhow people interact with technology.\nThrough gradually eliminating reliance\non cumbersome physical interfaces,\nNeurogress aims to transform how people\nbring their creative and intellectual\npursuits to fruition."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://drive.google.com/file/d/1rWFkKtDy7tuBwJ_oxSW2vEwAxEh3uqlM/view"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://neurogress.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/Neurogress"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/neurogress"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2809550.0"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "slack"
  name = "Slack"
  url = "https://neurogress.slack.com/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/pg/Neurogress-139431726679350"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/Neurogress"
  tags = [
    "Main",
    "Code"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://neurogress.io/"
    sales_agreement = "http://neurogress.io/terms-and-conditions/"

    [ico.common_info.token_distribution]
    total_supply = "100000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "50"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "50"
      description = "Product development"

    [[ico.common_info.use_of_proceeds]]
    percent = "32.5"
    description = "Software development (neurocontrol system)"

    [[ico.common_info.use_of_proceeds]]
    percent = "9.8"
    description = "Administrative"

    [[ico.common_info.use_of_proceeds]]
    percent = "10.5"
    description = "Marketplace development"

    [[ico.common_info.use_of_proceeds]]
    percent = "15.9"
    description = "Ecosystem development"

    [[ico.common_info.use_of_proceeds]]
    percent = "11.6"
    description = "Support of development community"

    [[ico.common_info.use_of_proceeds]]
    percent = "6.4"
    description = "Consulting services and outsourcing"

    [[ico.common_info.use_of_proceeds]]
    percent = "13.3"
    description = "Marketing campaign"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "50000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "ETH"
      amount = "58500"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-05-01"
    end_date = "2018-06-30"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "20%"
      condition = "First 6,450,000 tokens"

      [[ico.phases.prices.bonuses]]
      amount = "15%"
      condition = "Second 6,450,000 tokens"

      [[ico.phases.prices.bonuses]]
      amount = "10%"
      condition = "Third 6,450,000 tokens"

      [[ico.phases.prices.bonuses]]
      amount = "5%"
      condition = "Fourth 6,450,000 tokens"

[[token]]
name = "NEUROGRESS token"
symbol = "NRG"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""