
genesis_id = ""
system = "MBCH"
dependencies = [""]
icon = "mbch"

[token]
name = "mbch token"
symbol = "MBCH"

[consensus]
consensus_type = "POS"
consensus_name = "Proof-of-Stake"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Million Bitcoin Cash brings sound money to world. "

[crowdsales]
start_date = "2017-11-10T10:30:00"
end_date = "2017-11-11T22:30:00"
end_date_plan = "2017-11-11T22:30:00"
genesis_address = [""]
funding_terms = "https://millionbitcoincash.org/#plan"
funding_url = "https://btcfamilytrade.com/tsale.aspx"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "millionbitcoincash.org"
url = "https://www.millionbitcoincash.org"
tags = ["Main"]

[[links]]
type = "paper"
name = "MBCH Whitepaper"
url = "https://btcfamilytrade.com/img/MillionBitcoinCashWhite-paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "MBCH Github"
url = "https://www.github.com/MillionBitcoincash/millionbitcoincash"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "slack"
name = "MBCH Slack"
url = "https://millionbitcoincash.slack.com/?redir=%2Fmessages%2FD7DL06JN7"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = " Telegram"
url = "https://t.me/millionbitcoincash"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/user/millionbitcoincash/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Millionbitcoincash-135408390412704/"
icon = "facebook.png"
tags = ["News"]
