
genesis_id = ""
system = "Leverj"
dependencies = ["Ethereum"]
icon = "leverj"

[token]
name = "lev token"
symbol = "LEV"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized leveraged exchange."

[crowdsales]
start_date = "2017-11-07T12:00:00"
end_date = "2017-12-07T12:00:00"
end_date_plan = "2017-12-07T12:00:00"
genesis_address = [""]
funding_terms = "https://leverj.io/tc.html"
funding_url = "https://register.leverj.io/"
tokens_sold = ""
tokens_issued = "250000000"
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 1000000000

[[links]]
type = "website"
name = "leverj.io"
url = "https://leverj.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Leverj Whitepaper"
url = "https://leverj.io/whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Leverj Github"
url = "https://github.com/coinpit"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = "Leverj Blog"
url = "https://blog.leverj.io/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/Leverj_io"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Leverj Telegram"
url = "https://t.me/joinchat/C-gLzkMqKr1zmoeS-ZQePg"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Leverj/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UC9oq9zNCn5vFuWwtLuNLUfw"
icon = "youtube.png"
tags = ["News"]
