genesis_id = ""
system = "Chimaera"
dependencies = ["independent"]
icon = "chimaera"

[token]
name = "chimaera token"
symbol = "CHI"

[consensus]
consensus_type = "PoW"
consensus_name = "Proof-of-work"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralised Autonomous Universes (and games)"

[crowdsales]
start_date = "2017-10-16T18:00:00"
end_date = "2017-10-16T18:00:00"
end_date_plan = "2017-10-16T18:00:00"
genesis_address = [""]
funding_terms = "https://www.chimaera.io/downloads/Chimaera_White_Paper.pdf"
funding_url = "https://chimaera.io"
tokens_sold = 0
tokens_issued = 0
btc_raised = 0
cap_limit = [""]
raised = [""]

[specs]
supply = 75000000

[[links]]
type = "website"
name = "chimaera.io"
url = "https://chimaera.io"
tags = ["Main"]

[[links]]
type = "paper"
name = "Chimaera Whitepaper"
url = "https://www.chimaera.io/downloads/Chimaera_White_Paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Chimaera GitHub"
url = "https://github.com/chronokings"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/chimaera_tech"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/chimaeratech/"
icon = "facebook.png"
tags = ["News"]
