[blockchain]
project_name = "Dbrain"
headline = "A Blockchain Platform to Collectively Make AI Apps"
short_description = "Dbrain - openchchain платформа для коллективной сборки приложений искусственного интеллекта(ИИ). Он связывает коллекционеров и ученых, чтобы преобразовать необработанные данные в реальные решения ИИ для бизнеса, создавая беспроигрышную систему для всех участников рынка ИИ. С Dbrain каждый, у кого есть подключенное устройство, может выполнять простые задачи по обработке данных и мгновенно получать вознаграждение в виде криптовалюты. "
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"

  [[blockchain.milestone]]
  number = 1.0
  name = "Proof of concept and research phase to define the need for a collective AI development tool. Assembling the team"
  start_date = "2017 Q1"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 2.0
  name = "Product development and MVP testing  on the first business clients. Private seed round for $2.5m"
  start_date = "2017 Q4"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 3.0
  name = "Public Alpha version of web application  and Telegram bot to label and validate  data for crowdworkers (SPOCK). Coin sale"
  start_date = "2018 Q1"
  current_status = "In work"

  [[blockchain.milestone]]
  number = 4.0
  name = "Public Beta for training neural networks on labeled data, mobile app for data labeling. Dbraincoin (DBR) issue"
  start_date = "2018 Q2"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 5.0
  name = "Launch of the fully-running blockchain platform for building AI Apps with API integration for businesses. Partnership program for attracting business clients, active sales phase."
  start_date = "2018 Q3"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 6.0
  name = "Scaling platform to meet new markets with a focus on ever-growing AI community and client base "
  start_date = "2018 Q4"
  current_status = "Planned"

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://whitepaper.dbrain.io/"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://dbrain.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/joinchat/BSBzPk1gyw5grXyvBslXdg"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/dbrainio"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/dbrainio"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@dbrainio"
  tags = [
    "Main",
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://dbrain.io/"
    sales_agreement = "https://dbrain.io/"

    [ico.common_info.token_distribution]
    total_supply = ""
    shares = []

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "PreICO"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = "2017-12-15"
    end_date = "2018-03-31"
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = ""
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "40000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2017-12-15"
    end_date = "2018-03-31"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "USD"
      price = "2"

[[token]]
name = "Token DBR"
symbol = "DBR"
token_purpose = "Utility"
token_type = "Core token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""

[[app]]
name = "Dbrain"
same_blockchain = "true"
sources_availability = "true"
app_status = "2"
app_type = "Web App, Mobile App"
app_url = "https://my.dbrain.io/signup"