genesis_id = ""
system = "ARToken"
dependencies = ["Ethereum"]
icon = "artoken"

[token]
name = "artoken"
symbol = "AR"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized AR/VR ecosystem for 3D content exchange powered by ARToken"

[crowdsales]
start_date = "2017-10-25T13:00:00"
end_date = "2017-11-22T13:00:00"
end_date_plan = "2017-11-22T13:00:00"
genesis_address = [""]
funding_terms = "https://artoken.io/whitepaper?utm_source=cyberfund&utm_medium=tracker&utm_content=upcomingico"
funding_url = "https://artoken.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "artoken.io"
url = "https://artoken.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "ARToken Whitepaper"
url = "https://artoken.io/whitepaper?utm_source=cyberfund&utm_medium=tracker&utm_content=upcomingico"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "ARToken GitHub"
url = "https://github.com/CappasityTech/SmartContract/tree/master/contracts?utm_source=cyberfund&utm_medium=tracker&utm_content=upcomingico"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "ARToken Blog"
url = "https://blog.artoken.io/?utm_source=cyberfund&utm_medium=tracker&utm_content=upcomingico"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2135473.0&utm_source=cyberfund&utm_medium=tracker&utm_content=upcomingico"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/cappasity?utm_source=cyberfund&utm_medium=tracker&utm_content=upcomingico"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "ARToken Telegram"
url = "https://t.me/artoken?utm_source=cyberfund&utm_medium=tracker&utm_content=upcomingico"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "ARToken Slack"
url = "https://cappasity.herokuapp.com/?utm_source=cyberfund&utm_medium=tracker&utm_content=upcomingico- "
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/cappasity?utm_source=cyberfund&utm_medium=tracker&utm_content=upcomingico"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCRCSGdmb2ClX-3P9A6oXkAw?utm_source=cyberfund&utm_medium=tracker&utm_content=upcomingico"
icon = "youtube.png"
tags = ["News"]
