genesis_id = ""
system = "Agrello"
dependencies = ["Ethereum"]
icon = "agrello"

[token]
name = "agrello token"
symbol = "TM-AGRELLO"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Realizing the Vision of Legally-Binding Smart Contracts on Blockchain"

[[links]]
type = "website"
name = "agrello.org"
url = "https://www.agrello.org/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Agrello Whitepaper"
url = "https://docs.agrello.org/Agrello-Self-Aware_Whitepaper-English.pdf"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "Agrello Blog"
url = "https://blog.agrello.org/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1934422.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/AgrelloOfficial"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Agrello Telegram"
url = "https://t.me/agrello"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Agrello Slack"
url = "https://agrello-slack.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Agrello/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/agrellofoundation/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCJ939SlnjwRQvRpaKuA_iOw"
icon = "youtube.png"
tags = ["News"]
