app = []

[blockchain]
project_name = "EHAB"
headline = "Solving the global housing crisis through the blockchain"
short_description = "The main aim of ehab is to solve the global housing crisis. This will be achieved by\ntransitioning the residential house building sector from a centralised, unsustainable,\nprofit driven sector. To one which is led by people. To one which maximises human\nwell-being, minimises impact on the environment and allows for a more equitable\ndistribution in the financial gains of housing. Solving the global housing crisis is not\nas simple as building cheap housing. It has to be a holistic approach which enables\nthriving sustainable communities to emerge and flourish.\nEhab is the digital framework to make a decentralised housing system a reality.\nThe Individual: For individual people or families this means giving, you the customer,\nchoice over how your house is designed. It means providing you with clear information\nabout the costs and benefits of certain house types, so you can make the best decision\nfor your future in that house. We intend for the platform to remain useful even after\nthe development process has been completed. To continue to deliver value the\nplatform will be adapted with modules, developed by in house developers and external\ncompanies. These modules will add huge amounts of extra functionality to your\ndashboard and with internet of things (IoT) can turn a normal house into a smart one.\nConcurrently we will look to release a secondary marketplace for the growing number\nof IoT housing upgrades, the management of these will be run through modules on\nyour ehab platform dashboard.\nThe Community: On the neighbourhood scale this means groups of people making\ncollective decisions about things which will affect them and their families. This is direct\ndemocracy and the blockchain is the perfect way to facilitate this process. We don’t\nexpect this direct democracy to stop at aesthetic decisions though. Once you have\nbeen introduced to the possibilities of modern housing through the platform we expect\nthe community to want more. Community oriented modules could unlock microeconomies\n- e.g. for local food production and trading, or micro-energy grids where\nusers can more cheaply share excess energy. If households within the community all\npossess IoT devices the data from this could be collated and analysed for community\nwide benefit.\nThe City: The creation of new cities will eventually have to happen. The human\npopulation is rapidly urbanising and rising sea levels could see the many low lying cities\nmade uninhabitable in the next 100-200 years. A city is an incredibly complex entity of\nneeds and different incoming and outgoing resources. But we now know more than\never about what makes a liveable urban environment and what makes a poor one.\nMany of our current cities fall into this secondary category just because of the historical\nand cultural evolution they have been through. Any future city must meet the needs of\nits inhabitants, and enable them to flourish, whilst also allowing for citizens to have an\nequitable say in how it is developed and it’s continuing evolution.\nThe ehab platform in the first instance gathers the requirements from the potential\ninhabitants and start to build a database of different needs. This data could then\nbe integrated with the most up to data about the best percentage of urban green\nspaces, the ideal width of cycle paths, the optimum heights of tram pathways etc.\nWith this combination of data the platform could be enabled with artificial intelligence\n(AI) to make design decisions, at the base level about where zones could be placed\nor where wind turbines could be place in accordance with common wind direction.\nBut eventually, with the guidance of human designers and master-planners, it could\npresent a 3d masterplan of an entire city. It would know all the needs of the people and\nhave all the information collated from around the world about what currently makes\nthe optimum city.\nThe platform will still be being used by individuals and communities as a payment\nmechanism, a mechanism for direct democracy and micro-grid management. The tool\ncould be used for people to propose citywide initiatives, digital improvements, physical\nimprovements, art projects or events and then crowdfund the capital requirements\nfor these projects. The AI functionality could be scaled. The AI could be upgraded\nto effectively monitor payment flows and identify cost savings. It could help broker\nenergy deals between various microgrids to create a collection of microgrids which\nhelp balance the inflow and outflow of renewably generated energy. It could manage\nthe public transport system, or the network of autonomous cars.\nAll of this would be recorded on the blockchain, and every inhabitant, young or old,\ncould scroll back through the history of ehab to the day the first home was built on the\nplatform, all the way through to the day the first crowdfunded city was democratically\nfinanced and built. "
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://ehab.co/wp-content/uploads/2018/01/ehab-whitepaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://ehab.co/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/the-ehab-platform"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2834058.0"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/ehabplatform"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/ehabplatform"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/ehabplatform"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://ehab.co/"
    sales_agreement = "https://medium.com/the-ehab-platform/how-to-participate-in-the-ehab-token-sale-7c2a170dc9e3"

    [ico.common_info.token_distribution]
    total_supply = "4600000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "50"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "43"
      description = "Tokens frozen in ehab wallet for 12 months"

      [[ico.common_info.token_distribution.shares]]
      percent = "7"
      description = "Used for team, advisors, and bounty"

    [[ico.common_info.use_of_proceeds]]
    percent = "32"
    description = "Wages"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "Expenses"

    [[ico.common_info.use_of_proceeds]]
    percent = "18"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Tax budget"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "First project"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "2251000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "ETH"
      amount = "75000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-02-09"
    end_date = "2018-04-30"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "EHB token"
symbol = "EHB"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""