
genesis_id = ""
system = "IAC Crowdsale"
dependencies = ["Ethereum"]
icon = "iaccrowdsale"

[token]
name = "injii access token"
symbol = "IAC"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Blockchain-based open broadcast of content supporting causes."

[crowdsales]
start_date = "2017-11-07T15:00:00"
end_date = "2017-11-30T15:00:00"
end_date_plan = "2017-11-30T15:00:00"
genesis_address = [""]
funding_terms = "https://s3.amazonaws.com/injiiaccesscoin/injiiWhitePaper.pdf"
funding_url = "http://coin.injii.com"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 1000000000

[[links]]
type = "website"
name = "coin.injii.com"
url = "http://coin.injii.com"
tags = ["Main"]

[[links]]
type = "paper"
name = "IAC Crowdsale Whitepaper"
url = "https://s3.amazonaws.com/injiiaccesscoin/injiiWhitePaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "IAC Crowdsale Github"
url = "https://github.com/injiiAccessCoin"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = "IAC Crowdsale Blog"
url = "http://medium.com/@injii"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2291892.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "http://twitter.com/injii"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = " Telegram"
url = "https://t.me/joinchat/GpOASg6sWcySD1EcnoBt4w"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/user/injiiaccesscoin"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://facebook.com/injii"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Steem"
url = "https://steemit.com/@injii"
icon = "steem.png"
tags = ["News"]
