genesis_id = ""
system = "Lendroid"
dependencies = ["Ethereum"]
icon = "lendroid"

[token]
name = "lendroid token"
symbol = "LST"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized Digital Asset Lending Platform"

[[links]]
type = "website"
name = "lendroid.com"
url = "https://lendroid.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Lendroid Whitepaper"
url = "https://lendroid.com/assets/whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Lendroid GitHub"
url = "https://github.com/lendroidproject"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Lendroid Blog"
url = "https://blog.lendroid.com/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/lendroidproject"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Lendroid Slack"
url = "http://slack.lendroid.com/"
icon = "slack.png"
tags = ["News"]
