genesis_id = ""
system = "Streamr"
dependencies = ["Ethereum"]
icon = "streamr"

[token]
name = "DATAcoin token"
symbol = "DATA"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Create unstoppable real-time data apps, even without writing code"

[crowdsales]
start_date = "2017-10-06T12:00:00"
end_date = "2017-10-13T13:20:00"
end_date_plan = "2017-10-13T13:20:00"
genesis_address = [""]
funding_terms = "https://www.streamr.com/"
funding_url = "https://www.streamr.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "streamr.com"
url = "https://www.streamr.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Streamr Whitepaper"
url = "https://s3.amazonaws.com/streamr-public/streamr-datacoin-whitepaper-2017-07-25-v1_0.pdf"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "Streamr Blog"
url = "https://blog.streamr.com/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/streamrinc"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Streamr Telegram"
url = "https://www.streamr.com/assets/Icons/email.svg"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Streamr Slack"
url = "https://slack.streamr.com/"
icon = "slack.png"
tags = ["News"]
