genesis_id = ""
system = "Lescoin"
dependencies = ["Ethereum"]
icon = "lescoin"

[token]
name = "lescoin token"
symbol = "LSC"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Crypto-currency secured by wood stock"

[crowdsales]
start_date = "2017-09-18T09:00:00"
end_date = "2017-10-18T20:00:00"
end_date_plan = "2017-10-18T20:00:00"
genesis_address = [""]
funding_terms = "https://bit.ly/Lescoin_WP_EN"
funding_url = "https://lescoin.io"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "lescoin.io"
url = "https://lescoin.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Lescoin Whitepaper"
url = "https://bit.ly/Lescoin_WP_EN"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Lescoin GitHub"
url = " https://github.com/Lescoin/ico"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Lescoin Blog"
url = "https://medium.com/@lescoin"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2190584"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/DAO_Lescoin"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Lescoin Telegram"
url = "https://t.me/lescoin"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Lescoin Slack"
url = "https://lescoin.slack.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/DAO-Lescoin-270668693421364"
icon = "facebook.png"
tags = ["News"]
