[blockchain]
project_name = "AIRPOD"
headline = "Transforming Travel and Napping Industry"
short_description = "AirPod – это частный блок  «капсульного стиля» для  отдыха в общественных местах, таких как аэропорты, отели, железнодорожные и автобусные станции, торговые центры и коммерческие предприятия. Это простое решение для людей, нуждающихся в отдыхе, сне или изолированном рабочем пространстве. AirPod включает много передовых технологий, которые позволяют пользователям использовать бесплатный Wi-Fi, смотреть фильмы, слушать музыку, читать книгу или просто отдохнуть ."
logo = ""
state = "0"
dependency = "Ethereum"
consensus_name = "Proof-of-Work"

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/airpodsleepingpod/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/airpod_project"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/airpodsleepingpodproject"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://air-pod.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://air-pod.io/wp-content/uploads/2018/02/AirPod_Whitepaper_A4.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/airpod-blog"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.milestone]]
  number = 1.0
  name = "PRE-SALE begins"
  start_date = "2018-03-07"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 2.0
  name = "EVENT and PRESS conference Pre-production Prototype revealed (MVP)"
  start_date = "2018-03-01"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 3.0
  name = "ICO Starts"
  start_date = "2018-03-20"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 4.0
  name = "ICO Ends"
  start_date = "2018-04-20"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 5.0
  name = "AIRPOD mass production infrastructure completed"
  start_date = "2018 Q2"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 6.0
  name = "Production Starts first 10 AIRPODS manufactured"
  start_date = "2018 Q2"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 7.0
  name = "Commercial test of first 10 AIRPODs on UK Airports - PROOF OF CONCEPT"
  start_date = "2018 Q3"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 8.0
  name = "100 AIRPODS installed"
  start_date = "2019 Q1"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 9.0
  name = "400 AIRPODs installed Transition to 2nd Phase (introduction the DAPP Platform)"
  start_date = "2019 Q3"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 10.0
  name = "500 AIRPODs installed DAPP open to public - 3rd Phase"
  start_date = "2020 Q1"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 11.0
  name = "1000 AIRPODs installed"
  start_date = "2021 Q2"
  current_status = "Planned"
  value = false

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 1.0
  current_phase_status = ""

    [ico.common_info.token_distribution]
    total_supply = "250000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "80"
      description = "Crowdsale"

      [[ico.common_info.token_distribution.shares]]
      percent = "12"
      description = "Founders Fund"

      [[ico.common_info.token_distribution.shares]]
      percent = "3.6"
      description = "Supporters & Contractors Fund"

      [[ico.common_info.token_distribution.shares]]
      percent = "2"
      description = "Bounty campaign"

      [[ico.common_info.token_distribution.shares]]
      percent = "1.2"
      description = "Advisers, Ambassadors"

      [[ico.common_info.token_distribution.shares]]
      percent = "0.8"
      description = "Company reserve "

      [[ico.common_info.token_distribution.shares]]
      percent = "0.4"
      description = "AirDrop"

    [[ico.common_info.use_of_proceeds]]
    percent = "61"
    description = "Production and distribution"

    [[ico.common_info.use_of_proceeds]]
    percent = "17"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "Company operations"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "DApp Platform development"

    [[ico.common_info.use_of_proceeds]]
    percent = "2"
    description = " Legal"

  [[ico.phases]]
  phase_name = "ICO"
  phase_status = "Planned"
  phase_num = 0.0

    [ico.phases.registration]
    start_date = "2018-03-20T00:00:00.000Z"
    end_date = "2018-04-20T00:00:00.000Z"
    website = "https://air-pod.io/kyc-form/"
    terms = "https://medium.com/airpod-blog/whitelist-step-by-step-contribution-instructions-for-airpod-ico-participants-2d2dde4bf36"

    [ico.phases.terms]
    sales_agreement = "https://medium.com/airpod-blog/whitelist-step-by-step-contribution-instructions-for-airpod-ico-participants-2d2dde4bf36"
    sales_url = "https://air-pod.io/kyc-form/"
    issued_tokens = "200000000"
    sold_tokens = 0.0
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "20000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      currency = ""
      address = ""

    [ico.phases.dates]
    start_date = "2018-03-20T00:00:00.000Z"
    end_date = "2018-04-20T00:00:00.000Z"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = 0.0

    [[ico.phases.contract]]
    address = ""
    type = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = "0.1"

      [[ico.phases.prices.bonuses]]
      description = ""
      percent = ""

  [[ico.phases]]
  phase_name = "ICO"
  phase_status = "Planned"
  phase_num = 1.0

    [ico.phases.registration]
    start_date = "2018-03-20T00:00:00.000Z"
    end_date = "2018-04-20T00:00:00.000Z"
    website = "https://air-pod.io/kyc-form/"
    terms = "https://medium.com/airpod-blog/whitelist-step-by-step-contribution-instructions-for-airpod-ico-participants-2d2dde4bf36"

    [ico.phases.terms]
    sales_agreement = "https://medium.com/airpod-blog/whitelist-step-by-step-contribution-instructions-for-airpod-ico-participants-2d2dde4bf36"
    sales_url = "https://air-pod.io/kyc-form/"
    issued_tokens = "200000000"
    sold_tokens = 0.0
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "20000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      currency = ""
      address = ""

    [ico.phases.dates]
    start_date = "2018-03-20T00:00:00.000Z"
    end_date = "2018-04-20T00:00:00.000Z"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = 0.0

    [[ico.phases.contract]]
    address = ""
    type = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = "0.1"

      [[ico.phases.prices.bonuses]]
      amount = "12"
      condition = "Those who contribute in first 48 hours"
      index = 0.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "9"
      condition = "Week 1"
      index = 1.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "6"
      condition = "Week 2"
      index = 2.0
      value = false

      [[ico.phases.prices.bonuses]]
      amount = "3"
      condition = "Week 3"
      index = 3.0
      value = false

[app]
info = []

[[token]]
inflation_rate = ""
circulation_terms = ""
governance_rights_org = ""
governance_rights_project = ""
name = "APOD Tokens"
symbol = "APOD"
token_purpose = "Utility"
token_type = "Core token"

[[exchange]]
exchange = ""
date = ""
price = ""
volume = ""

[[label]]
blockchain = ""
address = ""
balance = ""