app = []

[blockchain]
project_name = "Datawallet"
headline = "Blockchain-based C2B Data Exchange"
short_description = "Given the deficiencies of the prevailing data brokerage system, it is surprising\nhow few personal data-management tools are available to data creators. One\npromising option is to consider the development of specific blockchain-based web\nbrowsers6\nthat strive to allow user control over self-generated content. However,\nthis requires a major shift in user behavior with concomitant technological challenges.\nThis paper proposes an alternative that disrupts the data-brokerage system,\nand not the data-creators Internet experience. We propose a blockchain-technology\nbased DataWallet that restores trust and control for users while providing datainformed\nbusinesses the most complete data profiles possible."
state = "0"
asset_type = ""
dependency = "independent"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://datawallet.com/pdf/datawallet_whitepaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://datawallet.com/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/DataWallet"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/datawallet"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://datawallet.com/"
    sales_agreement = "https://datawallet.com/"

    [ico.common_info.token_distribution]
    total_supply = "1000000000"
    shares = []

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "250000000"
    sold_tokens = "250000000"
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-02-05"
    end_date = "2018-03-07"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = "39000000 "

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "DXT token"
symbol = "DXT"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""