genesis_id = ""
system = "Ties.network"
dependencies = ["Ethereum"]
icon = "tiesnetwork"

[token]
name = "tiesnetwork token"
symbol = "TIE"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized public smart database"

[crowdsales]
start_date = "2017-09-21T10:00:00"
end_date = "2017-10-12T14:00:00"
end_date_plan = "2017-10-12T14:00:00"
genesis_address = [""]
funding_terms = "https://ties.network/"
funding_url = "https://ties.network/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 140000000

[[links]]
type = "website"
name = "ties.network"
url = "https://ties.network/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Ties.network Whitepaper"
url = "https://docs.google.com/document/d/1deB6McO4pEH37CnVmfVmuXt190i_uEAekyexRPG3R4M/edit"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Ties.network GitHub"
url = "https://github.com/tiesnetwork"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Ties.network Blog"
url = "https://blog.ties.network/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2071592.0"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/tiesnetwork"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Ties.network Telegram"
url = "https://t.me/tiesnetwork"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Ties.network Slack"
url = "https://tiesnetwork.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/tiesnetwork/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/tiesdb"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCA125wWsdbsG1XPenWcBkyg"
icon = "youtube.png"
tags = ["News"]
