app = []

[blockchain]
project_name = "Skraps"
headline = "Invest your spare change to crypto"
short_description = "Skraps essentially works like Acorns but for cryptocurrency purchases. Users can\ninvest their cryptocurrency or fiat spare change with the Skraps platform to earn the\nrewards of consistent investing. For investing cryptocurrencies, a user will need to\nlink his cryptocurrency wallets to the Skraps platform. Whenever a user will make\na purchase or do a transaction, a round off amount will be invested in the Skraps\nportfolio. The user can select the type of portfolio he wants to invest in based on his\nrisk tolerance.\nFor example, suppose Alice is purchasing a flight ticket in Air Baltic using Bitcoins.\nThe price of the flight ticket is 12.98 BTC. She pays 12.98 BTC for the ticket. Then\nshe goes to the Skraps app and rounds up the transaction to 13 BTC. So the .02 gets\ninvested. The 0.02 BTC gets invested in a portfolio of her choice. Suppose Alice has\nselected to invest in the Conservative port-folio. Then the 0.02 BTC will be invested\nin the Conservative portfolio in the Skraps platform. Similarly, the spare changes after\ntransactions in fiat currency will be invested in the selected cryptocurrency portfolio.\nThe same scenario works for fiat. If Alice purchases a coffee for $3.75, she can round\nup the transaction to $4.00 and the difference (of $0.25) will get invested.\nThus, as users keep investing in the Skraps platform, their cryptocurrency investments\nwill increase in value. The investment happens with each transaction, so there is no\nmental overload to decide where to invest and how much. Our commitment is to make\ninvesting very simple and intuitive so that everyone can benefit from the returns of\ndisciplined investing."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://skraps.io/assets/files/SKRAPS_White_Paper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://skraps.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/SkrapsIO"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@SKRAPS_IO"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2520387.msg25746537#msg25746537"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/SKRAPS_IO"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/SkrapsOfficial"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/SKRAPSio/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/SKRAPSAPP/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "http://ico.skraps.io/"
    sales_agreement = "http://ico.skraps.io/"

    [ico.common_info.token_distribution]
    total_supply = "110000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "65"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "15"
      description = "Partnerships"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Team"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Bounty"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Advisors"

    [[ico.common_info.use_of_proceeds]]
    percent = "50"
    description = "Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "30"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Team hires"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Legal"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Others"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "66000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-02-25"
    end_date = "2018-04-15"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = "7000000"

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "SKRAPS token"
symbol = "SKRP"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""