app = []

[blockchain]
project_name = "CashBet Coin"
headline = "CashBet offers the only complete, crypto-ready iGaming platform."
short_description = "Mobile gaming and cryptocurrency are two of the fastest growing, demand-driven markets\nin the world today. CashBet is merging these technologies into an iGaming solution and\nissuing CashBet Coin to solve the problems facing crypto casino operators and players\ntoday: speed, trust, cost, content and access.\nCashBet is the only complete, crypto-ready, mobile-first iGaming platform with an\nestablished, profitable presence in regulated gaming markets. Launched in 2012, CashBet\nhas hundreds of thousands of registered players, tens of millions of Pounds Sterling\nwagered, gaming licenses in multiple jurisdictions, and customers from all facets of\niGaming (real-money, social, and skill-based) from around the world.\n● The CashBet platform is uniquely positioned to set the standard in the\nemerging cryptocurrency iGaming space. Architected and implemented by\niGaming veterans, its modular, end-to-end iGaming solution reflects years of both\nB2B and B2C iGaming experience. It is creating a proprietary off-chain payment\ntechnology that will significantly reduce costs and increase payout speeds, making\nCashBet Coin the most desirable cryptocurrency in the iGaming market.\n● The CashBet platform is the only crypto-casino platform licensed in multiple\ntier 1 gaming jurisdictions. The platform and all associated games - over 450 titles\n- have passed rigorous third-party compliance testing. It features a player and\ncontent management system, content distribution tailored for the crypto casino\nmarket, a geo-verification system, and a responsible gaming module, all of which\ncan be licensed to crypto casino operators. It includes full support for\nFATF-compliant Know Your Customer (KYC) and Anti-Money Laundering (AML)\ncompliance.\n● CashBet is white-label capable. CashBet empowers operators and developers to\neasily launch their own bespoke iGaming sites, content, and apps.\n● CashBet Coin (“CBC”) tokens will be offered to token purchasers during a\ntoken sale that commenced in January 2018. The acceptance of CBC will\ndemocratize access to world-class entertainment for those underserved by the\ncentralized banking establishment.\n● The phases of the CashBet solution are as follows:\no Phase 1 CashBet Coin VIP registration. CashBet registers players who\ndeposit 1,000 CBC attain instant VIP membership and substantial bonuses\nfor gameplay unavailable to players not holding the 1,000 CBC balance.\no Phase 2 CashBet crypto gaming. CashBet will convert CBC at the time of\nwager to a fiat currency and convert any winnings back to CBC at the same\nPage 3 of 39\n© CashBet 2018\nCashBet Initial Coin Offering\nrate. This will make hundreds of games available to cryptocurrency players\nand operators.\no Phase 3 Direct CBC wagering. CashBet enables wagering in CBC with no fiat\ncurrency conversion. In addition, Phase 3 will include the rollout of\nCryptoRGS, CashBet’s content distribution platform for crypto casino\noperators.\no Phase 4 CrytoGo Payment channel-based gaming. CashBet’s proprietary\nimplementation, CryptoGo, is an off-chain\n1 state channel-based payment\ntechnology. It will allow wagers and payouts made directly between players’\nERC20 capable wallets and the CashBet platform without the need for a\ndeposit account. This will allow immediate payouts and a significant\nreduction in fees."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://coin.cashbet.com/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://coin.cashbet.com/wp-content/uploads/2018/03/CashBet-Coin-Whitepaper_v3.2.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@CashBetCoin"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/cashbetcoin"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/cashbetcoin"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/CashBetCoin/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://coin.cashbet.com/"
    sales_agreement = "https://coin.cashbet.com/wp-content/uploads/2018/03/CashBet-Coin-Whitepaper_v3.2.pdf"

    [ico.common_info.token_distribution]
    total_supply = "430000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "33.25"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "35"
      description = "Casino Bank Reserve"

      [[ico.common_info.token_distribution.shares]]
      percent = "16.75"
      description = "Team"

      [[ico.common_info.token_distribution.shares]]
      percent = "8"
      description = "Referral"

      [[ico.common_info.token_distribution.shares]]
      percent = "7"
      description = "Advisors"

    [[ico.common_info.use_of_proceeds]]
    percent = "32"
    description = "Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Business development & partnerships"

    [[ico.common_info.use_of_proceeds]]
    percent = "17.5"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "7.5"
    description = "Team building"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "Debt restructiring"

    [[ico.common_info.use_of_proceeds]]
    percent = "8"
    description = "ICO related expences"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = ""
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-04-10"
    end_date = "2018-04-27"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "10%"
      condition = " first 24 hours"

      [[ico.phases.prices.bonuses]]
      amount = "6%"
      condition = "second 24 hours"

[[token]]
name = "CashBet Coin"
symbol = "CBC"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""