
genesis_id = ""
system = "SENSE"
dependencies = ["Ethereum"]
icon = "sense"

[token]
name = "sense token"
symbol = "SENSE"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Value for Human Capital Enabled by Smart Contracts"

[crowdsales]
start_date = "2017-10-16T09:00:00"
end_date = "2017-10-30T09:00:00"
end_date_plan = "2017-10-30T09:00:00"
genesis_address = [""]
funding_terms = "https://sensetoken.com/pdfs/sensetoken_whitepaper_en.pdf"
funding_url = "http://t.sensetoken.com/cyberfund"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = ["usd = 25000000"]
raised = [""]

[specs]
supply = 1000000000

[[links]]
type = "website"
name = "sensetoken.com"
url = "http://sensetoken.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Sense Whitepaper"
url = "https://sensetoken.com/pdfs/sensetoken_whitepaper_en.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Sense Github"
url = "https://github.com/sensay"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Sense Blog"
url = "https://medium.com/sensay"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2096600.msg20951702#msg20951702"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/sensay"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Sense Telegram"
url = "https://t.me/joinchat/AAAAAEQzTJW8N35CcmHlZA"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/sensetoken/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/sensaybot/"
icon = "facebook.png"
tags = ["News"]
