genesis_id = ""
system = "E4Row"
dependencies = ["Ethereum"]
icon = "e4row"

[token]
name = "e4row token"
symbol = "E4ROW"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Bringing Ether apps to the online/mobile gaming markets"

[aliases]
coinmarketcap = "E4ROW"
nickname = "E4ROW"

[crowdsales]
start_date = "2017-05-02T00:00:00"
end_date = "2017-05-23T00:00:00"
end_date_plan = "2017-05-23T00:00:00"
genesis_address = [""]
funding_terms = "http://doc.liveplayergames.com/docs/CCOD.pdf"
funding_url = "https://www.e4row.co.il/contribute"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "e4row.co.il"
url = "https://www.e4row.co.il/"
tags = ["Main"]

[[links]]
type = "paper"
name = "E4Row Whitepaper"
url = "http://doc.liveplayergames.com/docs/CCOD.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "E4Row GitHub"
url = "https://github.com/liveplayergames?tab=repositories"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "E4Row Blog"
url = "https://medium.com/e4row"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/E4ROW"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "E4Row Slack"
url = "https://e4row.slack.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/E4ROW/"
icon = "reddit.png"
tags = ["News"]
