genesis_id = ""
system = "Quantstamp"
dependencies = ["Ethereum"]
icon = "quantstamp"

[token]
name = "quantstamp token"
symbol = "QSP"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized Smart Contract Security Platform"

[crowdsales]
start_date = "2017-09-29T09:00:00"
end_date = "2017-10-29T09:00:00"
end_date_plan = "2017-10-29T09:00:00"
genesis_address = [""]
funding_terms = "https://quantstamp.com"
funding_url = "https://quantstamp.com"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "quantstamp.com"
url = "https://quantstamp.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Quantstamp Whitepaper"
url = "https://quantstamp.com/wp-content/uploads/2017/09/Quantstamp-Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Quantstamp GitHub"
url = "https://github.com/quantstamp"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Quantstamp Blog"
url = "https://medium.com/quantstamp"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/Quantstamp"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/quantstamp/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCXP3YLX4JdI0gGb9UKSunMg"
icon = "youtube.png"
tags = ["News"]
