
genesis_id = ""
system = "Raiden Network"
dependencies = ["Ethereum"]
icon = "raidennetwork"

[token]
name = "rdn token"
symbol = "RDN"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Fast, scalable transfers for Ethereum"

[crowdsales]
start_date = "2017-10-18T15:00:00"
end_date = "2017-11-18T15:00:00"
end_date_plan = "2017-11-18T15:00:00"
genesis_address = [""]
funding_terms = "https://raiden.network/"
funding_url = "https://raiden.network/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 100000000

[[links]]
type = "website"
name = "raiden.network"
url = "https://raiden.network/"
tags = ["Main"]

[[links]]
type = "github"
name = "Raiden Network Github"
url = "https://github.com/raiden-network/raiden"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Raiden Network Blog"
url = "https://medium.com/@raiden_network"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/raiden_network"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/raidennetwork/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCoUP_hnjUddEvbxmtNCcApg"
icon = "youtube.png"
tags = ["News"]
