app = []

[blockchain]
project_name = "TE-FOOD"
headline = "Food Quality and Supply Ecosystem for Emerging Markets"
short_description = "TE-FOOD is a successful food traceability solution, used by\n6,000+ companies, managing more than 400,000 transactions\neach day, reaching 30 million people.\nWe are dedicated to improve food safety, fight off corruption,\nsupport fair trade, and build trust between the food supply\nchain companies, consumers, and authorities in the emerging\nmarkets.\nWe believe that building a sustainable business on food safety\nis much more efficient to make difference than any type of aid."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://ico.tefoodint.com/te-food-white-paper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://ico.tefoodint.com/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@te_food"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2176849.0"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/TE_FOOD"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/tefood"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/TE_FOOD/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/tefoodintl/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://ico.tefoodint.com/"
    sales_agreement = "https://ico.tefoodint.com/te-food-white-paper.pdf"

    [ico.common_info.token_distribution]
    total_supply = "1000000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "51"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Marketing pool"

      [[ico.common_info.token_distribution.shares]]
      percent = "44"
      description = "General reserve"

    [[ico.common_info.use_of_proceeds]]
    percent = "60"
    description = "Market expansion"

    [[ico.common_info.use_of_proceeds]]
    percent = "25"
    description = "Research & development"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Operations"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Legal"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "512000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "16000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-02-22"
    end_date = "2018-03-22"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = "19100000"

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "15%"
      condition = "1st week"

      [[ico.phases.prices.bonuses]]
      amount = "12%"
      condition = "2nd week"

      [[ico.phases.prices.bonuses]]
      amount = "10%"
      condition = "3rd week"

      [[ico.phases.prices.bonuses]]
      amount = "5%"
      condition = "4th week"

[[token]]
name = "TFOOD"
symbol = "TFOOD"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""