genesis_id = ""
system = "Vega Fund"
dependencies = ["Ethereum"]
icon = "vegafund"

[token]
name = "vegafund token"
symbol = "VEGA"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Venture Capital Crowdfunding Platform"

[[links]]
type = "website"
name = "vega.fund"
url = "http://www.vega.fund/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Vega Fund Whitepaper"
url = "https://docs.google.com/document/d/1rgMqqoE7NNTPCLEGyCSBfYW39hqAPEi0U6tS105-U3g/edit"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Vega Fund GitHub"
url = "https://github.com/VegaProject"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Vega Fund Blog"
url = "https://medium.com/vega-fund"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/vega_fund"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Vega Fund Slack"
url = "https://vega-fund.slack.com/join/shared_invite/enQtMjU0NDkxODU2Njc3LWM1MWUzOTAxYzljYjczOTQ3NzY3NGViNGIwNDE5MjdlNDE0OThmNjQzOTAxODFhNGQwMGE1ZTc2MTQyZmEzMzM"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/watch?v=kfXL3-TlCZI"
icon = "youtube.png"
tags = ["News"]
