genesis_id = ""
system = "Propy"
dependencies = ["Ethereum"]
icon = "propy"

[token]
name = "propy token"
symbol = "PRO"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Global property Store with Decentralized Title Registry "

[aliases]
coinmarketcap = "Propy"

[[links]]
type = "website"
name = "propy.com"
url = "http://propy.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Propy Whitepaper"
url = "http://tokensale.propy.com/Propy-White-Paper-17-Jul-2017.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Propy GitHub"
url = "https://github.com/Propy"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Propy Blog"
url = "https://blog.propy.com/"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=1982115"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/PropyInc"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Propy Telegram"
url = "https://t.me/propy"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Propy Slack"
url = "http://propy.slack.com"
icon = "slack.png"
tags = ["News"]
