genesis_id = ""
system = "Nimiq"
dependencies = ["Ethereum"]
icon = "nimiq"

[token]
name = "nimiq token"
symbol = "NET"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Browser Based Blockchain"

[aliases]
coinmarketcap = "Nimiq"

[crowdsales]
start_date = "2017-06-28T13:00:00"
end_date = "2017-07-26T13:00:00"
end_date_plan = "2017-07-26T13:00:00"
genesis_address = [""]
funding_terms = "https://medium.com/nimiq-network/nimiq-network-token-sale-terms-9af2e7fd6228"
funding_url = "https://nimiq.com"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "nimiq.com"
url = "https://nimiq.com"
tags = ["Main"]

[[links]]
type = "paper"
name = "Nimiq Whitepaper"
url = "https://medium.com/nimiq-network/nimiq-a-peer-to-peer-payment-protocol-native-to-the-web-ffd324bb084"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Nimiq GitHub"
url = "https://github.com/nimiq-network"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "blog"
name = "Nimiq Blog"
url = "https://medium.com/nimiq-network"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/nimiqnetwork"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Nimiq Telegram"
url = "https://t.me/joinchat/AAAAAEJW-ozFwo7Er9jpHw"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/Nimiq/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCJ1qu3KXwfmkGwBkU8F1jQg"
icon = "youtube.png"
tags = ["News"]
