[blockchain]
project_name = "FIC Network"
headline = "Fixed income infrastructure for blockchain assets"
short_description = "FIC Network is an end-to-end decentralized fixed income securities network that enables the\nlisting, exchange, and securitization of fixed income financial instruments. FIC Network is\nan asset-agnostic, multi-currency distributed ledger primarily focused towards institutions\nusing traditional currencies and adapting to cryptocurrency markets. Crypto hedge funds and\ntraditional asset managers will greatly benefit from cost savings and expanded market\nopportunities.\nProblem\n1. Existing crypto tokens are operating as currencies or stocks and there is no real fixedincome\noffering. As the crypto markets mature, earning interest on your assets and\npaying interest to borrow assets will become the largest financial market in crypto\nbeyond currencies and securities.\n2. Conventional fixed income security markets based on centralized third parties are known\nfor many inherent drawbacks in terms of friction, illiquidity, lack of interoperability,\nasymmetry of information and operational risks. On the other hand, these markets only\nsupport fiat currencies and there is no such market for the cryptocurrency space, which is\ngrowing at a rapid pace.\nSolution\nOur team has been building the network since early 2016, attracting seed funding from three\ninstitutional investors: Boost VC, Startupbootcamp Fintech NYC, Bialla Venture Partners.\nWe are building a blockchain-based fixed income market that will operate similarly in\nconcept to the traditional systems, but will reduce costs, operational friction, and risks along\nwith improved auditability and transparency. Our technology will allow the users to list, buy,\nand sell any type of fixed income securities/financial instruments, including loans, bonds,\ncollateralized loan obligations (CLOs), asset-backed securities (ABS), syndicated loans,\ncredit default swaps (CDS), and futures.\nThe network is primarily meant for financial institutions such as crypto asset managers,\nbanks, investment banks, lending companies, hedge funds, credit funds, insurance\ncompanies, family offices, and corporations, as well as for service providers like valuation\nfirms, auditors, law firms, and ratings agencies. The solution will be opened to individuals in\nlater iterations.\nThis will also open the door to a cryptocurrency fixed income market, a growing need\nin the crypto space. In addition, the currency exchange is integrated into the system,\nenabling the seamless trading of financial instruments among different currencies.\n5\nFIC Network will support the consumer and business loan market in its first phase of\nimplementation and it will then expand into other fixed income financial instruments.\nFIC Token\nFIC token is a utility token, used to perform activities on the network, such as listing, trading,\nand holding financial instruments. It is not backed by, and cannot be exchanged against, any\nfinancial instruments.\nOur Team\nWe have been working on a blockchain based fixed income market model for over a year.\nOur team consists of the right mix of talents, which has been through renowned startup\naccelerators along with VC support.\nOur vision\nOur vision is to become the de facto financial network for the global fixed income market.\nOur mission\nOur mission is to build an end-to-end, blockchain-based fixed income network that enables\nthe participants to source, buy, and sell financial products in a secure, easy, inexpensive,\ntransparent, and accessible way"
state = "1"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"

  [[blockchain.milestone]]
  number = 1.0
  name = "Pre-token eFIC on Ethereum network"
  start_date = "2017 Q4"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 2.0
  name = "Setting up a legal framework for the operation of FIC network Tests with Network Participants on Testnet Enabling the exchange of eFIC to FIC"
  start_date = "2018 Q1"
  current_status = "In work"

  [[blockchain.milestone]]
  number = 3.0
  name = "Launch of FIC Network for loan trading"
  start_date = "2018 Q2"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 4.0
  name = "Cryptocurrency implementation Implementing the ability to trade single ECF separately Listing and trading of corporate bonds"
  start_date = "2019"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 5.0
  name = "Listing and trading of other financial instruments"
  start_date = "2020"
  current_status = "Planned"

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://ficnetwork.com/en"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://s3.amazonaws.com/factury-public-files/FIC+Whitepaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@ficnetwork"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/ficnetwork"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/joinchat/Ch5GRUHJ576RiIkhuYVwuw"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://t.me/joinchat/Ch5GRUHJ576RiIkhuYVwuw"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/ficnetwork"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://ficnetwork.com/"
    sales_agreement = "https://ficnetwork.com/"

    [ico.common_info.token_distribution]
    total_supply = "594666667"

      [[ico.common_info.token_distribution.shares]]
      percent = "50"
      description = "Token sale participants"

      [[ico.common_info.token_distribution.shares]]
      percent = "30"
      description = "Reserves"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "Company"

    [[ico.common_info.use_of_proceeds]]
    percent = "39"
    description = "People and operations"

    [[ico.common_info.use_of_proceeds]]
    percent = "35"
    description = "Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "13"
    description = "Marketing and business development"

    [[ico.common_info.use_of_proceeds]]
    percent = "7"
    description = "Legal"

    [[ico.common_info.use_of_proceeds]]
    percent = "6"
    description = "Services and others"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Pre-sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "316500000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "16000000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-25"
    end_date = "2018-05-15"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "60%"
      condition = "During the Pre-ICO Phase 1 Sale Period, until $2 million is raised"

      [[ico.phases.prices.bonuses]]
      amount = "50%"
      condition = "During the Pre-ICO Phase 2 Sale Period, until $3 million is raised"

      [[ico.phases.prices.bonuses]]
      amount = "40"
      condition = "Day 1 of the public ICO. Each day the discount will go down by 2% down to a minimum of 0%. In the last 10 days of the ICO there will be no more discount"

[[token]]
name = "eFIC token"
symbol = "eFIC"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""

[[app]]
name = "eDepository"
same_blockchain = "true"
sources_availability = "false"
app_status = "2"
app_type = "exe"
app_url = "https://ficnetwork.com/en/download"