app = []

[blockchain]
project_name = "Cibus"
headline = "A FRESH REVOLUTION RESHAPING FOOD ECOSYSTEM 2.0"
short_description = "We at CIBUS realized that small-scale producers all over the world need a place for further development and product launch to the international market which is hitherto seems out of bound for them. Today scaling opportunity for small level traders and manufacturers is chained by various bottlenecks and that is where CIBUS solution gives them a chance to unshackle their true potential. CIBUS hence offers a plethora of services on its platform facilitated by CIBUS token and supported by CIBUS community spread worldwide so that above bottlenecks can easily be unshackled and true business potential can be realised by its users. The CIBUS network is a blockchain-based ecosystem on food and health supplements ensure the origin, quality and fulfilment to transparency. The genesis of CIBUS platform is to bring food and dietary supplements manufacturers, producers, sellers or traders under one functional, interactive, and mutually profitable platform based on blockchain technology and enabling a transparency via trustworthy data sitting on distributed ledger which can be freely accessed by all interested parties; Thus both the business owners and consumers can enjoy best possible transparency, authenticity, and reliability about the food products they are interested in. Production and distribution records maintained in CIBUS blockchain cannot be falsified. Consumer/Buyers, food producers and regulators could use it for rapid trace food products back to their source, to decide quick removal in case of food recall or fraud detection while availing a high degree of transparency. CIBUS Token enables trust less transaction within the platform between all participants. It is the underlying currency for all transactions, mode of payment for transaction fees, escrow services, and advertising and will provide commercial analytics and transactional intelligence. All transacting parties will be required to buy and pay using CIBUS tokens."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://drive.google.com/file/d/1KrPfMOiahljZNWj0Oo-8TunwJrs-Wr-d/view"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://cibus.world/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/cibusworld"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/cibusworld"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2713416.new#new"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/cibusworld"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/cibus_world"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://facebook.com/cibus-1812771722347122/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "http://tokensale.cibus.world/"
    sales_agreement = ""

    [ico.common_info.token_distribution]
    total_supply = "https://cibus.world/"

      [[ico.common_info.token_distribution.shares]]
      percent = "50"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "Marketing & promotion"

      [[ico.common_info.token_distribution.shares]]
      percent = "15"
      description = "CIBUS social rewards"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Team"

      [[ico.common_info.token_distribution.shares]]
      percent = "5"
      description = "Advisers"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Tge bounty"

    [[ico.common_info.use_of_proceeds]]
    percent = "50"
    description = "Platform Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "30"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Legal"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Operations"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Contingency"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "40000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-02-28"
    end_date = "2018-03-28"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "50000 CBT or More: 50% 10000-50000 CBT: 40% Less than 10000 CBT: 30%"
      condition = "TILL FEBRUARY 28, 2018, 10:59 AM (GMT)"

      [[ico.phases.prices.bonuses]]
      amount = "50000 CBT or More: 30% 10000-50000 CBT: 25% Less than 10000 CBT: 20%"
      condition = "February 28, 2018, 11:00 AM (GMT) - March 7, 2018, 10:59 AM (GMT)"

      [[ico.phases.prices.bonuses]]
      amount = "50000 CBT or More: 20% 10000-50000 CBT: 18% Less than 10000 CBT: 16%"
      condition = "March 7, 2018, 11:00 AM (GMT) - March 14, 2018, 10:59 AM (GMT)"

      [[ico.phases.prices.bonuses]]
      amount = "50000 CBT or More: 16% 10000-50000 CBT: 14% Less than 10000 CBT: 12%"
      condition = "March 14, 2018, 11:00 AM (GMT) - March 21, 2018, 10:59 AM (GMT) March 3rd to March  10th, 2018"

      [[ico.phases.prices.bonuses]]
      amount = "50000 CBT or More: 12% 10000-50000 CBT: 10% Less than 10000 CBT: 8%"
      condition = "March 21, 2018, 11:00 AM (GMT) - March 28, 2018, 10:59 AM (GMT)"

[[token]]
name = "CIBUS Token"
symbol = "CIBUS"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""