[blockchain]
project_name = "CryptoGaule"
headline = "The French cryptocurrebcy"
short_description = "CryptoGaule («CGL») является первой независимой французской криптовалютой и ставит целью сделать Францию одним из мировых лидеров в этой области. В этой перспективе Crypto Gaule предложит образовательную платформу, доступную всем, занимающуюся различными вопросами, относящимися к этой области, которые до сих пор не поняты. Для повышения доступности и удобства использования CryptoGaule в качестве платежной системы будет разработана дебетовая карта, которая может использоваться во всех французских компаниях. "
state = "0"
asset_type = ""
dependency = "independent"
consensus_name = "Proof-of-Work"

  [[blockchain.milestone]]
  number = 1.0
  name = "PROJECT STUDY ON CRYPTOCURRENCIES AND THE FRENCH."
  start_date = "2014-09-01"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 2.0
  name = "INSTALLATION OF PAYMENT SYSTEMS INTO SHOPS"
  start_date = "2014-12-01"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 3.0
  name = "FAILED TO INSTALL BITCOIN PAYMENT SYSTEM IN SHOPS"
  start_date = "2016-09-01"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 4.0
  name = "LAUNCH OF THE CRYPTOGAULE PROJECT"
  start_date = "2017-01-01"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 5.0
  name = "CREATION OF THE CRYPTOGAULE BLOCKCHAIN"
  start_date = "2017-07-01"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 6.0
  name = "DEVELOPMENT LAUNCH OF THE CRYPTOGAULE PLATFORM"
  start_date = "2017-09-01"
  current_status = "Completed"

  [[blockchain.milestone]]
  number = 7.0
  name = "PUBLIC LAUNCH OF CRYPTOGAULE AND CRYPTOGAULE PRE-ICO"
  start_date = "2018-03-01"
  current_status = "In work"

  [[blockchain.milestone]]
  number = 8.0
  name = "LAUNCH OF THE MINING INFRASTRUCTURE AND START OF THE ICO"
  start_date = "2018-04-01"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 9.0
  name = "END OF THE ICO"
  start_date = "2018-05-01"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 10.0
  name = "DISTRIBUTION OF THE CGL AND LAUNCH OF PUBLIC MINING. DEVELOPMENT OF MERCHANT SOLUTIONS FOR FRENCH BUSINESSES AND FINALIZATION OF THE DIGITAL MONEY MANAGEMENT PLATFORM."
  start_date = "2018 Q3"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 11.0
  name = "LAUNCH OF THE DEFINED BENEFIT PROTECTION SOLUTION. LAUNCH OF THE E-LEARNING PLATFORM ON BLOCKCHAIN AND CRYPTO CRYPTOGAULE DEBIT CARD USED IN ALL SHOPS!"
  start_date = "2018 Q4"
  current_status = "Planned"

  [[blockchain.milestone]]
  number = 12.0
  name = "LAUNCH OF THE GREEN MINING PROJECT / INVESTMENT IN ALTERNATIVE ENERGIES"
  start_date = "2019 Q1"
  current_status = "Planned"

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://cryptogaule.fr/en/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://cryptogaule.fr/wp/cryptogauleWP-EN.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/cryptogaule_en"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "http://www.facebook.com/cryptogaule/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "http://www.twitter.com/cryptogaule/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/Cryptogaule"
  tags = [
    "Main",
    "Code"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://cryptogaule.fr/en/"
    sales_agreement = "https://cryptogaule.fr/en/"

    [ico.common_info.token_distribution]
    total_supply = "60000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "77"
      description = "Total Sale "

      [[ico.common_info.token_distribution.shares]]
      percent = "8"
      description = "Team & Advisors"

      [[ico.common_info.token_distribution.shares]]
      percent = "6.5"
      description = "Distribution"

      [[ico.common_info.token_distribution.shares]]
      percent = "3"
      description = "Bounty"

      [[ico.common_info.token_distribution.shares]]
      percent = "3"
      description = "Affiliation Bonus"

      [[ico.common_info.token_distribution.shares]]
      percent = "2.5"
      description = "Reserve"

    [[ico.common_info.use_of_proceeds]]
    percent = "39"
    description = "DEVELOPMENT"

    [[ico.common_info.use_of_proceeds]]
    percent = "22.7"
    description = "EDUCATION"

    [[ico.common_info.use_of_proceeds]]
    percent = "19.5"
    description = "MARKETING"

    [[ico.common_info.use_of_proceeds]]
    percent = "9.1"
    description = "TRADING WALL"

    [[ico.common_info.use_of_proceeds]]
    percent = "9.7"
    description = "LEGAL & PARTNERSHIP"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = " pre-ICO"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = "2018-03-01"
    end_date = "2018-03-31"
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "13860000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-01"
    end_date = "2018-03-31"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "USD"
      price = "0,4"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "ICO"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = "2018-03-01"
    end_date = "2018-05-31"
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "32340000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "28644000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-01"
    end_date = "2018-05-31"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = "0.8"

[[token]]
name = "CGL "
symbol = "CGL"
token_purpose = "Utility"
token_type = "Core token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""

[[app]]
name = "CryptoGaule Wallet"
same_blockchain = "true"
sources_availability = "true"
app_status = "2"
app_type = "Web App"
app_url = "https://cryptogaule.fr/en/francais-cryptogaule-wallet-download-en/"