app = []

[blockchain]
project_name = "ViolaAI"
headline = " World’s First AI-driven Marketplace for Dating and Relationship"
short_description = "Singles and couples face numerous challenges in their journey of finding love and sustaining their relationships.\nSingles risk being victims of love scams due to the lack of identity verification, experience online dating fatigue\nand could be exploited by some unethical dating services. On the other hand, couples face difficulty in sustaining\ntheir marriages, exacerbated by uncertainty on where to seek help and which advice to follow. Many are also\nreluctant to share their problems due to concerns of privacy and stigma.\nViola.AI is our solution for singles and couples experiencing these love and relationship challenges.\nViola.AI harnesses on the latest technology in artificial intelligence, cryptocurrency and trustless smart contracts\nto develop a powerful lifelong relationship advisor named Viola and an A.I. and Blockchain driven marketplace\nto create and sustain successful and happy relationships for all singles and couples.\nViola.AI is designed to help achieve the following objectives:\n1) The World’s Most Effective A.I. Advisor and Assistant for Dating and Relationships\n2) The Smartest Blockchain Marketplace for Dating and Relationship\nTo achieve the objectives, Viola.AI is equipped with several core capabilities.\na) A.I. Engine - Provides highly personalized matching and discreet relationship advices which evolve\naccording to the user’s relationship status by employing A.I. with personalised machine learning engine\nand natural language empathy\nb) Blockchain Technology - Protects users through decentralised Real-ID Verification with visual\nrecognition technology, facilitates trustless and efficient transactions with Viola.AI Wallet and Hedged\nEscrow System\nc) Marketplace - Provides timely recommendations to address the user’s needs for goods and services\nfacilitated with Smart Contracts, offers strong community support with quality content and advice that\naddresses user’s enquiry and allows customization of Viola.AI core services on 3rd party platforms\nWe build the VIOLET token to have strong utility. Besides just the Viola.AI app, the VIOLET token will be\nintegrated with our existing ecosystem of 4 apps, 2 websites and 4 offline services (integrated 3rd party\nMerchants/Partners) so that VIOLET tokens can used by its owners almost immediately and with decent scale\nupon its launch. The core utilities of VIOLET Tokens are:\na) Payment Transactions – VIOLET token can be used for payment for goods and services in the 10\nplatforms in our eco-system and with plans to expand into other partners’ ecosystems/platforms.\nb) Advertising to Growing User-base - Merchants/Experts would buy VIOLET tokens to advertise the\ngrowing database, presenting another strong source of utility besides the transactional utility.\nc) Community Token - Users can ask the community questions and upon great content, responses or\nideas given, a reward of VIOLET tokens will be given. Rewards will also be given for referring new users\nor merchants who spend on Viola.AI as a thank you for helping grow the platform.\nThe VIOLET token is instrumental in building up interactivity and growth traction in the Viola.AI community who\nwill be encouraged and rewarded by providing great content to benefit other users and which the Viola.AI engine\ncan learn from, providing the growing data that Viola.AI can grow better and more accurate from.\nViola.AI is driven by the team behind the Lunch Actually Group, a group of proven, passionate and dedicated\nentrepreneurs who are convicted to create better lifetime relationships. Together, the team has combined more\nthan 50 years of experience in the dating and matchmaking industry. CEO Violet Lim is also an acknowledged\nindustry expert who has been featured in more than 4000 local and regional media appearances including\nBloomberg, Huffington Post, CNBC, Forbes, BBC, Channel NewsAsia and many others.\nWe believe Viola.AI will revolutionize and disrupt the world’s dating and relationship industry as it can\nsuccessfully address and resolve the pain points and challenges that singles and couples are facing today. "
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://viola.ai/whitepaper/viola-tech.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://viola.ai/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/ViolaAI"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/viola-ai"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2471543.new#new"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/viola_ai_"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/ViolaAI"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/ViolaAI"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/viola.ai.world"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://viola.ai/"
    sales_agreement = "https://viola.ai/whitepaper/viola-tech.pdf?v=v1.0"

    [ico.common_info.token_distribution]
    total_supply = "250000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "37"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "28"
      description = "Rewards & Bounty Pool"

      [[ico.common_info.token_distribution.shares]]
      percent = "25"
      description = "Company Reserve"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Team & Advisor Pool "

    [[ico.common_info.use_of_proceeds]]
    percent = "37"
    description = "Marketing & Growth"

    [[ico.common_info.use_of_proceeds]]
    percent = "30"
    description = "IT & Content Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "17"
    description = "Working Cap & Others"

    [[ico.common_info.use_of_proceeds]]
    percent = "13"
    description = "Other Manpower"

    [[ico.common_info.use_of_proceeds]]
    percent = "3"
    description = "Governance & Legal"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token sale"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "92500000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "12500000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-14"
    end_date = "2018-03-13"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

      [[ico.phases.prices.bonuses]]
      amount = "20&"
      condition = "First 24 hours"

      [[ico.phases.prices.bonuses]]
      amount = "15%"
      condition = "Day 2 & 3"

      [[ico.phases.prices.bonuses]]
      amount = "10%"
      condition = "Day 4 to 10"

[[token]]
name = "VIOLET token"
symbol = "VAI"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""