[blockchain]
project_name = "SmartO"
headline = "Your super-booster"
short_description = "SmartО-это мобильное приложение с открытым исходным кодом и мощная экспертная система на блокчейн-платформе с уникальным набором функций и простой монетизацией для всех участников. Приложение SmartО объединяет все возможные сервисы для решения повседневных задач, как для рядовых пользователей приложения, так и для бизнеса. Пользователям SmartО поможет не забыть о дне рождения, напомнит о времени принятия лекарств, сориентирует в незнакомой местности, подскажет, где находится хороший ресторан или отель, проинформирует о ценах, покажет отзывы и многое другое. Бизнесу SmartО предлагает комплексное решение по привлечению и удержанию клиентов, а также помогает оптимизировать бизнес-процессы. "
logo = ""
state = "0"
dependency = "Ethereum"
consensus_name = "Proof-of-Work"

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://smarto.im/en"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://smarto.im/images/docs/wp.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/SmartOProject"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@smartoprojectru"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=3023945"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/SmartoProject"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/SmartO_Project"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/user/SmartO_Project/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "http://fb.me/SmartOProject"
  tags = [
    "News"
  ]

  [[blockchain.milestone]]
  number = 1.0
  name = "start of pre-ICO"
  start_date = "2018-04-06"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 2.0
  name = "App prototype"
  start_date = "2018-04-01"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 3.0
  name = "End of pre-ICO"
  start_date = "2018-04-15"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 4.0
  name = "App prototype completion"
  start_date = "2018-05-01"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 5.0
  name = "Listing on exchanges"
  start_date = "2018-09-01"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 6.0
  name = "Test version launch"
  start_date = "2018-09-01"
  end_date = "2018-12-01"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 7.0
  name = "Further App development"
  start_date = "2018-12-01"
  end_date = "2019-08-01"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 8.0
  name = "Establishment of HQ"
  start_date = "2019-08-01"
  current_status = "Planned"
  value = false

  [[blockchain.milestone]]
  number = 9.0
  name = "Further App development"
  start_date = "2019-08-01"
  end_date = "2020-10-01"
  current_status = "Planned"
  value = false

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 1.0
  current_phase_status = ""

    [ico.common_info.token_distribution]
    total_supply = "12000000000"

      [[ico.common_info.token_distribution.shares]]
      description = ""
      percent = 0.0

    [[ico.common_info.use_of_proceeds]]
    percent = "2"
    description = "Exchanges"

    [[ico.common_info.use_of_proceeds]]
    percent = "4"
    description = "SmartO team expansion"

    [[ico.common_info.use_of_proceeds]]
    percent = "6"
    description = "SmartO team"

    [[ico.common_info.use_of_proceeds]]
    percent = "6"
    description = "SmartO partners and advisors"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Headquarters"

    [[ico.common_info.use_of_proceeds]]
    percent = "15"
    description = "Tokenomy marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "SmartO development"

    [[ico.common_info.use_of_proceeds]]
    percent = "37"
    description = "SmartO marketing"

  [[ico.phases]]
  phase_name = "pre-ICO"
  phase_status = "Planned"
  phase_num = 0.0

    [ico.phases.registration]
    start_date = "2018-04-06T00:00:00.000Z"
    end_date = "2018-04-15T00:00:00.000Z"
    website = ""
    terms = "https://smarto.im/images/docs/en/info_5.pdf"

    [ico.phases.terms]
    sales_agreement = "https://smarto.im/images/docs/en/info_5.pdf"
    sales_url = "https://smarto.im/en"
    issued_tokens = "3000000000"
    sold_tokens = 0.0
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = 0.0

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      currency = ""
      address = ""

    [ico.phases.dates]
    start_date = "2018-04-06T00:00:00.000Z"
    end_date = "2018-05-07T00:00:00.000Z"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = 0.0

    [[ico.phases.contract]]
    address = ""
    type = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "USD"
      price = "0.0007"

      [[ico.phases.prices.bonuses]]
      description = ""
      percent = ""

  [[ico.phases]]
  phase_name = "ICO"
  phase_status = "Planned"
  phase_num = 1.0

    [ico.phases.registration]
    start_date = "2018-04-26T00:00:00.000Z"
    end_date = "2018-05-07T00:00:00.000Z"
    website = "https://smarto.im/en"
    terms = "https://smarto.im/images/docs/en/info_5.pdf"

    [ico.phases.terms]
    sales_agreement = "https://smarto.im/images/docs/en/info_5.pdf"
    sales_url = "https://smarto.im/en"
    issued_tokens = "6000000000"
    sold_tokens = 0.0
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "8325000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      currency = ""
      address = ""

    [ico.phases.dates]
    start_date = "2018-04-26T00:00:00.000Z"
    end_date = "2018-05-07T00:00:00.000Z"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = 0.0

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = 0.0

    [[ico.phases.contract]]
    address = ""
    type = ""

    [ico.phases.prices]

      [[ico.phases.prices.token_final_price]]
      currency = "USD"
      price = "0.001"

      [[ico.phases.prices.bonuses]]
      description = ""
      percent = ""

[app]

  [[app.info]]
  name = "SmartO"
  same = "false"
  availability = "true"
  status = "1"
  app_type = "Mobile App"
  app_url = ""

[[token]]
inflation_rate = ""
circulation_terms = ""
governance_rights_org = ""
governance_rights_project = ""
name = "STO Token"
symbol = "STO"
token_purpose = "Utility"
token_type = "Core token"

[[exchange]]
exchange = ""
date = ""
price = ""
volume = ""

[[label]]
blockchain = ""
address = ""
balance = ""