genesis_id = ""
system = "Flip Coin"
dependencies = ["Ethereum"]
icon = "flipcoin"

[token]
name = "flip coin"
symbol = "ATM"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Bridging the gap between Consumer and Crypto"

[crowdsales]
start_date = "2017-09-16T02:00:00"
end_date = "2017-10-16T02:00:00"
end_date_plan = "2017-10-16T02:00:00"
genesis_address = [""]
funding_terms = "https://www.flipcoinsale.com/Whitepaper.pdf"
funding_url = "https://www.flipcoinsale.com/signup/individual"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = ["usd = 5000000"]
raised = [""]

[specs]
supply = 50000000

[[links]]
type = "website"
name = "flipcoinsale.com"
url = "https://www.flipcoinsale.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Flip Coin Whitepaper"
url = "https://www.flipcoinsale.com/Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Flip Coin GitHub"
url = "https://github.com/CoinflipATM/Flipcoin-Sale"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/coinflipatm"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Flip Coin Slack"
url = "https://glacial-harbor-23630.herokuapp.com/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/coinflipatm/"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCo_NsvcSyYZgCd67G65h2dg"
icon = "youtube.png"
tags = ["News"]
