app = []

[blockchain]
project_name = "Algebraix"
headline = "A permission-based advertising platform."
short_description = "The Algebraix Platform and the Personal Secure Vault\nThe Personal Secure Vault (PSV) is the user facing component of the Algebraix\nPlatform. It is a mobile phone application that provides access to the services\nof the Algebraix network. It delivers the following:\n1. A personal secure data store. The mobile app will store encrypted\npersonal data locally, using the Algebraix network for back-up\nand if necessary for overflow storage. Initially, we expect individuals\nto store their basic identity profile data. Eventually they may\nchoose to store some, if not all, of the data we previously described.\nEnd-to-end encryption will ensure that data is accessible only to its\nowner through using a private key. The owner will have the ability\nto grant access to this information to others (individuals or organizations)\nthrough purpose-designed smart contract permissions,\nwhich they alone will be able to set and manage.\n2. Multiple device implementation. The mobile app is designed for\nsynchronizing across multiple mobile devices so the intention is to\nsupport all existing and new mobile devices over time. The mobile\ndevice will be the individual’s gateway to load their data, access to\ntheir data and confer permissions to people or organizations to access\ntheir data if they so choose.\n3. Digital wallet. The mobile app will also be a digital wallet, for storing\nALX tokens earned (or bought) and for paying for any services\nthe network provides. It will include wallets for other cryptocurrencies\nand it will have a secure messaging application built in so\nthat users will be able to send each other direct payments in cryptocurrency\nas well as secure messages.\n4. Video Ad Browsing. The mobile app will enable the user to browse\nthrough and view ads. It will be designed to create a compelling\nuser experience, making the application easy to understand and\nuse when selecting and responding to ads and promotions, and\nalso when uploading data, accessing data, trading from one cryptocurrency\nto another, and reviewing one’s activity.\n5. An anonymized database. All data held by the Algebraix service\nwill be encrypted using cipher AES-256 encryption as a matter of\ncourse to protect it from compromise. The network will house an\nanonymized database of users’ profile data that they have given\npermission to advertisers to use. Advertisers will query the database\nto create target lists of users to whom they will publish ads or\nmake product offers. Individuals will be at liberty to view ads and\nrespond to offers.\nEnd-to-end encryption\nwill ensure that\ndata is accessible only\nto its owner through\nusing a private\nkey. The owner will\nhave the ability to\ngrant access to this\ninformation to others\n(individuals or organizations)\nthrough\npurpose-designed\nsmart contract\npermissions, which\nthey alone will be able\nto set and manage.\nPg. 6\n6. Access to other applications and blockchain services. There is\nalready a wide variety of blockchain-based services for individuals\nand more emerge month by month as new blockchain businesses\nemerge. For example: BitShares offers financial services, Steem\nprovides a social media platform and so on. The mobile app will\nbe built to run applications that provide direct access to such services.\nAlgebraix also intends to provide external developers with an\nability to build applications. Algebraix will create and manage an\nauditing and approval procedure for this."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://algebraix.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://algebraix.io/wp-content/uploads/2018/02/Algebraix_Blockchain_WPv1.12Feb16.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/AlgebraixData/algebraixlib"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/algebraix-data"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/alxtoken"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/Algebraix_Data"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/ALXToken/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/alxtoken/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://complyapi.coinlist.co/algebraix"
    sales_agreement = "https://algebraix.io/wp-content/uploads/2018/02/Coin_Economics1.2Feb17.pdf"

    [ico.common_info.token_distribution]
    total_supply = "100000000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "30"
      description = "SAFT Investors"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "Company Account"

      [[ico.common_info.token_distribution.shares]]
      percent = "50"
      description = "Company Reserve"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token sale"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "30000000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = "25000000 "

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-26"
    end_date = "2018-05-14"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "ALX token"
symbol = "ALX"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""