genesis_id = ""
system = "TrueBit"
dependencies = ["Ethereum"]
icon = "truebit"

[token]
name = "truebit token"
symbol = "TM-TrueBit"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Public"
system_type = "cryptoasset"
headline = "Scalable Verification Solution for Blockchains"

[[links]]
type = "website"
name = "truebit.io"
url = "https://www.truebit.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "TrueBit Whitepaper"
url = "https://people.cs.uchicago.edu/~teutsch/papers/truebit.pdf"
tags = ["Main", "Science"]

[[links]]
type = "blog"
name = "TrueBit Blog"
url = "https://medium.com/truebit"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/Truebitprotocol"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/truebit/"
icon = "reddit.png"
tags = ["News"]
