genesis_id = ""
system = "Fidcom"
dependencies = ["Ethereum"]
icon = "fidcom"

[token]
name = "fidcom token"
symbol = "FIDC"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Decentralized investment company"

[crowdsales]
start_date = "2017-09-19T13:00:00"
end_date = "2017-11-19T13:00:00"
end_date_plan = "2017-10-09T13:00:00"
genesis_address = ["0xd830955B58a9e55Aa1d92c799098909AB9f531a5"]
funding_terms = "https://fidcom.net/wp-content/uploads/2017/08/Fidcom_LP_public_offer.pdf"
funding_url = "https://fidcom.net"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "fidcom.net"
url = "https://fidcom.net/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Fidcom Whitepaper"
url = "https://fidcom.net/wp-content/uploads/2017/08/Whitepaper_en.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Fidcom GitHub"
url = "https://github.com/Bolikus/fidcom/tree/master/contracts"
icon = "github.png"
tags = ["Main","Code"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2180721"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/fidcomnet"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Fidcom Telegram"
url = "https://t.me/fidcom"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/Fidcom-1598716946846558/"
icon = "facebook.png"
tags = ["News"]
