app = []

[blockchain]
project_name = "OCN"
headline = "The first decentralized exchange for one-of-a-kind tokens"
short_description = "Open Collectors Network is the first decentralized platform for one-of-a-kind tokens,\nwhere everyone can seamlessly own, create, customize, interact with and trade individual\ntokens, on an open market, based on existing standard specifications.\n2.1 Vision\nAs founders of Open Collectors Network, we consider ourselves as get-your-hands-dirty\nprogrammers at heart. We love a good technical challenge and since the beginning of 2017 we’ve\nstarted looking into blockchain tech. How the different proof-of-X work, all the hashes out there\nand the special structures, like IOTA & Raiblocks.\nThe more read about the blockchain, the more we saw the beauty in it, and we knew that’s\nwhat we wanted to do from then on. But at some point, it hit us: all the coins out there were just\ncurrency, and like money, they’re fungible. Whereas in our daily jobs, writing code was all about\nworking with things that are non-fungible: like the list of company products, users, roles,\nservices and so on. The list of possible use-cases for unique tokens is virtually endless: the entire\nIT industry depends on it, and if they converted to the blockchain, they’d get all the benefits\ndecentralization brings: security, transparency, trust and the ease of attaching monetary value to\nsomething (virtual currency).\nWith this in mind, we started investigating what exists out there and it seems not a lot.\nJust a newly created Ethereum standard (ERC721, with a couple of other ERC proposals). So that’s\nour vision: to create a decentralized open platform, based on existing standards, for non-fungible\ntokens, all the while making it easy for the IT industry to join the blockchain revolution"
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://opencollectors.network/layout/OpenCollectorsNetwork"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://opencollectors.network/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/cosmingrigore/OpenCollectorsNetwork"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/opencollectorsnetwork"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2881612.0"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/open_collectors"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/opencollectorsnetwork"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "reddit"
  name = "Reddit"
  url = "https://www.reddit.com/r/OpenCollectorsNetwork/"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/OpenCollectorsNetwork"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://opencollectors.network/"
    sales_agreement = "https://opencollectors.network/"

    [ico.common_info.token_distribution]
    total_supply = "150000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "65"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Advisors"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "Founders"

      [[ico.common_info.token_distribution.shares]]
      percent = "13"
      description = "Company"

      [[ico.common_info.token_distribution.shares]]
      percent = "2"
      description = "Bounty"

    [[ico.common_info.use_of_proceeds]]
    percent = "37"
    description = "Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "30"
    description = "Partnerships"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Legal & Operations"

    [[ico.common_info.use_of_proceeds]]
    percent = "3"
    description = "Unforseen"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Active"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "90000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-02-12"
    end_date = "2018-04-15"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "ECTO token"
symbol = "ECTO"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""