app = []

[blockchain]
project_name = "Project Shivom"
headline = "Blockchain based Ecosystem Powering Era of Precision Medicine"
short_description = "Over the last few years, three revolutionary technologies, genomics, artificial intelligence\nand blockchain, have reached the potential to significantly improve global healthcare.\nGenomic medicine has huge implications for the understanding and treatment of as many\nas 7,000 rare diseases, as well as cancers, complex disease such as cardiovascular and\nneurodegenerative, and infections. Likewise, blockchain is the technology that may have\nthe greatest impact on the world economy. Shivom is the next evolutionary step in this\ndevelopment, bringing those technologies together, by creating a medical genomics\necosystem based on next-generation distributed ledger technology. For the first time\never, an ecosystem will offer an open web-marketplace for other providers to add their\napps and services, alongside genomic data analytics and personalized medicine. After\nestablishment of this highly scalable healthcare vertical, we will extend our services to\nform a global network of genomic counselors and associated laboratories for a fully\n\nintegrated service system. Finally, on top of this global ecosystem we will build a not-for-\nprofit R&D organization. Leveraging blockchain technology, the research institute will be\n\nbased on open-innovation, that optimally connects patients, clinicians, researchers,\ninsurers and clinical laboratories to one another. The Shivom platform works on principles\nof collaboration, openness, and integrity allowing patients to own their genomic data,\nhave full access to it, and monetize it on the blockchain. To ensure widespread adoption\nof genomics, we offer a solution where everybody will be able to get their genome\nsequenced and stored. Shivom will deliver genomics to all global healthcare ecosystems,\nreaching even low-income countries and rural areas, where these services have not been\npreviously available, and will provide clinicians and patients with genomic information\n\nthat can be used to guide their decisions about personalized care, protecting research-\nparticipant interests in a manner that promotes maximum public benefit. For each person\n\nit means the genome once uploaded can provide access to the latest health advances for\nmany years to come. Blockchain technology is ideally suited to address most trust issues,\nsuch as patient consent, unclear data ownership, data integrity, or user authentication,\nenabling complex data rights management and fine-grained access using smart contracts.\nUsing state-of-the-art blockchain technology means access to improved data security,\neasier data sharing, increased patient engagement, better quality ‘big data’ analytics,\nenhanced R&D processes, and artificial intelligence-based diagnostics for all participants.\nThe integration of this blockchain platform with population-scale genomics data sets, a\nhealth app marketplace, and global sponsoring programs will create seismic changes in\nhow individuals receive medical care and how therapies will be developed. Our vision is\nfor Shivom to be the largest genomic data-hub on the planet. In doing so, this new\nmassive ecosystem will create value for individuals, not-for-profit organizations,\ngovernments, and for-profit entities."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://shivom.io/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://drive.google.com/file/d/1satOkHzSwj_oqEp2fzIh78t-BUBctmBO/view"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "bitcointalk"
  name = "Bitcointalk"
  url = "https://bitcointalk.org/index.php?topic=2365709.msg24124494#msg24124494"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/projectshivom"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/projshivom"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/ProjectShivom"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://shivom.io/"
    sales_agreement = "https://drive.google.com/file/d/1satOkHzSwj_oqEp2fzIh78t-BUBctmBO/view"

    [ico.common_info.token_distribution]
    total_supply = "3000000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "33"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "14"
      description = "Founders"

      [[ico.common_info.token_distribution.shares]]
      percent = "10"
      description = "early backers and advisors"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "incentivizing growth pool"

      [[ico.common_info.token_distribution.shares]]
      percent = "20"
      description = "reserve fund"

      [[ico.common_info.token_distribution.shares]]
      percent = "3"
      description = "Bounty"

    [[ico.common_info.use_of_proceeds]]
    percent = "20"
    description = "Platform development"

    [[ico.common_info.use_of_proceeds]]
    percent = "11"
    description = "Operations & Business Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "21"
    description = "Marketing & Forming Partnerships"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Legal"

    [[ico.common_info.use_of_proceeds]]
    percent = "2.5"
    description = "Conducting initial sequencing project"

    [[ico.common_info.use_of_proceeds]]
    percent = "5.5"
    description = "Data Storage"

    [[ico.common_info.use_of_proceeds]]
    percent = "25"
    description = "Setting up labs"

    [[ico.common_info.use_of_proceeds]]
    percent = "10"
    description = "Non-profit R&D platform"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "990000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-04-16"
    end_date = "2018-05-16"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "OmiX token"
symbol = "OMX"
token_purpose = "Both"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""