app = []

[blockchain]
project_name = "WISEPLAT"
headline = "WISEPLAT is the next generation blockchain system."
short_description = "The WISEPLAT developers team is ready to implement a new blockchain system project to use the best\nproblem solving approaches accumulated by popular blockchain systems. Laying down the functionality\nand potential at the WISEPLAT architecture design stage will enable us to come up with a best solution\nfor providing fast payments and ensuring a maximum performance of blockchain applications. Keeping\nthe backward compatibility with an enormous number of tools for Ethereum blockchain we provide\nmultiple developers the possibility to effectively use the ready developments in the new WISEPLAT\nblockchain system.\nThe WISEPLAT blockchain system should comply with the following requirements to successfully\nsupport the future development of decentralized applications:\n1. Open source code. The open source code wins the trust of potential users.\n2. Scalability. Ability to process large volumes of transactions.\n3. Free use. Offering a free platform for the application users is a feature of decentralized apps.\n4. Decentralized consensus.\n5. No single point of failure. All data is distributed between all nodes. If one node fails, others continue\noperating independently. In other words, there is no central server that can break down.\n6. Ease of upgrade and mistake correction.\n7. Fast transactions.\n8. Supports apps using concurrent and consecutive computing."
state = "0"
asset_type = ""
dependency = "Ethereum"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://oswiseplat.org/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://oswiseplat.org/whitepaper.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/OSWISEPLAT"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/OSWISEPLAT"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/OSWISEPLAT"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/OSWISEPLAT"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0
  use_of_proceeds = []

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://oswiseplat.org/"
    sales_agreement = "https://oswiseplat.org/faq"

    [ico.common_info.token_distribution]
    total_supply = ""
    shares = []

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Finished"

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = ""
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

      [[ico.phases.terms.crowdsale_addresses]]
      address = "0x06D49e8aA90b1413A641D69c6B8AC154f5c9FE92"
      currency = "ETH"

    [ico.phases.dates]
    start_date = "2017-10-29"
    end_date = "2017-12-31"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

    [[ico.phases.contract]]
    address = "0x81481c47639c8e1BbF07E7b1b868B48EE8bBcd23"

[[token]]
name = "WISE Token"
symbol = "WISE"
token_purpose = "Raising funds"
token_type = "Blockchain issued token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""