genesis_id = ""
system = "Verif-y"
dependencies = ["Ethereum"]
icon = "verif-y"

[token]
name = "verif-y token"
symbol = "VFY"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Blockchain-based Identity for Digital Economy"

[crowdsales]
start_date = "2017-10-05T00:00:00"
end_date = "2017-10-30T00:00:00"
end_date_plan = "2017-10-30T00:00:00"
genesis_address = [""]
funding_terms = "https://www.verif-y.io/"
funding_url = "https://www.verif-y.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[[links]]
type = "website"
name = "verif-y.io"
url = "https://www.verif-y.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Verif-y Whitepaper"
url = "https://www.verif-y.io/vfy-white-paper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/YVerif"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Verif-y Telegram"
url = "https://t.me/VFY_TOKEN"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "slack"
name = "Verif-y Slack"
url = "https://verif-yworkspace.slack.com/messages/@slackbot/"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://www.facebook.com/VerifyInc"
icon = "facebook.png"
tags = ["News"]
