
genesis_id = ""
system = "FansUnite"
dependencies = ["Ethereum"]
icon = "fansunite"

[token]
name = " token"
symbol = ""

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Sports Betting on the Blockchain"

[crowdsales]
start_date = "2017-11-08T09:00:00"
end_date = "2017-12-06T09:00:00"
end_date_plan = "2017-12-06T09:00:00"
genesis_address = [""]
funding_terms = "https://fansunite.io/token-sale"
funding_url = "https://fansunite.io/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 0

[[links]]
type = "website"
name = "fansunite.io"
url = "https://fansunite.io/"
tags = ["Main"]

[[links]]
type = "paper"
name = "FansUnite Whitepaper"
url = "https://fansunite.io/whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "FansUnite Github"
url = "https://github.com/FansUnite12"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = "FansUnite Blog"
url = "https://medium.com/fansunite"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "slack"
name = "FansUnite Slack"
url = "https://fansunite.io/slack"
icon = "slack.png"
tags = ["News"]

[[links]]
type = "custom"
name = " Telegram"
url = "https://t.me/FansUnite"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "reddit"
name = "Reddit"
url = "https://www.reddit.com/r/fansunite/"
icon = "reddit.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = ""
icon = "facebook.png"
tags = ["News"]
