app = []

[blockchain]
project_name = "TIM"
headline = " Geo based multigraph blockchain providing 100 Million TPS "
short_description = "TIM\nevolved from enterprise implementation of blockchain for easing supply chain woes\nfor postal companies like Singapore Post and e-commerce giant Alibaba. The project\nevolved from that phase to become a general purpose platform to provide fast and\nscalable blockchain. We introduced the feature of using geo-location in blockchain to\nidentify and verify the independent nodes. Firstly the geo-location provided many\nbenefits to build an energy wastage free consensus mechanism without\ncompromising the decentralization aspects. It means that this algorithm provides as\nmuch security as proof of work (PoW) so that we need not operate certain privileged\nnodes like in proof of stake (PoS). This is proof of belongingness (PoB). Secondly, the\ngeolocation allowed us to specify coordinates within which a smart contract can\noperate. This makes the smart contracts safer from outside interference. Also we\nextended this feature to host smart contracts having their own blockchain along\nwith geo-fencing. We will go through the details in section of Hyperlocal Dapp. And\nfinally, we designed continuous mining in TIM so that security and integrity can be\nmaintained by community. This mining is also based on geolocation. In this mining\nprocess, nodes verify the location of neighbors based on what they advertise on p2p\nnetwork against a special type of network ping checking. Pinging a computer or\nserver tells you many details about their speed and location. We integrated pinging\nto check location. The attackers will not attack from within the network for getting\ninstantly blocked and burning of stakes for signing 2 headers. The location test is\npart of graph network of TIM which is responsible to collect transactions in a\nspecified region. These graph networks are dynamic triangular regions. We will\nstart the technical discussion with graphs to build on top of graphs for achieving a\nhigh performance blockchain"
state = "0"
asset_type = ""
dependency = "independent"
consensus_name = "Proof-of-Work"
milestone = []

  [[blockchain.links]]
  type = "website"
  name = "Website"
  url = "https://www.talking.im/"
  tags = [
    "Main"
  ]

  [[blockchain.links]]
  type = "paper"
  name = "Paper"
  url = "https://www.talking.im/assets/collat/TIM_Whitepaper_en.pdf"
  tags = [
    "Main",
    "Science"
  ]

  [[blockchain.links]]
  type = "github"
  name = "Github"
  url = "https://github.com/timcoindev"
  tags = [
    "Main",
    "Code"
  ]

  [[blockchain.links]]
  type = "blog"
  name = "Blog"
  url = "https://medium.com/@tim_coin"
  tags = [
    "Main",
    "News"
  ]

  [[blockchain.links]]
  type = "twitter"
  name = "Twitter"
  url = "https://twitter.com/tim_coin"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "telegram"
  name = "Telegram"
  url = "https://t.me/joinchat/GQ9YGFCHzx_vZvglnMdYyA"
  tags = [
    "News"
  ]

  [[blockchain.links]]
  type = "facebook"
  name = "Facebook"
  url = "https://www.facebook.com/TIM_Coin-824457371070141/"
  tags = [
    "News"
  ]

[ico]

  [ico.common_info]
  is_ico = true
  current_ico_phase = 0.0

    [ico.common_info.terms]
    sales_argeement = ""
    sales_url = "https://talking.im/whitelist/home"
    sales_agreement = "http://www.talking.im/assets/collat/TIM_Whitepaper_en.pdf"

    [ico.common_info.token_distribution]
    total_supply = "110000000"

      [[ico.common_info.token_distribution.shares]]
      percent = "91"
      description = "ICO"

      [[ico.common_info.token_distribution.shares]]
      percent = "9"
      description = "Developer + Bounty"

    [[ico.common_info.use_of_proceeds]]
    percent = "45"
    description = "Development"

    [[ico.common_info.use_of_proceeds]]
    percent = "25"
    description = "Marketing"

    [[ico.common_info.use_of_proceeds]]
    percent = "13"
    description = "Partnerships"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Infrastructure"

    [[ico.common_info.use_of_proceeds]]
    percent = "5"
    description = "Legal"

    [[ico.common_info.use_of_proceeds]]
    percent = "7"
    description = "Operations"

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Token Sale"
  phase_status = "Planned"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = "70000000"
    sold_tokens = ""
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "ETH"
      amount = "50000"

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-06-24"
    end_date = "2018-07-08"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

  [[ico.phases]]
  phase_num = 0.0
  phase_name = "Pre-Sale"
  phase_status = "Finished"
  contract = []

    [ico.phases.registration]
    start_date = ""
    end_date = ""
    website = ""
    terms = ""

    [ico.phases.terms]
    issued_tokens = ""
    sold_tokens = "32124067"
    share_of_sold = 0.0
    token_distribution_date = ""
    crowdsale_addresses = []

      [[ico.phases.terms.cap_limit]]
      currency = "USD"
      amount = ""

      [[ico.phases.terms.vesting]]
      supply_percent = 0.0
      lockup_condition = ""
      lockup_date = ""

    [ico.phases.dates]
    start_date = "2018-03-12"
    end_date = "2018-03-24"
    duration = ""

    [[ico.phases.raised_funds]]
    currency = "USD"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "ETH"
    amount = ""

    [[ico.phases.raised_funds]]
    currency = "BTC"
    amount = ""

    [ico.phases.prices]
    bonuses = []

      [[ico.phases.prices.token_final_price]]
      currency = "BTC"
      price = ""

[[token]]
name = "TIM Token"
symbol = "TIM"
token_purpose = "Raising funds"
token_type = "Core token"
inflation_rate = ""
circulation_terms = ""
governance_rights_project = ""
governance_rights_org = ""